<div class="mi-panel-nav"><span class="nav-title">📌 <b>Navegación:</b></span><a href="#introduction" class="z-nav-link">Introducción</a><a href="#methodology" class="z-nav-link">Metodología</a><div class="z-dropdown-container"><button class="z-dropdown-btn" onclick="toggleZMenu(event)">Resultados ▼</button><div class="z-dropdown-menu" id="z-menu-items"><a href="#ETL" onclick="closeZMenu()">Procesamiento de Datos</a><a href="#eda-demografia" onclick="closeZMenu()">Análisis Demográfico</a><a href="#eda-temporal" onclick="closeZMenu()">Análisis Temporal</a><a href="#eda-transaccional" onclick="closeZMenu()">Análisis Transaccional</a><a href="#eda-espacial" onclick="closeZMenu()">Análisis Espacial</a><a href="#client-behaviour" onclick="closeZMenu()">Comportamiento de Compra</a><a href="#FE" onclick="closeZMenu()">Ingeniería de Características</a><a href="#ML" onclick="closeZMenu()">Machine Learning</a><a href="#DL" onclick="closeZMenu()">Deep Learning</a></div></div><a href="#discussion" class="z-nav-link">Discusión</a><a href="#ref" class="z-nav-link">Referencias</a><a href="#anexo" class="z-nav-link">Anexo</a><button id="btn-codigo" class="z-action-btn btn-green" onclick="alternarVisibilidadCodigo()"><span class="txt-boton">💻 Ocultar Código</span><span class="ico-boton">💻</span></button><button id="btn-tema" class="z-action-btn btn-dark" onclick="alternarTema()"><span class="txt-boton">🌙 Modo Oscuro</span><span class="ico-boton">🌙</span></button><div class="z-slider-box"><span class="txt-boton" style="font-weight: bold; color: #555;">↔️ Ancho Página:</span><span class="ico-boton" style="font-weight: bold; color: #555;">↔️</span><input type="range" id="slider-margen" min="50" max="100" value="80" oninput="ajustarMargenPagina(this.value)"><span id="txt-margen" style="font-weight: bold; color: #555;">80%</span></div></div>

<style>
/* Modificamos tu clase inicial directamente para que recupere su comportamiento flotante nativo */
.mi-panel-nav {
  display: flex !important;
  flex-direction: row !important;
  flex-wrap: nowrap !important;
  justify-content: flex-start !important;
  align-items: center !important;
  width: 100% !important;
  padding: 10px 15px 10px 25px !important;
  box-sizing: border-box !important;
  gap: 15px !important;
  background: var(--jp-layout-color1, #f8f9fa) !important;
  border-bottom: 1px solid var(--jp-border-color1, #e9ecef) !important;
  overflow-x: auto !important; /* Mantiene el scroll de seguridad horizontal */
  white-space: nowrap !important;
}

/* Forzar que ningún elemento se aplaste al desplazar lateralmente */
.mi-panel-nav > *, .z-slider-box {
  flex-shrink: 0 !important;
}

/* Enlaces del menú superior */
.z-nav-link, .z-dropdown-btn {
  color: #1a5276 !important;
  text-decoration: none !important;
  font-weight: bold !important;
  font-family: inherit !important;
  font-size: inherit !important;
  background: none !important;
  border: none !important;
  cursor: pointer !important;
  padding: 0 !important;
}

/* Contenedor del botón desplegable */
.z-dropdown-container {
  position: relative !important;
  display: inline-block !important;
}

/* MENÚ FLOTANTE: Usando position: fixed para que pinte encima sin romper el scroll de la barra */
.z-dropdown-menu {
  display: none;
  position: fixed !important;
  background-color: white !important;
  min-width: 220px !important;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.15) !important;
  z-index: 999999 !important;
  flex-direction: column !important;
  padding: 5px 0 !important;
  border-radius: 4px !important;
  border: 1px solid #ddd !important;
}

.z-dropdown-menu a {
  padding: 8px 15px !important;
  font-weight: normal !important;
  color: #333 !important;
  text-align: left !important;
  display: block !important;
  text-decoration: none !important;
}

.z-dropdown-menu a:hover {
  background-color: #f1f1f1 !important;
  color: #1a5276 !important;
}

/* Estilos de botones de acción */
.z-action-btn {
  padding: 4px 10px !important;
  cursor: pointer !important;
  border-radius: 4px !important;
  background: var(--jp-layout-color1, white) !important;
  font-weight: bold !important;
}

.btn-green {
  border: 1px solid var(--jp-border-color1, #27ae60) !important;
  color: #27ae60 !important;
  margin-left: 10px !important;
}

.btn-dark {
  border: 1px solid #2c3e50 !important;
  color: #2c3e50 !important;
}

#slider-margen {
  cursor: pointer !important;
  vertical-align: middle !important;
  width: 80px !important;
}

.z-slider-box {
  display: inline-flex !important;
  align-items: center !important;
  gap: 5px !important;
  font-family: sans-serif !important;
  font-size: 13px !important;
}

.ico-boton {
  display: none !important;
}

/* Centrado vertical adaptado al clic */
[id] {
  scroll-margin-top: 25vh !important;
  scroll-behavior: smooth !important;
}

@media (max-width: 1024px) {
  .mi-panel-nav {
    font-size: 13px !important;
    gap: 10px !important;
  }
  .txt-boton {
    display: none !important;
  }
  .ico-boton {
    display: inline !important;
  }
}
</style>

<script>
window.toggleZMenu = function(event) {
    event.stopPropagation();
    const btn = event.currentTarget;
    const menu = document.getElementById('z-menu-items');
    
    if (menu.style.display === 'flex') {
        menu.style.display = 'none';
    } else {
        const bounds = btn.getBoundingClientRect();
        menu.style.top = bounds.bottom + 'px';
        menu.style.left = bounds.left + 'px';
        menu.style.display = 'flex';
    }
};

window.closeZMenu = function() {
    const menu = document.getElementById('z-menu-items');
    if (menu) menu.style.display = 'none';
};

window.addEventListener('click', window.closeZMenu);
document.addEventListener('scroll', window.closeZMenu, true);
if(document.querySelector('.mi-panel-nav')) {
    document.querySelector('.mi-panel-nav').addEventListener('scroll', window.closeZMenu);
}

function ajustarMargenPagina(porcentajeAncho) {
    document.getElementById('txt-margen').innerText = porcentajeAncho + '%';
    const contenedor = document.getElementById('notebook-container') 
                     || document.querySelector('.jp-Notebook') 
                     || document.getElementById('notebook');
    if (contenedor) {
        contenedor.style.maxWidth = porcentajeAncho + '%';
        contenedor.style.marginLeft = 'auto';
        contenedor.style.marginRight = 'auto';
    }
}
</script>

In [9]:
from IPython.display import HTML, display

diseno_unificado = """
<style>
  /* CONFIGURACIÓN DE MÁRGENES SIMÉTRICOS ESTILO ACADÉMICO (2.0 cm) */
  body,
  .jp-Notebook {
    padding-left: 2.0cm !important;
    padding-right: 2.0cm !important;
    box-sizing: border-box !important;
    /* Ajuste clave: Permitir que el background cambie dinámicamente con la variable */
    background-color: var(--jp-layout-color1) !important; 
  }

  /* REGLA DE EQUILIBRIO INTERNO */
  .jp-Cell-inputWrapper,
  .jp-OutputArea-child {
    display: flex !important;
    flex-direction: row !important;.
    width: 100% !important;
    box-sizing: border-box !important;
    padding-left: 15px !important;
    padding-right: 15px !important;
  }

  .jp-InputArea-editor,
  .jp-OutputArea-output,
  .jp-RenderedText,
  .jp-RenderedHTMLCommon {
    flex: 1 !important;
    min-width: 0 !important;
    width: 100% !important;
    box-sizing: border-box !important;
    display: block !important;
  }

  /* CLASE CSS DINÁMICA DE CONTROL DE VISIBILIDAD (Para el botón) */
  .jp-Cell-inputWrapper.ocultar-bloque-codigo {
    display: none !important;
  }

  /* FORMATO Y SCROLL VERTICAL EXCLUSIVO PARA DATAFRAMES */
  .jp-RenderedHTMLCommon:has(table) {
    max-height: 450px !important;    
    overflow-y: auto !important;     
    overflow-x: auto !important;     
    width: 100% !important;
    box-sizing: border-box !important;
    margin-bottom: 1em !important;
    background-color: var(--jp-layout-color1) !important;
  }

  .jp-RenderedHTMLCommon table {
    display: table !important;       
    max-width: 100% !important;
    white-space: nowrap !important;
    margin-left: auto !important;    
    margin-right: auto !important;
    background-color: var(--jp-layout-color1) !important;
    color: var(--jp-ui-font-color1) !important;
  }

  .jp-RenderedHTMLCommon table th,
  .jp-RenderedHTMLCommon table td {
    white-space: nowrap !important;
    border: 1px solid var(--jp-border-color2) !important;
  }

  /* 1. Fondo sombreado sutil para los títulos de las columnas (client_id, gender, etc.) */
  .jp-RenderedHTMLCommon table thead tr:nth-child(1) th,
  table.dataframe thead tr:nth-child(1) th {
    background-color: #f5f5f5 !important; 
    font-weight: bold !important;
  }

  /* 2. Forzar que la fila de tipos de datos (i64, cat) se mantenga con fondo blanco */
  .jp-RenderedHTMLCommon table thead tr:nth-child(2) th,
  .jp-RenderedHTMLCommon table thead tr:nth-child(2) td,
  table.dataframe thead tr:nth-child(2) th,
  table.dataframe thead tr:nth-child(2) td {
    background-color: #ffffff !important;
    font-style: italic !important;        
    font-weight: bold !important;     
    color: #666666 !important;            
  }

  /* 3. El sombreado gris empieza estrictamente en la primera fila de datos reales (Impares) */
  .jp-RenderedHTMLCommon table tbody tr:nth-child(odd) td,
  table.dataframe tbody tr:nth-child(odd) td {
    background-color: #f9f9f9 !important; 
  }

  /* 4. Dejamos las filas pares totalmente blancas */
  .jp-RenderedHTMLCommon table tbody tr:nth-child(even) td,
  table.dataframe tbody tr:nth-child(even) td {
    background-color: #ffffff !important;
  }

  /* FORMATO Y SALIDA DE TEXTO DE CONSOLA (PRINT Y .SHOW) */
  .jp-RenderedText pre,
  .jp-RenderedText code {
    display: block !important;
    overflow-x: auto !important;
    overflow-y: auto !important;
    max-width: fit-content !important;
    max-height: 300px !important;
    white-space: pre-wrap !important;
    word-break: break-all !important;
    margin-left: auto !important;
    margin-right: auto !important;
    padding: 10px !important;
    box-sizing: border-box !important;
    text-align: left !important;
    background-color: var(--jp-layout-color2) !important;
    color: var(--jp-ui-font-color1) !important;
  }

  /* CENTRADO DE PLOTLY */
  .plotly-graph-div,
  .plotly-graph-div-container,
  .user-select-none {
    margin-left: auto !important;
    margin-right: auto !important;
    display: block !important;
  }

  /* OCULTAR TEXTO DE PROMPTS COMPLETAMENTE */
  .jp-InputPrompt,
  .jp-OutputPrompt,
  .jp-InputArea-prompt,
  .jp-OutputArea-prompt,
  .prompt {
    visibility: hidden !important;
    width: 0px !important;
    min-width: 0px !important;
    max-width: 0px !important;
    padding: 0 !important;
    margin: 0 !important;
  }

  /* BARRA DE NAVEGACIÓN SUPERIOR FIJA */
  .jp-NotebookPanel-main, .jp-WindowedPanel-outer {
    position: relative !important;
  }

  .mi-panel-nav {
    position: fixed !important;
    top: 0 !important;
    left: 0 !important;
    width: 100% !important;
    height: 56px !important;
    box-sizing: border-box !important;
    background-color: var(--jp-layout-color1) !important;
    border-bottom: 2px solid var(--jp-border-color2) !important;
    display: flex !important;
    align-items: center !important;
    justify-content: center !important;
    gap: 28px !important;
    padding: 0 20px !important;
    z-index: 10000 !important;
    box-shadow: 0 4px 6px rgba(0,0,0,0.1) !important;
  }

  .mi-panel-nav .nav-title {
    display: flex !important;
    align-items: center !important;
    height: 56px !important;
    margin: 0 !important;
    padding: 0 !important;
    white-space: nowrap !important;
  }

  .mi-panel-nav .nav-title b {
    color: var(--jp-ui-font-color0) !important;
  }

  .mi-panel-nav > a {
    display: flex !important;
    align-items: center !important;
    height: 56px !important;
    margin: 0 !important;
    padding: 0 !important;
    color: var(--jp-content-link-color) !important;
    font-weight: bold !important;
    text-decoration: none !important;
    white-space: nowrap !important;
  }

  .mi-panel-nav > a:hover {
    color: var(--jp-content-link-hover-color) !important;
    text-decoration: underline !important;
  }

  .nav-dropdown {
    position: relative !important;
    display: flex !important;
    align-items: center !important;
    height: 56px !important;
    margin: 0 !important;
    padding: 0 !important;
  }

  .nav-dropdown summary {
    display: flex !important;
    align-items: center !important;
    height: 56px !important;
    margin: 0 !important;
    padding: 0 !important;
    color: var(--jp-content-link-color) !important;
    font-weight: bold !important;
    cursor: pointer !important;
    white-space: nowrap !important;
    list-style: none !important;
  }

  .nav-dropdown summary::-webkit-details-marker {
    display: none !important;
  }

  .nav-dropdown summary::after {
    content: " ▼";
    font-size: 11px !important;
    margin-left: 5px !important;
  }

  .nav-dropdown summary:hover {
    color: var(--jp-content-link-hover-color) !important;
  }

  .nav-submenu {
    position: absolute !important;
    top: 56px !important;
    left: 50% !important;
    transform: translateX(-50%) !important;
    min-width: 100px !important;
    padding: 6px 0 !important;
    background-color: var(--jp-layout-color1) !important;
    border: 1px solid var(--jp-border-color2) !important;
    box-shadow: 0 4px 8px rgba(0,0,0,0.15) !important;
    z-index: 10001 !important;
  }

  .nav-submenu a {
    display: block !important;
    padding: 8px 16px !important;
    margin: 0 !important;
    color: var(--jp-content-link-color) !important;
    font-weight: bold !important;
    text-decoration: none !important;
    white-space: nowrap !important;
  }
  
  .nav-submenu a:hover {
    background-color: var(--jp-layout-color2) !important;
    color: var(--jp-content-link-hover-color) !important;
  }

  /* 🌟 AQUÍ COLOCAS EL NUEVO BLOQUE DE ESTILOS OSCUROS 🌟 */
  /* Fuerza el fondo oscuro si Jupyter no cambia la variable automáticamente */
  /* ======================================================================== */
  /* 🌟 CORRECCIÓN DEFINITIVA PARA EL MODO OSCURO (REEMPLAZA EL ANTERIOR)    */
  /* ======================================================================== */

  /* 1. Fondo general y textos principales */
  body.tema-oscuro, 
  body.tema-oscuro .jp-Notebook,
  body.tema-oscuro .jp-Cell,
  body.tema-oscuro .jp-Cell-inputWrapper,
  body.tema-oscuro .jp-MarkdownOutput,
  body.tema-oscuro .jp-RenderedHTMLCommon {
    background-color: #121212 !important;
    color: #e0e0e0 !important;
  }

  /* 2. Encabezados (Títulos H1, H2, H3, etc.) */
  body.tema-oscuro h1, 
  body.tema-oscuro h2, 
  body.tema-oscuro h3, 
  body.tema-oscuro h4, 
  body.tema-oscuro h5, 
  body.tema-oscuro h6,
  body.tema-oscuro h1 *, 
  body.tema-oscuro h2 *, 
  body.tema-oscuro h3 * {
    color: #ffffff !important;
  }

  /* 3. Párrafos y texto plano de Markdown */
  body.tema-oscuro p,
  body.tema-oscuro li,
  body.tema-oscuro span {
    color: #e0e0e0 !important;
  }

  /* Excepción para las etiquetas de código inline dentro del texto (ej: id, date) */
  body.tema-oscuro p code,
  body.tema-oscuro li code {
    background-color: #2d2d2d !important;
    color: #f8f6f0 !important;
    padding: 2px 6px !important;
    border-radius: 4px !important;
  }

  /* 4. REPARACIÓN TOTAL DE DATAFRAMES (TABLAS) */
  body.tema-oscuro .jp-RenderedHTMLCommon:has(table),
  body.tema-oscuro .jp-RenderedHTMLCommon table,
  body.tema-oscuro table.dataframe {
    background-color: #1e1e1e !important;
    color: #ffffff !important;
    border: 1px solid #3c3c3c !important;
  }

  /* Filas, encabezados y celdas individuales */
  body.tema-oscuro .jp-RenderedHTMLCommon table tr,
  body.tema-oscuro .jp-RenderedHTMLCommon table th,
  body.tema-oscuro .jp-RenderedHTMLCommon table td,
  body.tema-oscuro table.dataframe tr,
  body.tema-oscuro table.dataframe th,
  body.tema-oscuro table.dataframe td {
    background-color: #1e1e1e !important; /* Quita el fondo blanco de las celdas */
    color: #ffffff !important;            /* Fuerza el texto a blanco */
    border: 1px solid #3c3c3c !important; /* Bordes sutiles oscuros */
  }

  /* Encabezado principal de la tabla */
  body.tema-oscuro .jp-RenderedHTMLCommon table thead th,
  body.tema-oscuro table.dataframe thead th {
    background-color: #2d2d2d !important;
    color: #58a6ff !important;            /* Color azul académico para resaltar columnas */
    font-weight: bold !important;
  }

  /* Alternancia de filas (Zebra striping) corregida para pintar las celdas por dentro */
  body.tema-oscuro .jp-RenderedHTMLCommon table tbody tr:nth-child(odd) td,
  body.tema-oscuro table.dataframe tbody tr:nth-child(odd) td {
    background-color: #252526 !important; /* El sombreado gris empieza en la primera fila */
  }

  /* Dejamos las filas pares totalmente limpias/transparentes */
  body.tema-oscuro .jp-RenderedHTMLCommon table tbody tr:nth-child(even) td,
  body.tema-oscuro table.dataframe tbody tr:nth-child(even) td {
    background-color: transparent !important; 
  }


  /* 5. Barra de Navegación Superior */
  body.tema-oscuro .mi-panel-nav {
    background-color: #1e1e1e !important;
    border-bottom: 2px solid #333333 !important;
  }

  body.tema-oscuro .mi-panel-nav .nav-title b {
    color: #ffffff !important;
  }

  body.tema-oscuro .mi-panel-nav > a,
  body.tema-oscuro .nav-dropdown summary {
    color: #58a6ff !important;
  }

  body.tema-oscuro .nav-submenu {
    background-color: #1e1e1e !important;
    border: 1px solid #333333 !important;
  }

  body.tema-oscuro .nav-submenu a {
    color: #58a6ff !important;
  }

  body.tema-oscuro .nav-submenu a:hover {
    background-color: var(--jp-layout-color2) !important;
    color: var(--jp-content-link-hover-color) !important;
  }


  /* 🔑 ¡AQUÍ PEGAS EL NUEVO CÓDIGO QUE TE ACABO DE DAR! */
  /* ======================================================================== */
  /* 🛠️ SOLUCIÓN A LOS PARCHES BLANCOS EN CELDAS DE CÓDIGO                    */
  /* ======================================================================== */

  /* 1. Corrige el fondo de los contenedores de código de Jupyter */
  body.tema-oscuro .jp-InputArea-editor,
  body.tema-oscuro .jp-InputArea-inner,  
  body.tema-oscuro .input_area,           
  body.tema-oscuro .jp-CodeCell .highlight,  
  body.tema-oscuro .jp-CodeMirrorEditor,
  body.tema-oscuro .cm-editor,
  body.tema-oscuro .cm-scroller,
  body.tema-oscuro .highlight pre,
  body.tema-oscuro .highlight {
    background-color: #1e1e1e !important; 
    color: #f8f6f0 !important;
  }

  /* 2. Asegura que el texto plano dentro del código no sea invisible */
  body.tema-oscuro .cm-line,
  body.tema-oscuro .jp-CodeMirrorEditor .CodeMirror-line {
    background-color: transparent !important;
    color: #e0e0e0 !important;
  }

  /* 3. Corrección estética del botón "Modo Claro" en el panel nav oscuro */
  body.tema-oscuro #btn-tema {
    background: #2d3139 !important;
    color: #f1c40f !important; 
    border: 1px solid #f1c40f !important;
  }

  /* 4. Corrección para los enlaces (Links como el de GitHub) */
  body.tema-oscuro a {
    color: #58a6ff !important; 
  }
  body.tema-oscuro a:hover {
    color: #79c0ff !important;
    text-decoration: underline !important;
  }

  body.tema-oscuro .jp-OutputArea-output,
  body.tema-oscuro .jp-RenderedText,
  body.tema-oscuro .jp-RenderedText pre {
    background-color: #1e1e1e !important;
    color: #e0e0e0 !important;
    border: 1px solid #3c3c3c !important;
  }

  /* Corrección estética del botón "Ocultar Código" en el panel nav oscuro */
  body.tema-oscuro #btn-codigo {
    background: #2d3139 !important; /* Mismo fondo gris oscuro que el botón de tema */
    color: #27ae60 !important;      /* Mantiene su texto verde característico */
    border: 1px solid #27ae60 !important; /* Borde verde a juego */
  }

  /* ======================================================================== */
  /* 🎨 PALETA DE SINTAXIS EXACTA JUPYTER LAB DARK (MÁXIMA FIDELIDAD)        */
  /* ======================================================================== */

  /* Texto base, variables y operadores (=, +, y nombres como amountchip_fraud_unbiased_df) */
  body.tema-oscuro .highlight,
  body.tema-oscuro .highlight pre,
  body.tema-oscuro .cm-line,
  body.tema-oscuro .highlight .o {
    color: #e6edf3 !important; /* Blanco tiza limpio original */
  }

  /* Palabras clave de control (import, from, as, for, in, if) */
  body.tema-oscuro .highlight .k,
  body.tema-oscuro .highlight .kn,
  body.tema-oscuro .highlight .kr,
  body.tema-oscuro .cm-keyword { 
    color: #4caf50 !important; /* Verde brillante e idéntico al original */
    font-weight: bold !important;
  }

  /* Nombres de módulos/paquetes importados (polars, pandas, datetime) */
  body.tema-oscuro .highlight .nn,
  body.tema-oscuro .highlight .ne { 
    color: #e6edf3 !important; /* Blanco neutro, sin destacar en azul */
  }

  /* Cadenas de texto / Strings (Rutas, "Fraudulent", "date") */
  body.tema-oscuro .highlight .s,
  body.tema-oscuro .highlight .s1,
  body.tema-oscuro .highlight .s2,
  body.tema-oscuro .highlight .se,
  body.tema-oscuro .cm-string { 
    color: #ff7070 !important; /* Rojo ocre / ladrillo original */
  }

  /* Números e índices (2010, 1, 8, 4, 19, 22) */
  body.tema-oscuro .highlight .mi,
  body.tema-oscuro .highlight .mf,
  body.tema-oscuro .cm-number { 
    color: #4caf50 !important; /* Azul cian / verde agua original */
  }

  /* Funciones y métodos nativos de Python (print, len) */
  body.tema-oscuro .highlight .nb,
  body.tema-oscuro .cm-builtin {
    color: #ffa657 !important; /* Ocre/Naranja sutil para funciones built-in */
  }

  /* Métodos de objetos (.scan_parquet, .filter, .with_columns, .show) */
  body.tema-oscuro .highlight .nf,
  body.tema-oscuro .highlight .fm,
  body.tema-oscuro .cm-property {
    color: #aa22ff !important; /* Violeta/Púrpura claro característico */
  }

  /* ======================================================================== */
  /* 💜 ADICIÓN: VIOLETA PARA SÍMBOLOS, OPERADORES Y COMANDOS BASH          */
  /* ======================================================================== */

  /* Signo igual (=) y operadores especiales */
  body.tema-oscuro .highlight .o,
  body.tema-oscuro .cm-operator,
  body.tema-oscuro .highlight .ch {
    color: #ff7070 !important; /* Nota: Si el '=' original comparte color con strings */
  }

  /* Si en tu captura original el '=' y el '!' son exactamente del mismo violeta: */
  body.tema-oscuro .highlight .o,
  body.tema-oscuro .highlight .im,
  body.tema-oscuro .highlight .bp,
  body.tema-oscuro .highlight .ge {
    color: #aa22ff !important; /* Este es el violeta/púrpura exacto que extrajimos */
  }

  /* 1. Puntos (.) en Violeta */
  body.tema-oscuro .highlight .nd,
  body.tema-oscuro .highlight .nc,
  body.tema-oscuro .cm-property {
    color: #aa22ff !important; /* Violeta original */
  }

  /* 2. Paréntesis y Corchetes (), [] en Azul Celeste */
  body.tema-oscuro .highlight .p,
  body.tema-oscuro .cm-punctuation {
    color: #58a6ff !important; /* Azul celeste original */
  }

  /* 3. Valores Booleanos (True, False) en Verde Brillante */
  body.tema-oscuro .highlight .kc,
  body.tema-oscuro .cm-atom {
    color: #4caf50 !important; /* Mismo verde que 'import' y 'from' */
    font-weight: bold !important;
  }

  /* Corrección específica de color para la fila de tipos de datos en Modo Oscuro */
  body.tema-oscuro .jp-RenderedHTMLCommon table thead tr:nth-child(2) th,
  body.tema-oscuro .jp-RenderedHTMLCommon table thead tr:nth-child(2) td,
  body.tema-oscuro table.dataframe thead tr:nth-child(2) th,
  body.tema-oscuro table.dataframe thead tr:nth-child(2) td {
    background-color: transparent !important; /* Quita el fondo blanco en modo oscuro */
    color: #8b949e !important;                /* Gris atenuado ideal para fondo negro */
    font-style: italic !important;            /* Reafirma la cursiva en modo oscuro */
    font-weight: bold !important;
  }


</style>

<script>
  // 🌟 FUNCIÓN ORIGINAL REPARADA PARA VISIBILIDAD DE CÓDIGO
  function alternarVisibilidadCodigo() {
    var celdasCodigo = document.querySelectorAll('.jp-CodeCell .jp-Cell-inputWrapper');
    var boton = document.getElementById('btn-codigo');
    if (celdasCodigo.length === 0 || !boton) return;

    var yaEstanOcultas = celdasCodigo[0].classList.contains('ocultar-bloque-codigo');

    celdasCodigo.forEach(function(celda) {
      if (yaEstanOcultas) {
        celda.classList.remove('ocultar-bloque-codigo');
      } else {
        celda.classList.add('ocultar-bloque-codigo');
      }
    });

    // 🌟 REPARACIÓN INTERACTIVA: Detectamos si la página está en modo oscuro
    var esModoOscuro = document.body.classList.contains('tema-oscuro');

    if (yaEstanOcultas) {
      boton.innerHTML = "💻 Ocultar Código";
      boton.style.color = "#27ae60";
      boton.style.borderColor = "#27ae60";
      // Si está oscuro, forzamos fondo oscuro; si no, fondo claro
      boton.style.background = esModoOscuro ? "#2d3139" : "var(--jp-layout-color1, white)";
    } else {
      boton.innerHTML = "👁️ Mostrar Código";
      boton.style.color = "#e67e22";
      boton.style.borderColor = "#e67e22";
      boton.style.background = esModoOscuro ? "#2d3139" : "var(--jp-layout-color1, white)";
    }
  }

  // 🌟 NUEVA FUNCIÓN INTERACTIVA PARA PASAR A DARK THEME
  // 🌟 JAVASCRIPT CORREGIDO PARA EL CAMBIO DE TEMA NATIVO
  function alternarTema() {
    var body = document.body;
    var botonTema = document.getElementById('btn-tema');
    if (!botonTema) return;

    // Verificamos si ya está activo el tema oscuro nativo de Jupyter
    var esOscuro = body.getAttribute('data-jp-theme-light') === 'false' || body.classList.contains('tema-oscuro');

    if (esOscuro) {
      // ☀️ VOLVER A MODO CLARO
      body.classList.remove('tema-oscuro');
      body.setAttribute('data-jp-theme-light', 'true');
      body.setAttribute('data-jp-theme-name', 'JupyterLab Light');
      
      // Actualización visual del botón
      botonTema.innerHTML = "🌙 Modo Oscuro";
      botonTema.style.color = "#2c3e50";
      botonTema.style.borderColor = "#2c3e50";
    } else {
      // 🌙 PASAR A MODO OSCURO
      body.classList.add('tema-oscuro');
      body.setAttribute('data-jp-theme-light', 'false');
      body.setAttribute('data-jp-theme-name', 'JupyterLab Dark');
      
      // Actualización visual del botón
      botonTema.innerHTML = "☀️ Modo Claro";
      botonTema.style.color = "#f1c40f";
      botonTema.style.borderColor = "#f1c40f";
    }
  }


  // CENTRADO DE GRÁFICOS (Plotly)
  function forzarCentradoPlotly() {
    var graficos = document.querySelectorAll('.plotly-graph-div, .js-plotly-plot');
    graficos.forEach(function(grafico) {
      grafico.style.setProperty('margin-left', 'auto', 'important');
      grafico.style.setProperty('margin-right', 'auto', 'important');
      grafico.style.setProperty('display', 'block', 'important');

      var contenedorPadre = grafico.parentElement;
      if (contenedorPadre) {
        contenedorPadre.style.setProperty('display', 'flex', 'important');
        contenedorPadre.style.setProperty('justify-content', 'center', 'important');
        contenedorPadre.style.setProperty('width', '100%', 'important');
      }
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener("DOMContentLoaded", forzarCentradoPlotly);
  } else {
    forzarCentradoPlotly();
    setTimeout(forzarCentradoPlotly, 600);
  }
</script>
"""

display(HTML(diseno_unificado))

# **ANÁLISIS DE FRAUDE FINANCIERO**

---

#### Autor: Diego Alexander Zambrano Tipán

#### e-mail: diegozt91@gmail.com

#### https://github.com/diegozt91-dotcom/financial-fraud-MLOps

---

## <span id="introduction"></span> **1. INTRODUCCIÓN**

El fraude financiero asociado a las transacciones digitales constituye un problema de creciente relevancia a escala global y, particularmente, en Europa. En 2022, el valor total de las pérdidas económicas derivadas del fraude alcanzó los 4.300 millones de euros, mientras que en 2024 se registró un incremento del 24 % en el fraude financiero con respecto al año anterior <cite id="iezgp"><a href="#zotero%7C24849794%2F8RUI7M59">(Jendruszak, 2024)</a></cite>. Este problema se ha visto agravado por la transformación experimentada por los servicios financieros durante los últimos años.

La pandemia de COVID-19 aceleró significativamente la digitalización de los servicios financieros y el desplazamiento de numerosas operaciones desde entornos presenciales hacia plataformas digitales. Esta transformación no solo incrementó el volumen y la disponibilidad de datos financieros, sino que también generó nuevas oportunidades para la comisión de actividades fraudulentas y dificultó su detección. La mayor utilización de servicios bancarios y transacciones remotas, junto con la aparición y evolución continua de nuevos productos y servicios digitales, ha contribuido a aumentar la complejidad y sofisticación de los esquemas de fraude <cite id="gknvb"><a href="#zotero%7C24849794%2F7BUIWEJW">(Zhu et al., 2021)</a></cite>. En consecuencia, los sistemas de detección requieren métodos cada vez más rápidos, robustos e interpretables, capaces de procesar grandes volúmenes de información y adaptarse a patrones de comportamiento cambiantes.

La detección del fraude con tarjetas de crédito constituye, además, un problema especialmente complejo debido al elevado desequilibrio existente entre las transacciones legítimas y fraudulentas, así como a la necesidad de minimizar tanto los falsos positivos como los falsos negativos. En este contexto, los métodos tradicionales y los modelos estáticos pueden presentar limitaciones frente a estrategias fraudulentas que evolucionan continuamente, haciendo necesario incorporar información que permita caracterizar no solo las transacciones individuales, sino también el comportamiento histórico de los clientes.

Los estudios previos han destacado precisamente la utilidad de la ingeniería de características para incorporar información contextual y temporal relacionada con el comportamiento de los usuarios. Entre estas técnicas se encuentra el análisis de secuencias de transacciones y la generación de variables agregadas mediante medidas estadísticas como promedios, desviaciones estándar, intervalos de confianza y características periódicas basadas en la distribución de von Mises <cite id="nrgi8"><a href="#zotero%7C24849794%2FBTXFK83Q">(Correa Bahnsen et al., 2016)</a></cite>. Estas características permiten representar patrones de gasto y comportamiento histórico que pueden contribuir a distinguir las transacciones fraudulentas de las legítimas.

En este contexto, el uso de técnicas de *machine learning* y *deep learning* ha adquirido especial relevancia para la detección automática del fraude. Entre los enfoques empleados se encuentran los algoritmos *ensemble* basados en árboles de decisión, así como arquitecturas basadas en redes neuronales capaces de aprender relaciones complejas presentes en los datos.

Por tanto, en este trabajo se ha llevado a cabo el análisis, procesamiento y modelado de un conjunto de datos de transacciones financieras disponible en Kaggle, compuesto por millones de transacciones e información relacionada con los usuarios, las tarjetas utilizadas y los comercios asociados a cada transacción <cite id="fp5i5"><a href="#zotero%7C24849794%2FT98H6WQU">(Caixabank Tech, n.d.)</cite>. A partir de estos datos se han desarrollado diferentes características orientadas a representar tanto las propiedades individuales de las transacciones como el comportamiento histórico y temporal de los clientes. Posteriormente, se han evaluado diferentes algoritmos de aprendizaje automático y aprendizaje profundo con el objetivo de analizar su capacidad para identificar transacciones fraudulentas en un escenario caracterizado por un elevado desequilibrio de clases.

---

## <span id="methodology"></span> **2. METODOLOGÍA**

El dataset analizado se encuentra alojado en la siguiente url:  
https://www.kaggle.com/datasets/computingvictor/transactions-fraud-datasets  
En la misma url se describe este dataset como un conjunto de datos financieros que combina registros de transacciones, información de clientes y datos de tarjetas de una institución bancaria, abarcando el periodo de la década de 2010-2019. Este dataset fue creado por CaixaBank Tech.

Debido a que también trabajaremos con datos geoespaciales, necesitaremos las coordenadas de todas las ciudades, pues en nuestro dataset las ciuades extranjeras, no presentan ni código postal ni coordenadas, estos datos los obtuvimos de la siguiente url:  
https://download.geonames.org

El análisis se llevó a cabo utilizando JupyterLab, ejecutado en un contenedor Docker. Los datos empleados en el estudio se almacenaron y procesaron a partir de la ruta de trabajo indicada en esta celda de código:

In [1]:
path = "/home/jovyan/work"
!ls $path/data/raw

cards_data.csv	 mcc_codes.json		    transactions_data.csv
cities15000.txt  train_fraud_labels.json    users_data.csv
countryInfo.txt  train_fraud_labels.ndjson  ZIP_US.txt

Como podemos observar nos encontramos con los 5 archivos orginales alojados en kaggle (`cards_data.csv`, `mcc_codes.json`, `transactions_data.csv`, `users_data.csv`, `train_fraud_labels.json`) y los 3 archivos alojados en geonames (`cities15000.txt`, `countryInfo.txt`, `ZIP_US.txt`). Además observamos un archivo adicional, un archivo `.ndjson` que comentaremos en la sección del procesamiento de datos.

Debido al elevado volumen de datos, se utilizará el formato de archivo `.parquet`, que permite almacenar y procesar grandes conjuntos de datos de manera eficiente. Para el procesamiento, análisis y modelado de los datos se emplearán las siguientes librerías:

- Polars: se utilizará para el procesamiento eficiente de grandes volúmenes de datos mediante su motor de ejecución - lazy, que permite optimizar las operaciones antes de su ejecución.
- Plotly: se empleará para la generación de visualizaciones y gráficos interactivos.
- Sweetviz: para realizar un análisis automatizado descriptivo de nuestras variables en el dataset.
- Pandas: Para trabajar con dataframes en este formato, ya que hay librerías que solo aceptan este formato.
- Scikit-learn: se utilizará para las tareas de preprocesamiento de los datos, selección y evaluación de modelos de machine learning.
- Random Forest, XGBoost y LightGBM: se emplearán como algoritmos de machine learning basados en árboles de decisión para la clasificación de las transacciones.
- TensorFlow: se utilizará para el desarrollo y entrenamiento de modelos de deep learning.

A continuación, en esta celda de código, listamos de forma detallada las librerías utilizadas en este reporte:

In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

In [3]:
import polars as pl
import polars.selectors as cs

import pandas as pd
import numpy as np
import math
from scipy import stats

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from datetime import date, datetime

import gc

import sweetviz as sv

from sklearn.metrics import classification_report, precision_recall_curve, auc, average_precision_score
from sklearn.model_selection import PredefinedSplit, GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.utils import compute_class_weight, class_weight
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
import lightgbm as lgb
import tensorflow as tf
from tensorflow.keras import layers, models, regularizers

import joblib

In [4]:
%%capture
pl.Config.set_tbl_rows(-1)
pl.Config.set_tbl_cols(-1)

os.environ["POLARS_FMT_TABLE_FORMATTING"] = "NOTHING"

import plotly.io as pio
pio.renderers.default = "notebook_connected"

En esta celda de código, listamos las polar expressions que utilizaremos

In [12]:
#Polar expression para etiquetar de froma detallada nuestra columna target
label_expr = (
    pl.when(pl.col("target")).then(pl.lit("Fraudulent"))
    .when(~pl.col("target")).then(pl.lit("Legitimate"))
    .otherwise(pl.lit("Unlabeled"))
)

#Polar expression para filtrar los datos sesgados
unbiased_expr = (
    (
        pl.col("date").is_between(datetime(2010, 1, 1), datetime(2011, 1, 8)) |
        pl.col("date").is_between(datetime(2013, 7, 19), datetime(2014, 4, 8)) |
        pl.col("date").is_between(datetime(2015, 3, 30), datetime(2016, 12, 22))
    ) &
    (pl.col("date") != datetime(2016, 2, 29)) &
    (pl.col("target").is_not_null())
)

# Debemos tener en cuenta que para la sección de ingeniería de características, donde crearemos
# las caracteristicas temporales, un sesgo temporal rompería el comportamiento normal de un cliente 
# al utilizar funciones ventana, por lo que para llevar adecuandamente el diseño de las
# características, ampliaremos el filtro a 7 días antes de lo establecido anteriormente.
unbiased_w7_expr = (
    (
        pl.col("date").is_between(datetime(2010, 1, 1), datetime(2011, 1, 8)) |
        pl.col("date").is_between(datetime(2013, 7, 12), datetime(2014, 4, 8)) |
        pl.col("date").is_between(datetime(2015, 3, 23), datetime(2016, 12, 22))
    ) &
    (pl.col("date") != datetime(2016, 2, 29))
)

Para el desarrollo de las características aplicaremos algunas funciones matemáticas. Nosotros trabajaremos con la distribución de von Mises para la determinación de algunas características temporales, a continuación mostramos las fórmulas para el cálculo de la media periódica (1) y la desviación estándar periódica (2). Para el cálculo de las distancias aplicaremos la fórmula de Haversine (3). 
$$\mu_{vM}(D) = 2 \tan^{-1} \left( \frac{\sum_{t_j \in D} \sin(t_j)}{\left(\sqrt{\left(\sum_{t_j \in D} \cos(t_j)\right)^2 + \left(\sum_{t_j \in D} \sin(t_j)\right)^2} + \sum_{t_j \in D} \cos(t_j)\right)} \right), \tag{1}$$
  
$$\sigma_{vM}(D) = \sqrt{\ln \left( \frac{1}{\left(\frac{1}{N} \sum_{t_j \in D} \sin(t_j)\right)^2 + \left(\frac{1}{N} \sum_{t_j \in D} \cos(t_j)\right)^2} \right)}, \tag{2}$$

$$d = 2R \cdot \text{atan2}\left(\sqrt{\sin^2\left(\frac{\Delta \varphi}{2}\right) + \cos(\varphi_1) \cos(\varphi_2) \sin^2\left(\frac{\Delta \lambda}{2}\right)}, \sqrt{1 - \sin^2\left(\frac{\Delta \varphi}{2}\right) - \cos(\varphi_1) \cos(\varphi_2) \sin^2\left(\frac{\Delta \lambda}{2}\right)}\right). \tag{3}$$

<br>Para trabajar con estas fórmulas, realizar la estadística y algunas verficaciones, definimos algunas funciones a continuación en la siguiente celda.

In [6]:
## En el artículo referenciado se utiliza la arcotangente, por tanto nosotros debemos trabajar con ángulos 
## que oscilen entre - pi y pi. Definimos una función para la normalización
PI = math.pi
def normalize_angle(angle):
    return ((angle + PI) % (2 * PI)) - PI

## Definimos la función de Haversine con arctan2 para evitar problemas derivados de arcsin en distancias cortas
R_EARTH = 6371.0088
def calculate_haversine(lat1, lon1, lat2, lon2):
    dlat = pl.col(lat2) - pl.col(lat1)
    dlon = pl.col(lon2) - pl.col(lon1)
    a = (dlat / 2).sin().pow(2) + pl.col(lat1).cos() * pl.col(lat2).cos() * (dlon / 2).sin().pow(2)
    return 2 * R_EARTH * pl.arctan2(a.sqrt(), (1 - a).sqrt())

# Calculamos los valores críticos utilizando una distribución normal si la muestra, N_sample, es mayor a 30, 
# en caso contrario utilizaremos una distribucion normal por la teoria del limite central
T_DISTRIBUTIONS = {
    90: {n: stats.t.ppf(0.95, df=n-1) for n in range(2, 31)},
    95: {n: stats.t.ppf(0.975, df=n-1) for n in range(2, 31)},
    99: {n: stats.t.ppf(0.995, df=n-1) for n in range(2, 31)}
}
Z_VALUES = {90: 1.645, 95: 1.960, 99: 2.576}
def calculate_Zt_value(N_sample: str, confidence_level: int) -> pl.Expr:
    if confidence_level not in T_DISTRIBUTIONS:
        raise ValueError("confidence_level must be 90, 95 or 99")
    z_val = Z_VALUES[confidence_level]
    t_dist = T_DISTRIBUTIONS[confidence_level]
    expression = pl.when(pl.col(N_sample) >= 31).then(z_val)    
    for n_val, t_val in t_dist.items():
        expression = expression.when(pl.col(N_sample) == n_val).then(t_val)
    return expression.otherwise(0.0)

## Creamos una función que verifique que el número de filas coincida con el número de ids
def check_row_id(lazyframe):    
    check = lazyframe.select(
        pl.len().alias("rows"),
        pl.col("id").n_unique().alias("unique_ids")
    ).collect()
    return check

## Creamos una función que verifique los valores de las columnas númericas de nuestro lazyframe
def calculate_INF_NULL_NAN(lazyframe):    
    numtype_columns = lazyframe.select(cs.numeric()).collect_schema().names()
    analysis = pl.concat(
        [lazyframe.select(
            pl.lit(col).alias("COLUMN"),
            pl.col(col).is_infinite().sum().alias("INF"),
            pl.col(col).is_null().sum().alias("NULL"),
            pl.col(col).is_nan().sum().alias("NAN"),
         )
         for col in numtype_columns 
        ]
    ).collect()    
    with pl.Config(tbl_rows=-1, fmt_str_lengths=100):
        print(analysis)

En esta sección definimos algunas funciones que utilizaremos para evaluar el entrenamiento del modelo

In [41]:
## Funciones para el entrenamiento por machine learning

def create_validation_report(modelo, calibrated_threshold = 0.45):
    val_probs = modelo.predict_proba(X_val)[:, 1]
    calibrated_threshold = calibrated_threshold
    calibrated_preds = val_probs > calibrated_threshold
    print("-------- VALIDATION REPORT --------")
    print(classification_report(y_val, calibrated_preds))    
    precision, recall, thresholds = precision_recall_curve(y_val, val_probs)
    pr_auc = auc(recall, precision)
    ap = average_precision_score(y_val, val_probs)
    print(f"PR-AUC Score: {pr_auc:.4f}")
    print(f"Average Precision (AP) Score: {ap:.4f}")

def create_test_report(modelo, calibrated_threshold = 0.45):
    test_probs = modelo.predict_proba(X_test)[:, 1]
    test_preds = test_probs > calibrated_threshold
    print("----------- TEST REPORT -----------")
    print(classification_report(y_test, test_preds))
    precision, recall, thresholds = precision_recall_curve(y_test, test_probs)
    pr_auc = auc(recall, precision)
    ap = average_precision_score(y_test, test_probs)
    print(f"PR-AUC Score: {pr_auc:.4f}")
    print(f"Average Precision (AP) Score: {ap:.4f}")
    return precision, recall, pr_auc, ap, test_preds

## Funciones para el entrenamiento por deeep learning

def plot_monitoring(history, name):
    df_history = pd.DataFrame(history.history)
    df_history['Epoch'] = df_history.index + 1
    fig_auc = px.line(
        df_history, 
        x='Epoch', 
        y=['pr_auc', 'val_pr_auc'], 
        labels={'value': 'PR-AUC score', 'variable': 'Set'},
        title=f"Monitoring: {name}"
    )
    new_names_auc = {'pr_auc': 'Train', 'val_pr_auc': 'Validation'}
    fig_auc.for_each_trace(lambda t: t.update(name = new_names_auc[t.name]))
    fig_auc.update_traces(line=dict(width=2.5))
    fig_auc.update_layout(
        width=700, height=500, autosize=False,
        template='plotly_white', hovermode='x unified', title_x=0.5
    )
    return fig_auc

def create_test_report_2(modelo, calibrated_threshold = 0.45):
    test_probs = (modelo.predict(X_test)).ravel()
    test_preds = test_probs > calibrated_threshold
    print("----------- TEST REPORT -----------")
    print(classification_report(y_test, test_preds))
    precision, recall, thresholds = precision_recall_curve(y_test, test_probs)
    pr_auc = auc(recall, precision)
    ap = average_precision_score(y_test, test_probs)
    print(f"PR-AUC Score: {pr_auc:.4f}")
    print(f"Average Precision (AP) Score: {ap:.4f}")
    return precision, recall, pr_auc, ap

# Función para graficar la curva Precision-Recall

def plot_PRAUC(precision, recall, pr_auc, ap, algorithm, name, colour):
    PRAUC_df = pl.DataFrame({"Recall": recall, "Precision": precision})
    light_PRAUC_df = PRAUC_df.gather_every(50)
    baseline = float(y_test.sum() / len(y_test))
    fig = px.line(
        light_PRAUC_df, 
        x='Recall', 
        y='Precision',
        title=f'<b>Precision-Recall Curve (PR-AUC): {name}</b>',
        labels={'Recall': '<b>Recall<b>', 'Precision': '<b>Precision<b>'}
    )
    fig.update_traces(
        line=dict(color=colour, width=4),
        name=f'{algorithm} (AUC = {pr_auc:.4f} | AP = {ap:.4f})',
        showlegend=True,
        hovertemplate='<b>Recall:</b> %{x:.4f}<br><b>Precision:</b> %{y:.4f}<extra></extra>'
    )
    fig.add_shape(
        type="line", x0=0, y0=baseline, x1=1, y1=baseline,
        line=dict(color="navy", width=2, dash="dash"),
    )
    fig.add_trace(px.scatter(x=[None], y=[None], labels={'x':'', 'y':''}).data[0])
    fig.data[-1].update(
        name=f'Random Classifier (Prop. = {baseline:.4f})', 
        showlegend=True, mode='lines',
        line=dict(color="navy", width=2, dash="dash")
    )
    fig.update_layout(
        width=700, height=500, title_x=0.5, autosize=False,
        xaxis=dict(range=[0.0, 1.0], gridcolor='rgba(0,0,0,0.1)'),
        yaxis=dict(range=[0.0, 1.05], gridcolor='rgba(0,0,0,0.1)'),
        plot_bgcolor='white',
        legend=dict(x=0.45, y=1.1, bgcolor='rgba(255, 255, 255, 0.8)')
    )
    return fig

# Función para calcular los costes de las predicciones del modelo
def calculate_financial_metrics(predictions_df):
    financial_metrics = (
        predictions_df
        .select(
            # Dinero Rescatado: Fraudes detectados (True Positives)
            Recovered_Amount = pl.when(pl.col("target") & pl.col("prediction")).then(pl.col("amount")).otherwise(0).sum(),
            # Dinero Perdido: Fraudes que el modelo no vio (False Negatives)
            Leaked_Amount = pl.when(pl.col("target") & ~pl.col("prediction")).then(pl.col("amount")).otherwise(0).sum(),
            # Dinero Bloqueado por Falsas Alarmas: (False Positives)
            False_Positive_Cost = pl.when(~pl.col("target") & pl.col("prediction")).then(pl.col("amount")).otherwise(0).sum(),
            # Total de dinero que estaba en riesgo de fraude
            Total_Fraud = pl.when(pl.col("target")).then(pl.col("amount")).otherwise(0).sum()
        )
        .with_columns(
            Recovery_Rate_Pct = pl.col("Recovered_Amount") / pl.col("Total_Fraud") * 100
        )
    )
    return financial_metrics

---

## <span id="results"></span> **3. RESULTADOS**

### <span id="ETL"></span> **3.1. Extracción, Transformación y Carga**

Preparamos la carga del archivo `transactions_data.csv`, en este archivo encontramos la información de las transacciones identificadas por la variable `id`, el cliente que realizó la transación con la variable `client_id`, y con que tarjeta se realizó esta transacción con la variable `card_id`, además tenemos la información temporal del momnento en que se realizó la transacción por fecha y hora en la variable `date`. Tenemos la información del comercio donde se realizó la transacción, información que incluye la identificación de este (`merchant_id`), el tipo de comercio (`mcc`), el código postal del comercio (`zip`),la ciudad (`merchant_city`) y el estado (`merchant_state`). Por último tenemos información de la cuantía de la transacción (`amount`), de la forma de pago (`use_chip`) y si esta generó algún error (`erros`). Antes de cargar el archivo completo, definimos el esquema de las columnas del `lazyframe`, cargaremos el `zip` y `amount` como `String` ya que haremos modificaciones a estas variables, para dejar el código postal como un codigo de 5 números y eliminar el símbolo `$` de las cuantías y poder hacer operaciones con esta variable. Además transformaremos `use_chip` y `errors` como variables categóricas para ahorrar memoria RAM y mejorar las agrupaciones.

In [32]:
transactions_data_schema = {
    "id": pl.Int64,
    "date": pl.String,

    "client_id": pl.Int64,
    "card_id": pl.Int64,
    "amount": pl.String,

    "use_chip": pl.String,
    "merchant_id": pl.Int64, 
    "merchant_city": pl.String,
    "merchant_state": pl.String,
    "zip": pl.String,
    "mcc": pl.Int64,
    "errors": pl.String
}

transactions_categorical = ["use_chip", "errors"]

transactions_data_df = (
    pl.scan_csv(f"{path}/data/raw/transactions_data.csv", schema=transactions_data_schema)
    .with_columns([
        pl.col(transactions_categorical).cast(pl.Categorical),
        pl.col("date").str.to_datetime("%Y-%m-%d %H:%M:%S"),
        pl.col("amount").str.replace(r"\$", "", literal=False).cast(pl.Float64),
        pl.col("zip").str.replace(r"\.0$", "", literal=False).str.pad_start(5, "0")
    ])
)

transactions_data_df.show(5)

id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
i64,datetime[μs],i64,i64,f64,cat,i64,str,str,str,i64,cat
7475327,2010-01-01 00:01:00,1556,2972,-77.0,"""Swipe Transaction""",59935,"""Beulah""","""ND""","""58523""",5499,null
7475328,2010-01-01 00:02:00,561,4575,14.57,"""Swipe Transaction""",67570,"""Bettendorf""","""IA""","""52722""",5311,null
7475329,2010-01-01 00:02:00,1129,102,80.0,"""Swipe Transaction""",27092,"""Vista""","""CA""","""92084""",4829,null
7475331,2010-01-01 00:05:00,430,2860,200.0,"""Swipe Transaction""",27092,"""Crown Point""","""IN""","""46307""",4829,null
7475332,2010-01-01 00:06:00,848,3915,46.41,"""Swipe Transaction""",13051,"""Harwood""","""MD""","""20776""",5813,null

Preparamos la carga del archivo `users_data.csv`, en este archivo encontramos la información de los clientes, identificados por la variable `client_id`. Disponemos de información como el género (`gender`), su edad (`current_age`) actual, su año y mes de nacimiento (`birth_year`, `birth_month`), su edad de retiro (`retirement_age`), dirección (`address`) y coordenadas de esta (`client_latitude`, `client_longitude`), así como información de su puntuación crediticia (`credit_score`), el número de tarjetas (`num_credit_cards`), sus ingresos (`per_capita_income`, `yearly_income`) y adeudos (`total_debt`). Antes de cargar el archivo completo, definimos el esquema de las columnas del `lazyframe`, cargaremos `per_capita_income`, `yearly_income`, `total_debt` como `String` ya que eliminaremos el símbolo `$` de las cuantías y poder hacer operaciones con estas variables. Además transformaremos `gender` como variable categórica para ahorrar memoria RAM y mejorar las agrupaciones.

In [28]:
users_data_schema = {
    "client_id": pl.Int64,
    "current_age": pl.Int64,
    "retirement_age": pl.Int64,
    "birth_year": pl.Int64,
    "birth_month": pl.Int64,

    "gender": pl.String,
    "address": pl.String,

    "client_latitude": pl.Float64,
    "client_longitude": pl.Float64, 

    "per_capita_income": pl.String,
    "yearly_income": pl.String,
    "total_debt": pl.String,

    "credit_score": pl.Int64,
    "num_credit_cards": pl.Int64  
}

dollar_columns = ["per_capita_income", "yearly_income", "total_debt"]

users_data_df = (
    pl.scan_csv(f"{path}/data/raw/users_data.csv", schema=users_data_schema)
    .with_columns([
        pl.col("gender").cast(pl.Categorical),
        pl.col(dollar_columns).str.replace(r"\$", "", literal=False).cast(pl.Float64)
    ])
)

users_data_df.show(5)

client_id,current_age,retirement_age,birth_year,birth_month,gender,address,client_latitude,client_longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
i64,i64,i64,i64,i64,cat,str,f64,f64,f64,f64,f64,i64,i64
825,53,66,1966,11,"""Female""","""462 Rose Lane""",34.15,-117.76,29278.0,59696.0,127613.0,787,5
1746,53,68,1966,12,"""Female""","""3606 Federal Boulevard""",40.76,-73.74,37891.0,77254.0,191349.0,701,5
1718,81,67,1938,11,"""Female""","""766 Third Drive""",34.02,-117.89,22681.0,33483.0,196.0,698,5
708,63,63,1957,1,"""Female""","""3 Madison Street""",40.71,-73.99,163145.0,249925.0,202328.0,722,4
1164,43,70,1976,9,"""Male""","""9620 Valley Stream Drive""",37.76,-122.44,53797.0,109687.0,183855.0,675,1

Procedemos a guardar el archivo `users_data` con sus transformaciones, ya que más adelante trabajaremos con él.

In [6]:
users_data_df.sink_parquet(f"{path}/data/bronze/Polars/users_data.parquet")

<br>Preparamos la carga del archivo `cards_data.csv`, en este archivo encontramos la información de los clientes, identificados por la variable `card_id`. Disponemos de información como el tipo de tarjeta (`card_type`) o la compañía (`card_brand`), así como su número (`card_number`), código de verificación (`cvv`), fecha de expiración (`expires`), si tiene o no chip (`has_chip`), número de tarjetas asociadas (`num_cards_issued`), así como su límite crediticio (`credit_limit`), fecah de apertura (`acct_open_date`), último año en que se cambió el pin (`year_pin_last_changed`) o si está en la *dark web* (`card_on_dark_we`). Antes de cargar el archivo completo, definimos el esquema de las columnas del `lazyframe`, cargaremos `credit_limit` como `String` ya que eliminaremos el símbolo `$` de las cuantías y poder hacer operaciones con estas variable. Además transformaremos `card_brand` y `card_type` como variables categóricas y `has_chip` y `card_on_dark_web` como variables booleanas.

In [31]:
cards_data_schema = {
    "card_id": pl.Int64,
    "client_id": pl.Int64,
    "card_brand": pl.String,
    "card_type": pl.String,
    "card_number": pl.Int64,

    "expires": pl.String,
    "cvv": pl.Int64,
    "has_chip": pl.String,
    "num_cards_issued": pl.Int64,

    "credit_limit": pl.String,

    "acct_open_date": pl.String, 
    "year_pin_last_changed": pl.Int64,
    "card_on_dark_web": pl.String           
}

cards_categorical = ["card_brand", "card_type"]
cards_booleans = ["has_chip", "card_on_dark_web"]

cards_data_df = (
    pl.scan_csv(f"{path}/data/raw/cards_data.csv", schema=cards_data_schema)
    .with_columns([
        pl.col(cards_categorical).cast(pl.Categorical),
        pl.col(cards_booleans).str.strip_chars().str.to_uppercase() == "YES",
        pl.col("credit_limit").str.replace(r"\$", "", literal=False).cast(pl.Float64),
        (pl.lit("01/") + pl.col("expires")).str.to_date("%d/%m/%Y").alias("expires"),
        (pl.lit("01/") + pl.col("acct_open_date")).str.to_date("%d/%m/%Y").alias("acct_open_date")
    ])
)

cards_data_df.show(5)

card_id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
i64,i64,cat,cat,i64,date,i64,bool,i64,f64,date,i64,bool
4524,825,"""Visa""","""Debit""",4344676511950444,2022-12-01,623,true,2,24295.0,2002-09-01,2008,false
2731,825,"""Visa""","""Debit""",4956965974959986,2020-12-01,393,true,2,21968.0,2014-04-01,2014,false
3701,825,"""Visa""","""Debit""",4582313478255491,2024-02-01,719,true,2,46414.0,2003-07-01,2004,false
42,825,"""Visa""","""Credit""",4879494103069057,2024-08-01,693,false,1,12400.0,2003-01-01,2012,false
4659,825,"""Mastercard""","""Debit (Prepaid)""",5722874738736011,2009-03-01,75,true,1,28.0,2008-09-01,2009,false

Hacemos una inspección del archivo `mcc_codes.json` para verificar su estructura. Como podemos observar este tiene una estructura plana *key-value*.

In [7]:
with open(f"{path}/data/raw/mcc_codes.json", "r", encoding="utf-8") as f:
    fragmento = f.read(400)
    print(fragmento)

{
    "5812": "Eating Places and Restaurants",
    "5541": "Service Stations",
    "7996": "Amusement Parks, Carnivals, Circuses",
    "5411": "Grocery Stores, Supermarkets",
    "4784": "Tolls and Bridge Fees",
    "4900": "Utilities - Electric, Gas, Water, Sanitary",
    "5942": "Book Stores",
    "5814": "Fast Food Restaurants",
    "4829": "Money Transfer",
    "5311": "Department Stores",

Preparamos la carga de nuestro archivo `mcc_codes.json`. Como observamos este archivo tiene el código del tipo comercio (`mcc`) y la descripción del tipo de comercio asociado (`mcc_description`).

In [33]:
mcc_codes_df = (
    pl.read_json(f"{path}/data/raw/mcc_codes.json")
    .lazy()
    .unpivot(variable_name="mcc", value_name="mcc_description")
    .with_columns(pl.col("mcc").cast(pl.Int64))
)

mcc_codes_df.show(5)

mcc,mcc_description
i64,str
3722,"""Passenger Railways"""
3000,"""Steelworks"""
5947,"""Gift, Card, Novelty Stores"""
4111,"""Local and Suburban Commuter Tr…"
5311,"""Department Stores"""

De manera idéntica al caso de arriba hacemos una inspección del archivo `train_fraud_labels.json` para verificar su estructura. Como podemos observar este envuelve todos los datos dentro de una llave principal llamada `target`.

In [17]:
with open(f"{path}/data/raw/train_fraud_labels.json", "r", encoding="utf-8") as f:
    fragmento = f.read(400)
    print(fragmento)

{"target": {"10649266": "No", "23410063": "No", "9316588": "No", "12478022": "No", "9558530": "No", "12532830": "No", "19526714": "No", "9906964": "No", "13224888": "No", "13749094": "No", "12303776": "No", "19480376": "No", "11716050": "No", "20025400": "No", "7661688": "No", "16662807": "No", "21419778": "No", "18011186": "No", "23289598": "No", "11644547": "No", "23235120": "No", "19748218": "N

Para optimizar la lectura y el procesamiento en paralelo dentro de Polars, procedimos a transformar el archivo `.json` original a un formato `.ndjson` mediante la ejecución del siguiente comando en la terminal:  
 ```jq -c '.target | to_entries[] | {id: .key, target: .value}' train_fraud_labels.json > train_fraud_labels.ndjson ```

Procedemos a verificar la estructura del archivo generado en `.ndjson`.

In [30]:
with open(f"{path}/data/raw/train_fraud_labels.ndjson", "r", encoding="utf-8") as f:
    fragmento = f.read(400)
    print(fragmento)

{"id":"10649266","target":"No"}
{"id":"23410063","target":"No"}
{"id":"9316588","target":"No"}
{"id":"12478022","target":"No"}
{"id":"9558530","target":"No"}
{"id":"12532830","target":"No"}
{"id":"19526714","target":"No"}
{"id":"9906964","target":"No"}
{"id":"13224888","target":"No"}
{"id":"13749094","target":"No"}
{"id":"12303776","target":"No"}
{"id":"19480376","target":"No"}
{"id":"11716050","t

Preparamos la carga de nuestro archivo `train_fraud_labels.ndjson`. Como observamos este archivo tiene información sobre el código de identifiación de la transacción (`id`) y si esta fue registrada como fradudulenta o legítima (`target`).

In [27]:
train_fraud_labels_df = (
    pl.scan_ndjson(f"{path}/data/raw/train_fraud_labels.ndjson")
    .with_columns(
        pl.col("target").str.strip_chars().str.to_uppercase().eq("YES").alias("target"),
        pl.col("id").cast(pl.Int64).alias("id")
    )
)

train_fraud_labels_df.show(5)

id,target
i64,bool
10649266,false
23410063,false
9316588,false
12478022,false
9558530,false

Como mencionamos anteriormente trabajaremos con información geoespacial, para completar la información restante. La información de las coordenadas de los códigos postales de USA está alojada en el archivo `ZIP_US.txt` que descargaremos:  
https://download.geonames.org/export/zip/  

Debido a la presencia de duplicados, ordenaremos en función de la precisión de las coordenadas (`accuracy`) para seleccionar una sola pareja de coordenadas por código postal con `.first()`,  la de mayor precisión.

In [43]:
ZIP_columns = [
    "country_code", "zip", "place_name", "admin_name1", 
    "admin_code1", "admin_name2", "admin_code2", "admin_name3",
    "admin_code3", "merchant_latitude", "merchant_longitude", "accuracy"
]

ZIP_schema = {
    "zip": pl.String,
    "merchant_latitude": pl.Float64,
    "merchant_longitude": pl.Float64
}

ZIP_US_df = (
    pl.scan_csv(f"{path}/data/raw/ZIP_US.txt", separator="\t", has_header = False,
                new_columns = ZIP_columns, schema_overrides= ZIP_schema,
    )
    .select(["zip", "merchant_latitude", "merchant_longitude", "accuracy"])
    .sort("accuracy", descending=True)
    .group_by("zip")
    .agg([
        pl.col("merchant_latitude").first(),
        pl.col("merchant_longitude").first()
    ])
)

ZIP_US_df.show(5)

zip,merchant_latitude,merchant_longitude
str,f64,f64
"""32333""",30.6092,-84.4143
"""32426""",30.9563,-85.3766
"""30439""",32.401,-82.0607
"""32190""",29.3201,-81.5279
"""34690""",28.1913,-82.7279

Dado que las ciudades extranjeras no presentan código postal en nuestro dataset, obtendremos sus coordenadas a partir del archivo alojado en el siguiente enlace (`cities15000.txt`):  
https://download.geonames.org/export/dump/

Además también descargaremos de este sitio el código por país (`countryInfo.txt`), necesario para los `.join`. Debido a la presencia de ciudades con el mismo nomnbre, ordenaremos en función del tamaño de la población de cada ciudad, y seleccionaremos aquellas con mayor población.

In [40]:
cities_columns = [
    "geonameid", "name", "merchant_city", "alternatenames", 
    "city_latitude", "city_longitude", "feature class", "feature code", 
    "country_code", "cc2", "admin1 code", "admin2 code", 
    "admin3 code", "admin4 code", "population", "elevation", 
    "dem", "timezone", "modification date"
]

cities_schema = {
    "merchant_city": pl.String,
    "city_latitude": pl.Float64,
    "city_longitude": pl.Float64,
    "country_code": pl.String
}

cities_df = (
    pl.scan_csv(f"{path}/data/raw/cities15000.txt", separator="\t", has_header = False,
                new_columns = cities_columns, schema_overrides= ZIP_schema,
    )
    .select(["merchant_city", "city_latitude", "city_longitude", "country_code", "population"])
)

countries_df = (
    pl.scan_csv(f"{path}/data/raw/countryInfo.txt", separator="\t")
    .select("ISO", "Country")
    .rename({"ISO": "country_code", "Country": "merchant_state"})
)

city_country_df = (
    countries_df
    .join(cities_df, on="country_code", how="left")
    .sort("population", descending=True)
    .group_by(["merchant_state", "merchant_city"])
    .agg(
        pl.col("city_latitude").first(),
        pl.col("city_longitude").first(),
    )
)

city_country_df.show(5)

merchant_state,merchant_city,city_latitude,city_longitude
str,str,f64,f64
"""Brazil""","""Fortaleza""",-3.71722,-38.54306
"""China""","""Dezhou""",37.44661,116.36706
"""Ivory Coast""","""Abobo""",5.41613,-4.0159
"""Canada""","""Mississauga""",43.5789,-79.6583
"""Pakistan""","""Chunian""",30.96621,73.97908

Por último procedemos a preparar el plan de ejecución de los `.join` para unificar toda la información en un único archivo `.parquet`.

In [44]:
complete_fraud_data_df = (
    transactions_data_df
        .join(ZIP_US_df, on="zip", how="left")
        .join(city_country_df, on=["merchant_state", "merchant_city"], how="left")
        .with_columns(
            merchant_latitude = pl.coalesce(["merchant_latitude", "city_latitude"]),
            merchant_longitude = pl.coalesce(["merchant_longitude", "city_longitude"])
        )
        .drop("city_latitude", "city_longitude")
        .join(mcc_codes_df, on="mcc", how="left")
        .join(users_data_df, on="client_id", how="left")
        .join(cards_data_df, on=["client_id", "card_id"], how="left")
        .join(train_fraud_labels_df, on="id", how="left")        
)

complete_fraud_data_df.show(5)

id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors,merchant_latitude,merchant_longitude,mcc_description,current_age,retirement_age,birth_year,birth_month,gender,address,client_latitude,client_longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web,target
i64,datetime[μs],i64,i64,f64,cat,i64,str,str,str,i64,cat,f64,f64,str,i64,i64,i64,i64,cat,str,f64,f64,f64,f64,f64,i64,i64,cat,cat,i64,date,i64,bool,i64,f64,date,i64,bool,bool
7475329,2010-01-01 00:02:00,1129,102,80.0,"""Swipe Transaction""",27092,"""Vista""","""CA""","""92084""",4829,null,33.2131,-117.2243,"""Money Transfer""",49,65,1970,4,"""Male""","""2379 Forest Lane""",33.18,-117.29,16894.0,34449.0,36540.0,686,3,"""Mastercard""","""Debit""",5874992802287595,2020-05-01,256,true,1,14802.0,2006-01-01,2008,false,false
7475332,2010-01-01 00:06:00,848,3915,46.41,"""Swipe Transaction""",13051,"""Harwood""","""MD""","""20776""",5813,null,38.8582,-76.6145,"""Drinking Places (Alcoholic Bev…",51,69,1968,5,"""Male""","""166 River Drive""",38.86,-76.6,33529.0,68362.0,96182.0,711,2,"""Visa""","""Debit""",4354185735186651,2020-01-01,120,true,1,19113.0,2009-07-01,2014,false,false
7475328,2010-01-01 00:02:00,561,4575,14.57,"""Swipe Transaction""",67570,"""Bettendorf""","""IA""","""52722""",5311,null,41.5509,-90.4942,"""Department Stores""",48,67,1971,6,"""Male""","""604 Pine Street""",40.8,-91.12,18076.0,36853.0,112139.0,834,5,"""Mastercard""","""Credit""",5175842699412235,2024-12-01,438,true,1,9100.0,2005-09-01,2015,false,false
7475327,2010-01-01 00:01:00,1556,2972,-77.0,"""Swipe Transaction""",59935,"""Beulah""","""ND""","""58523""",5499,null,47.2707,-101.8075,"""Miscellaneous Food Stores""",30,67,1989,7,"""Female""","""594 Mountain View Street""",46.8,-100.76,23679.0,48277.0,110153.0,740,4,"""Mastercard""","""Debit (Prepaid)""",5497590243197280,2022-07-01,306,true,2,55.0,2008-05-01,2008,false,false
7475331,2010-01-01 00:05:00,430,2860,200.0,"""Swipe Transaction""",27092,"""Crown Point""","""IN""","""46307""",4829,null,41.4236,-87.3556,"""Money Transfer""",52,67,1967,5,"""Female""","""903 Hill Boulevard""",41.42,-87.35,26168.0,53350.0,128676.0,685,5,"""Mastercard""","""Debit""",5346827663529174,2024-10-01,54,false,2,37634.0,2004-05-01,2006,false,null

Verificamos que tras los `.join` tengamos el mismo número de filas que de *ids*.

In [45]:
complete_fraud_data_df.select(
    pl.len().alias("rows"),
    pl.col("id").n_unique().alias("unique_ids")
).collect()

shape: (1, 2)
 rows      unique_ids
 ---       ---
 u32       u32
 13305915  13305915

Por último, para guardar el archivo y ejecutar el plan de procesamiento utilizamos `.sink_parquet()`, procedimiento que realiza una operación de escritura optimizada de datos en transmisión.

In [3]:
complete_fraud_data_df.sink_parquet(f"{path}/data/bronze/Polars/complete_fraud_data.parquet")

del mcc_codes_df
gc.collect()

---

### <span id="eda-demografia"></span> **3.2. Análisis Exploratorio de Datos Demográficos y de Comercio**

En esta sección haremos un primer análisis de las variables, y estudiaremos la demografía de los clientes. Escaneamos nuestro archivo `complete_fraud_data.parquet` para inicializarlo como un `LazyFrame`, como pondemos observar el tipo de variable de las columnas es el esperado.

In [9]:
fraud_data_df = pl.scan_parquet(f"{path}/data/bronze/Polars/complete_fraud_data.parquet")
fraud_data_df.show(5)

id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors,merchant_latitude,merchant_longitude,mcc_description,current_age,retirement_age,birth_year,birth_month,gender,address,client_latitude,client_longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web,target
i64,datetime[μs],i64,i64,f64,cat,i64,str,str,str,i64,cat,f64,f64,str,i64,i64,i64,i64,cat,str,f64,f64,f64,f64,f64,i64,i64,cat,cat,i64,date,i64,bool,i64,f64,date,i64,bool,bool
7475459,2010-01-01 03:08:00,169,3256,11.18,"""Swipe Transaction""",2205,"""Sumter""","""SC""","""29153""",5813,null,33.9446,-80.3206,"""Drinking Places (Alcoholic Bev…",85,71,1934,5,"""Male""","""2 11th Avenue""",33.94,-80.39,14224.0,30451.0,93.0,686,4,"""Mastercard""","""Debit""",5995053751840192,2024-02-01,267,true,1,12591.0,2003-06-01,2010,false,false
7475921,2010-01-01 07:33:00,1296,67,24.63,"""Online Transaction""",39021,"""ONLINE""",null,null,4784,null,null,null,"""Tolls and Bridge Fees""",60,64,1959,11,"""Female""","""2468 Spruce Drive""",28.7,-81.34,22896.0,46683.0,93126.0,788,5,"""Mastercard""","""Credit""",5181226307106931,2024-11-01,820,true,2,15500.0,2005-01-01,2014,false,false
7475754,2010-01-01 06:53:00,17,4962,89.46,"""Swipe Transaction""",50783,"""Banner Elk""","""NC""","""28604""",5411,null,36.1705,-81.8412,"""Grocery Stores, Supermarkets""",76,65,1943,7,"""Male""","""2012 Forest Avenue""",35.73,-81.32,17850.0,21867.0,21103.0,759,2,"""Amex""","""Credit""",396239738941168,2024-10-01,814,true,1,2800.0,2002-10-01,2011,false,null
7475627,2010-01-01 06:16:00,1678,4680,6.58,"""Swipe Transaction""",17493,"""Wethersfield""","""CT""","""06109""",5812,null,41.7013,-72.6763,"""Eating Places and Restaurants""",36,65,1983,3,"""Male""","""296 Pine Boulevard""",41.7,-72.67,28557.0,58225.0,101148.0,685,3,"""Mastercard""","""Debit""",5127936739014860,2023-01-01,896,true,1,30424.0,2008-09-01,2011,false,false
7475344,2010-01-01 00:32:00,646,2093,73.79,"""Swipe Transaction""",1636,"""Erie""","""PA""","""16511""",7538,null,42.1553,-80.0177,"""Automotive Service Shops""",38,65,1981,12,"""Female""","""354 Federal Street""",41.47,-81.67,21402.0,43634.0,73037.0,786,3,"""Mastercard""","""Credit""",5417194878972795,2021-04-01,638,true,2,14500.0,2005-03-01,2019,false,false

A continuación verificamos la presencia de valores nulos en nuestro arrchivo con `.count()`, como podemos observar hay columnas que presentan conteos inferiores a los de la columna `id`. Por ejemplo, encontramos 211.393 registros de errores en la transacción para un total de 13.305.915 de transacciones.
Por otro lado encontramos que no todas las transacciones han sido auditadas, registrándose 8.914.963 conteos para `target`.

Encontramos también la aparición de valores nulos para la información geoespacial, lo cual atribuimos a la presencia de transacciones online, las cuales no aportan coordenadas de comercio.

In [51]:
fraud_data_df.collect().select(pl.all().count())

shape: (1, 40)
 id   dat  cli  car  amo  use  mer  mer  mer  zip  mcc  err  mer  mer  mcc  cur  ret  bir  bir  gen  add  cli  cli  per  yea  tot  cre  num  car  car  car  exp  cvv  has  num  cre  acc  yea  car  tar
 ---  e    ent  d_i  unt  _ch  cha  cha  cha  ---  ---  ors  cha  cha  _de  ren  ire  th_  th_  der  res  ent  ent  _ca  rly  al_  dit  _cr  d_b  d_t  d_n  ire  ---  _ch  _ca  dit  t_o  r_p  d_o  get
 u32  ---  _id  d    ---  ip   nt_  nt_  nt_  u32  u32  ---  nt_  nt_  scr  t_a  men  yea  mon  ---  s    _la  _lo  pit  _in  deb  _sc  edi  ran  ype  umb  s    u32  ip   rds  _li  pen  in_  n_d  ---
      u32  ---  ---  u32  ---  id   cit  sta            u32  lat  lon  ipt  ge   t_a  r    th   u32  ---  tit  ngi  a_i  com  t    ore  t_c  d    ---  er   ---       ---  _is  mit  _da  las  ark  u32
           u32  u32       u32  ---  y    te                  itu  git  ion  ---  ge   ---  ---       u32  ude  tud  nco  e    ---  ---  ard  ---  u32  ---  u32       u32  sue  ---  te   t_c  _we
                               u32  ---  ---                 de   ude  ---  u32  ---  u32  u32            ---  e    me   ---  u32  u32  s    u32       u32                 d    u32  ---  han  b
                                    u32  u32                 ---  ---  u32       u32                      u32  ---  ---  u32            ---                                ---       u32  ged  ---
                                                             u32  u32                                          u32  u32                 u32                                u32            ---  u32
                                                                                                                                                                                          u32
 133  133  133  133  133  133  133  133  117  116  133  211  117  117  133  133  133  133  133  133  133  133  133  133  133  133  133  133  133  133  133  133  133  133  133  133  133  133  133  891
 059  059  059  059  059  059  059  059  422  532  059  393  283  283  059  059  059  059  059  059  059  059  059  059  059  059  059  059  059  059  059  059  059  059  059  059  059  059  059  496
 15   15   15   15   15   15   15   15   15   09   15        28   28   15   15   15   15   15   15   15   15   15   15   15   15   15   15   15   15   15   15   15   15   15   15   15   15   15   3

Como observamos en la siguiente tabla, los valores de las transacciones onlines para `merchant_state`, `merchant_latitude`, `merchant_longitude` y `zip` es `null`. Mientras que los valores para `merchant_city` son "ONLINE". También observamos que hay más conteos para las coordenadas del comercio que para los códigos postales de Estados Unidos, lo cual también es lógico ya que las coordenadas las obtuvimos no solo de los códigos postales sino también de la información de las ciudades extranjeras.

In [52]:
fraud_data_df.filter(pl.col("use_chip") == "Online Transaction").show(5)

id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors,merchant_latitude,merchant_longitude,mcc_description,current_age,retirement_age,birth_year,birth_month,gender,address,client_latitude,client_longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web,target
i64,datetime[μs],i64,i64,f64,cat,i64,str,str,str,i64,cat,f64,f64,str,i64,i64,i64,i64,cat,str,f64,f64,f64,f64,f64,i64,i64,cat,cat,i64,date,i64,bool,i64,f64,date,i64,bool,bool
7475921,2010-01-01 07:33:00,1296,67,24.63,"""Online Transaction""",39021,"""ONLINE""",null,null,4784,null,null,null,"""Tolls and Bridge Fees""",60,64,1959,11,"""Female""","""2468 Spruce Drive""",28.7,-81.34,22896.0,46683.0,93126.0,788,5,"""Mastercard""","""Credit""",5181226307106931,2024-11-01,820,true,2,15500.0,2005-01-01,2014,false,false
7476016,2010-01-01 07:54:00,1558,3750,63.02,"""Online Transaction""",39021,"""ONLINE""",null,null,4784,null,null,null,"""Tolls and Bridge Fees""",47,65,1973,2,"""Female""","""675 Little Creek Drive""",40.64,-73.94,25172.0,51330.0,106161.0,597,2,"""Visa""","""Debit""",4836616684752344,2021-07-01,399,true,2,10182.0,2005-07-01,2011,false,false
7475737,2010-01-01 06:49:00,119,5980,178.53,"""Online Transaction""",73186,"""ONLINE""",null,null,4814,null,null,null,"""Telecommunication Services""",44,67,1975,9,"""Female""","""60 Little Creek Avenue""",36.16,-115.28,27761.0,56605.0,87970.0,624,3,"""Visa""","""Credit""",4282551690422601,2019-03-01,688,true,1,2500.0,2009-12-01,2009,false,null
7475491,2010-01-01 04:17:00,356,3251,7.71,"""Online Transaction""",50404,"""ONLINE""",null,null,4784,null,null,null,"""Tolls and Bridge Fees""",50,73,1969,10,"""Female""","""24 River Avenue""",27.19,-80.24,20315.0,41420.0,0.0,691,5,"""Mastercard""","""Debit""",5812893386791853,2012-07-01,51,true,2,14100.0,2003-06-01,2010,false,false
7475983,2010-01-01 07:47:00,1176,5003,31.28,"""Online Transaction""",39021,"""ONLINE""",null,null,4784,null,null,null,"""Tolls and Bridge Fees""",39,64,1980,10,"""Male""","""2411 Hillside Lane""",37.94,-87.4,28126.0,57348.0,119230.0,527,3,"""Mastercard""","""Debit""",5274657041301974,2020-04-01,436,true,2,47833.0,2004-10-01,2010,false,false

A continuación analizamos la cardinalidad de nuestras columnas y las ordenamos de forma descendente. Lo primero que observamos es que la columna `date` presenta una cardinalidad inferior a la columna `id`, indicándonos que hay información temporal idéntica para diferentes transacciones. Por otro lado observamos que la columna `card_on_dark_web` presenta cardinalidad 1, por lo que descartaremos esta columna ya que no aporta información útil para el modelado. Por otro lado `card_id` y `card_number` presentan la misma cardinalidad, igual que `address` y `client_id`, por último observamos que `cvv` presenta un valor 983, cercano a 999.

In [74]:
fraud_data_df.select(pl.all().n_unique()).collect().unpivot().sort("value", descending=True)

shape: (40, 2)
┌───────────────────────┬──────────┐
│ variable              ┆ value    │
│ ---                   ┆ ---      │
│ str                   ┆ u32      │
╞═══════════════════════╪══════════╡
│ id                    ┆ 13305915 │
│ date                  ┆ 4136496  │
│ amount                ┆ 81160    │
│ merchant_id           ┆ 74831    │
│ zip                   ┆ 25257    │
│ merchant_longitude    ┆ 23888    │
│ merchant_latitude     ┆ 22891    │
│ merchant_city         ┆ 12492    │
│ card_id               ┆ 4071     │
│ card_number           ┆ 4071     │
│ credit_limit          ┆ 2603     │
│ client_id             ┆ 1219     │
│ address               ┆ 1219     │
│ yearly_income         ┆ 1201     │
│ total_debt            ┆ 1150     │
│ per_capita_income     ┆ 1120     │
│ cvv                   ┆ 983      │
│ client_longitude      ┆ 859      │
│ client_latitude       ┆ 740      │
│ acct_open_date        ┆ 295      │
│ credit_score          ┆ 281      │
│ merchant_state        ┆ 200      │
│ expires               ┆ 180      │
│ mcc                   ┆ 109      │
│ mcc_description       ┆ 108      │
│ current_age           ┆ 74       │
│ birth_year            ┆ 74       │
│ retirement_age        ┆ 27       │
│ errors                ┆ 23       │
│ year_pin_last_changed ┆ 19       │
│ birth_month           ┆ 12       │
│ num_credit_cards      ┆ 9        │
│ card_brand            ┆ 4        │
│ use_chip              ┆ 3        │
│ card_type             ┆ 3        │
│ num_cards_issued      ┆ 3        │
│ target                ┆ 3        │
│ gender                ┆ 2        │
│ has_chip              ┆ 2        │
│ card_on_dark_web      ┆ 1        │
└───────────────────────┴──────────┘

A continuación seleccionaremos una lista de columnas para analizar su cardinalidad, distribución y calidad, esto lo llevaremos a cabo de forma automatizada con la herramienta sweetviz. Para este análisis tomaremos una muestra de los datos, para que `sweetviz` no colapse, y trabajaremos con dataframes de `pandas`, ya que `sweetviz` trabaja en este formato. Los resultados de este analisis han sido adjuntados en el archivo `Anexo.html`.

In [42]:
EDA_columns = ["amount", "use_chip", "errors", "mcc_description", "target",
    "year_pin_last_changed", "credit_limit", "card_brand", "card_type",
    "current_age", "gender", "per_capita_income", "yearly_income", 
    "total_debt", "credit_score", "num_credit_cards"
]

true_data_pd = (
    fraud_data_df
    .filter(pl.col("target"))
    .select(EDA_columns)
    .with_columns(target = pl.lit(1).cast(pl.Int8))
    .collect()
    .to_pandas()

)

false_data_pd = (
    fraud_data_df
    .filter(~pl.col("target"))
    .select(EDA_columns)
    .collect()
    .sample(fraction=0.01, with_replacement=False, seed=777)
    .with_columns(target = pl.lit(0).cast(pl.Int8))
    .to_pandas()
)

sample_data_pd = pd.concat([false_data_pd, true_data_pd], ignore_index=True)
del true_data_pd, false_data_pd
gc.collect()
sample_data_pd = sample_data_pd.sample(frac=1, random_state=42).reset_index(drop=True)
sample_data_pd.head(5)

,amount,use_chip,errors,mcc_description,target,year_pin_last_changed,credit_limit,card_brand,card_type,current_age,gender,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,-58.00,Chip Transaction,NaN,Service Stations,0,2016,6600.0,Mastercard,Credit,52,Female,14465.0,29496.0,49681.0,704,5
1,148.10,Chip Transaction,NaN,Department Stores,0,2007,18462.0,Mastercard,Debit,53,Male,26420.0,53872.0,64269.0,691,5
2,1.58,Swipe Transaction,NaN,Miscellaneous Food Stores,0,2010,73.0,Mastercard,Debit (Prepaid),49,Male,15676.0,31957.0,12347.0,771,6
3,43.30,Chip Transaction,NaN,Drug Stores and Pharmacies,0,2014,14600.0,Visa,Credit,42,Female,35905.0,73208.0,115827.0,664,6
4,45.09,Chip Transaction,NaN,Miscellaneous Food Stores,0,2007,7100.0,Visa,Credit,33,Female,13820.0,28181.0,37929.0,682,2

In [4]:
report_ml = sv.analyze(sample_data_pd, target_feat="target")
report_ml.show_html(filepath=f"{path}/reports/Anexo.html", open_browser=False)

del sample_data_pd, report_ml
gc.collect()

En este apartado buscamos identificar los clientes que presentan alguna transacción fraudulenta en su historial

In [9]:
client_fraudlabel_df = (
    fraud_data_df
    .select("client_id", "target")
    .group_by("client_id")
    .agg(
         pl.col("target").any().alias("Fraud")
    )
    .with_columns(
        pl.when(pl.col("Fraud")).then(pl.lit("Fraudulent_Client")).otherwise(pl.lit("Legitimate_Client"))
        .alias("client_label")
    )
)

client_fraudlabel_df.show(5)

client_id,Fraud,client_label
i64,bool,str
528,true,"""Fraudulent_Client"""
928,true,"""Fraudulent_Client"""
184,true,"""Fraudulent_Client"""
849,true,"""Fraudulent_Client"""
1495,true,"""Fraudulent_Client"""

Como podemos observar el número de clientes con alguna transacción fraudulenta en su historial asciende a 1196, mientras que los que no presentan ninguna son 23, para un total de 1219 clientes analziados en nuestro dataset.

In [10]:
(
    client_fraudlabel_df
    .select(
        pl.col("client_label").value_counts(name="Total")
    )
    .unnest("client_label")
    .collect()
)

shape: (2, 2)
 client_label       Total
 ---                ---
 str                u32
 Legitimate_Client  23
 Fraudulent_Client  1196

Para hacer un análisis poblacional de los clientes, cargamos el archivo `users_data.parquet` y agrupamos a nuestros clientes por edad y género. Para su graficación en un gráfico tipo pirámide, en uno de los géneros, convertimos en negativo el número de individuos por estrato.

In [13]:
demographic_df = (
    pl.scan_parquet(f"{path}/data/bronze/Polars/users_data.parquet")
    .select(["current_age", "gender"])
    .group_by("current_age", "gender")
    .len(name="Total")
    .with_columns( 
        pl.when(pl.col("gender") == "Male").then(pl.col("Total") * -1).otherwise(pl.col("Total")).alias("count_pyramid")
    )
    .sort("Total", descending=True)
)

demographic_df.show(5)

current_age,gender,Total,count_pyramid
i64,cat,u32,i64
18,"""Male""",43,-43
18,"""Female""",34,34
30,"""Male""",28,-28
49,"""Female""",27,27
48,"""Male""",26,-26

Además también calculamos la edad a la que nuestros clientes fueron víctimas de su primer fraude. De manera tal que se puedan observar si hay una edad a la que se es más propenso a sufrir un fraude.

In [15]:
demographic_first_fraud_age_df = (
    fraud_data_df
    .filter(pl.col("target")) 
    .group_by("client_id", "gender")
    .agg(
        age_at_first_fraud = pl.col("date").dt.year().min() - pl.col("birth_year").first()
    )
    .select("age_at_first_fraud", "gender")
    .group_by("age_at_first_fraud", "gender")
    .len(name = "Total")
    .with_columns(
        pl.when(pl.col("gender") == "Male")
            .then(pl.col("Total") * -1)
            .otherwise(pl.col("Total"))
            .alias("count_pyramid")
    )
    .sort("Total", descending=True)
)

demographic_first_fraud_age_df.show(5)

age_at_first_fraud,gender,Total,count_pyramid
i64,cat,u32,i64
43,"""Male""",25,-25
36,"""Female""",20,20
40,"""Female""",19,19
51,"""Male""",19,-19
49,"""Female""",19,19

En el siguiente gráfico representamos en el eje vertical los diferentes estratos de edad de nuestros clientes, mientras que en el eje horizontal están representados en el panel de la izquierda el número de clientes hombres con esa edad y en la de derecha el de clientes mujeres. En color gris están representados los valores de de edad actual de los clientes, mientras que en azul la edad a la que fueron por primera vez víctima de fraude los clientes hombre mientras que en rojo los clientes mujer. Como podemos observar en el gráfico, no es común sufrir una operación fraudulenta a edades inferiores a 25 años. Por otro lado, en la tercera edad ls principales víctimas son mujeres y parecen ser una población diana de fraude finaciero.

In [17]:
demo_mem = demographic_df.collect()
males_gen = demo_mem.filter(pl.col("gender") == "Male")
females_gen = demo_mem.filter(pl.col("gender") == "Female")

demo_first_mem = demographic_first_fraud_age_df.collect()
males_frd = demo_first_mem.filter(pl.col("gender") == "Male")
females_frd = demo_first_mem.filter(pl.col("gender") == "Female")

demographic_fig = go.Figure()

demographic_fig.add_trace(go.Bar(
    y=males_gen["current_age"],
    x=males_gen["count_pyramid"],
    name="Male (Current Age)",
    orientation="h",
    marker=dict(color="#B4B4B4", opacity=0.8, line=dict(color="#8C8C8C", width=1)),
    hovertemplate="<b>Age: %{y} years old</b><br>General Males: %{customdata:,}<extra></extra>",
    customdata=males_gen["Total"]
))
demographic_fig.add_trace(go.Bar(
    y=females_gen["current_age"],
    x=females_gen["count_pyramid"],
    name="Female (Current Age)",
    orientation="h",
    marker=dict(color="#B4B4B4", opacity=0.8, line=dict(color="#8C8C8C", width=1)),
    hovertemplate="<b>Age: %{y} years old</b><br>General Females: %{x:,}<extra></extra>"
))

demographic_fig.add_trace(go.Bar(
    y=males_frd["age_at_first_fraud"],
    x=males_frd["count_pyramid"],
    name="Male (Age at First Fraud)",
    orientation="h",
    marker=dict(color="#1F77B4", opacity=0.5, line=dict(color="#0A4678", width=1.5)),
    hovertemplate="<b>Age: %{y} years old</b><br>Fraudulent Males: %{customdata:,}<extra></extra>",
    customdata=males_frd["Total"]
))
demographic_fig.add_trace(go.Bar(
    y=females_frd["age_at_first_fraud"],
    x=females_frd["count_pyramid"],
    name="Female (Age at First Fraud)",
    orientation="h",
    marker=dict(color="#DB4455", opacity=0.5, line=dict(color="#961428", width=1.5)),
    hovertemplate="<b>Age: %{y} years old</b><br>Fraudulent Females: %{x:,}<extra></extra>"
))

max_count = int(max(demo_mem["Total"].max(), demo_first_mem["Total"].max()))
tick_step = max(1, max_count // 4)
tick_vals = list(range(-max_count - tick_step, max_count + tick_step, tick_step))
tick_text = [str(abs(v)) for v in tick_vals]

demographic_fig.update_layout(
    title="<b>Demographic Profile Comparison: Current Age vs. Age at First Fraud Event</b>",
    barmode="overlay",        
    bargap=0.05, height=750, width=950, autosize=False,    
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0),
    xaxis=dict(
        title="Number of Clients / Cases", 
        tickvals=tick_vals, ticktext=tick_text, range=[-max_count * 1.1, max_count * 1.1]
    ),
    yaxis=dict(title="Age (Years)", type="linear", range=[18, 100], dtick=5),
    template="plotly_white"
)

demographic_fig.show()

<br>A continuación calculamos la edad de cada cliente al momento en el que se produce cada transacción fraudulenta, de manera que podamos identificar si hay un sesgo en la edad en función de la actividad transaccional.

In [18]:
demographic_fraud_age_df = (
    fraud_data_df
    .select(["gender", "target", "date", "birth_year"])
    .filter(pl.col("target"))
    .with_columns(
        age_at_transaction = pl.col("date").dt.year() - pl.col("birth_year")
    )
    .group_by(["gender", "age_at_transaction"])
    .len("Total")
    .with_columns(
        Total_pyramid = pl.when(pl.col("gender") == "Male").then(pl.col("Total") * -1).otherwise(pl.col("Total"))
    )
)

demographic_fraud_age_df.show(5)

gender,age_at_transaction,Total,Total_pyramid
cat,i64,u32,i64
"""Male""",33,127,-127
"""Female""",40,172,172
"""Female""",45,168,168
"""Female""",43,208,208
"""Male""",40,162,-162

Al representar estos datos, en el eje vertical la edad a la que se realiza la transacción y en el eje horizontal el número de transacciones fraudulentas realizadas a esa edad, de manera similar al gráfico anterior representamos en azul y a la izquierda el número de transacciones fraudulentas por cliente hombre y a la derecha por cliente mujer. Como podemos observar esta pirámide presenta diferencias con la pirámide de la edad al priemr fraude, esto se debe probablemente a que un cliente cuando es víctima de fraude no lo es solo con una transacción única sino con una ráfaga de transacciones en un lapso de tiempo relativamente corto.

In [19]:
demographic_fraud_age_pd = demographic_fraud_age_df.collect()

demographic_fraud_age_fig = px.bar(
    demographic_fraud_age_pd,
    x="Total_pyramid",
    y="age_at_transaction",
    color="gender",  
    orientation="h",
    color_discrete_map={"Male": "#1F77B4", "Female": "#DB4455"},
    custom_data=["Total"]
)

demographic_fraud_age_fig.update_traces(
    opacity=0.75, marker_line_width=1., marker_line_color="#000000",
    hovertemplate="<b>Age: %{y} years old</b><br>Fraudulent Transactions: %{customdata[0]:,}<extra></extra>"
)

max_count = int(demographic_fraud_age_pd["Total"].max())
tick_step = max(1, max_count // 4)
tick_vals = list(range(-max_count - tick_step, max_count + tick_step, tick_step))
tick_text = [str(abs(v)) for v in tick_vals]

demographic_fraud_age_fig.update_layout(
    title="<b>Total Volume of Fraudulent Transactions by Real Age at Event</b>",
    barmode="overlay", bargap=0.05, 
    height=700, width=950, autosize=False,    
    legend=dict(orientation="h", yanchor="bottom", y=1.0, xanchor="left", x=0.7, title=None),
    xaxis=dict(
        title="Number of Fraudulent Transactions",
        tickvals=tick_vals, ticktext=tick_text, 
        range=[-max_count * 1.6, max_count * 1.6]
    ),
    yaxis=dict(title="Age at Event (Years)", type="linear", range=[18, 100], dtick=5),
    template="plotly_white",
)

demographic_fraud_age_fig.show()

<br>Por otro lado calculamos el número de transacciones que se producen según la edad del cliente al momento de realizar la transacción para normalizar los datos anteriores.

In [20]:
demographic_transaction_age_df = (
    fraud_data_df       
    .filter(pl.col("target").is_not_null())
    .with_columns(
        age_at_event = pl.col("date").dt.year() - pl.col("birth_year")
    )     
    .pivot(
        on="target",  index=["age_at_event", "gender"], 
        values="target", aggregate_function="len", 
        on_columns = [False, True]
    )
    .rename({"false": "Legitimate", "true": "Fraudulent"})
    .with_columns(
        frd_leg_ratio = (pl.col("Fraudulent")/(pl.col("Legitimate") + 1)).round(5)
    )
    .with_columns(
        ratio_pyramid = (
            pl.when(pl.col("gender") == "Male")
                .then(pl.col("frd_leg_ratio") * -1)
                .otherwise(pl.col("frd_leg_ratio"))
        )
    )  
)

demographic_transaction_age_df.show(5)

age_at_event,gender,Legitimate,Fraudulent,frd_leg_ratio,ratio_pyramid
i64,cat,u32,u32,f64,f64
45,"""Female""",120650,168,0.00139,0.00139
25,"""Female""",46896,26,0.00055,0.00055
45,"""Male""",115763,174,0.0015,-0.0015
49,"""Male""",107219,104,0.00097,-0.00097
55,"""Male""",86958,146,0.00168,-0.00168

En el siguiente gráfico se representa el número de transacciones fraudulentas en relación con el número total de transacciones realizdas en función de la edad. Como podemos observar esta tasa crece a partir de la tercera edad. E interesantemente es bastante mayor a la edad de 18 años y principalmente en clientes hombre.

In [21]:
demographic_transaction_age_pd = demographic_transaction_age_df.collect()

demographic_transaction_age_fig = px.bar(
    demographic_transaction_age_pd,
    x="ratio_pyramid",
    y="age_at_event",
    color="gender", 
    orientation="h",
    color_discrete_map={"Male": "#1F77B4", "Female": "#DB4455"},
    custom_data=["Legitimate", "Fraudulent", "frd_leg_ratio"],
)

demographic_transaction_age_fig.update_traces(
    opacity=0.75, marker_line_width=1., marker_line_color="#000000",
    hovertemplate="<b>Age at Event: %{y} years old</b><br>" +
                  "Fraud Ratio: %{customdata[2]:.4f}<br>" +
                  "Fraudulent Transactions: %{customdata[1]:,}<br>" +
                  "Legitimate Transactions: %{customdata[0]:,}<extra></extra>"
)

max_ratio = demographic_transaction_age_pd["frd_leg_ratio"].max()
tick_step = max(0.001, round(max_ratio / 4, 3))

tick_vals = []
val = -max_ratio
while val <= max_ratio:
    tick_vals.append(round(val, 4))
    val += tick_step
tick_text = [str(abs(round(v, 3))) for v in tick_vals]
limite_eje_x = abs(tick_vals[-1])

demographic_transaction_age_fig.update_layout(
    title="<b>Fraud-to-Legitimate Transaction Ratio by Real Age at Event</b>",
    barmode="overlay", bargap=0.05, 
    height=700, width=900, autosize=False,    
    legend=dict(orientation="h", yanchor="bottom", y=1.0, xanchor="left", x=0.7, title=None),
    xaxis=dict(
        title="Fraudulent Transactions per 1 Legitimate Transaction (Ratio)", 
        tickvals=tick_vals, ticktext=tick_text, 
        range=[-limite_eje_x, limite_eje_x]
    ),
    yaxis=dict(title="Age at Event (Years)", type="linear", range=[18, 100], dtick=5),
    template="plotly_white",
)

demographic_transaction_age_fig.show()

<br>A continuación calculamos el riesgo de cada tipo de comercio como diana de fraude. Para ello solo utilizamos las transacciones auditadas, y calculamos el factor de riesgo dividiendo el número de transacciones fradulentas entre el número de transacciones legítimas, para evitar problemas de escala, donde los valores que presentan una tasa entre 0 y 1 sean comparables a los valores mayor a 1, utilizaremos logaritmos, por ejemplo si un comercio presenta una tasa de 0.5 será el doble de segura que una con riesgo 1 riesgo, una tasa de 0.25 será 4 veces más segura que un comercio con tasa 1, es por ello que para escalar y hacer comparables estos valores utilizamos logaritmos, ya que:  
$\log (1/X) = -\log(X)$
Al valor obtenido lo denominaremos Log2RiskFactor

In [23]:
mcc_description_df = (
    fraud_data_df
    .filter(pl.col("target").is_not_null())
    .pivot(
        on="target", index="mcc_description", 
        values="mcc_description", aggregate_function="len",
        on_columns=["false", "true"], 
    )
    .rename({"false": "Legitimate", "true": "Fraudulent"})
    .with_columns(
        mcc_rate = pl.col("Fraudulent")/(pl.col("Legitimate") + 1)
    )
    .with_columns(
        total_leg = pl.col("Legitimate").sum(),
        total_fraud = pl.col("Fraudulent").sum()
    )
    .with_columns(
        fraud_rate = pl.col("total_fraud")/pl.col("total_leg")
    )
    .with_columns(
        mcc_risk_factor = pl.col("mcc_rate")/pl.col("fraud_rate")
    )
    .with_columns(
        Log2_risk_factor = (pl.col("mcc_risk_factor") + 0.00001).log(base=2).round(2)
    )  
    .with_columns(
        mcc_risk_category = (
            pl.when(pl.col("Log2_risk_factor") > 2).then(pl.lit("High Risk"))
                .when(pl.col("Log2_risk_factor") < -2).then(pl.lit("Low Risk"))
                .otherwise(pl.lit("Baseline Risk"))
        )
    ) 
    .drop(["total_leg", "total_fraud", "fraud_rate", "mcc_rate"])
)

mcc_description_df.show(5)

mcc_description,Legitimate,Fraudulent,mcc_risk_factor,Log2_risk_factor,mcc_risk_category
str,u32,u32,f64,f64,str
"""Automotive Service Shops""",320112,13,0.027115,-5.2,"""Low Risk"""
"""Service Stations""",954955,168,0.117463,-3.09,"""Low Risk"""
"""Book Stores""",155740,42,0.180061,-2.47,"""Low Risk"""
"""Discount Stores""",164896,859,3.478201,1.8,"""Baseline Risk"""
"""Chiropractors""",7035,2,0.189792,-2.4,"""Low Risk"""

En el siguiente gráfico representamos los valores obtenidos del Log2RiskFactor de cada comercio. Para discriminar los comercios con alto riesgo utilizamos un umbral superior a 2, representado con color rojo, y para bajo riesgo un umbral inferior a -2, representado con color azul, aquellos valores que fueron considerados neutros están representados en gris. Como podemos observar en el gráfico las compañías de cruceros y tiendas musciales son las que presentan mayor tasa de operaciones fraudulentas, mientras que los talleres automotrices y los clubes recreativos y deportivos son los más seguros.

In [24]:
mcc_description_mem = mcc_description_df.collect()

color_risk = {
    'High Risk': '#d9534f',      
    'Baseline Risk': '#999999',  
    'Low Risk': '#337ab7'      
}

mcc_fig = px.scatter(
    mcc_description_mem,
    x="Legitimate",
    y="Fraudulent",
    color="mcc_risk_category",   
    color_discrete_map=color_risk,    
    hover_name="mcc_description", 
    hover_data=["Legitimate", "Fraudulent", "mcc_risk_factor", "Log2_risk_factor"],
    log_x=True,                   
    log_y=True,                  
    title="<b>Merchant Anomaly Detection and Risk Factor Analysis</b>",
    labels={"mcc_risk_category": "Risk Level", "mcc_risk_factor": "Risk Factor",
           "Log2_risk_factor": "Log2(Risk Factor)"},
    template="plotly_white"   
)


mcc_fig.update_traces(
    marker=dict(
        size=12,
        line=dict(width=1, color='Black'),
        opacity=0.8
    )
)

mcc_fig.update_layout(
    height=400, width=900, autosize=False,
    title_font_size=18, xaxis_title_font_size=12, yaxis_title_font_size=12,
    margin=dict(l=40, r=40, t=60, b=40),
    legend=dict(orientation="h", yanchor="top", y=1.07, xanchor="left", x=0.05)
)

mcc_fig.show()

---
<br>

### <span id="eda-temporal"></span> **3.3. Análisis Exploratorio de Datos Temporales**

A continuación procederemos con el análisis temporal de las transacciones, para facilitar el trabajo extraremos la fecha de la columna `date` en la columna `day`. Además crearemos una expresión en polars para etiquetar las transacciones en función de si fueron legítimas (*Legitimate*), fraudulentas (*Fraudulent*) o no auditadas (*Unlabeled*).

In [133]:
fraud_date_df = (
    fraud_data_df
    .with_columns(
        label = label_expr,
        day = pl.col("date").cast(pl.Date)
    )
    .select("date", "day", "target", "label")
)

Rows = fraud_date_df.select(pl.len()).collect().item()
Columns = len(fraud_date_df.collect_schema().names())
print(f"Rows: {Rows}, Columns: {Columns}")

fraud_date_df.show(5)

Rows: 13305915, Columns: 4

date,day,target,label
datetime[μs],date,bool,str
2010-01-01 03:08:00,2010-01-01,false,"""Legitimate"""
2010-01-01 07:33:00,2010-01-01,false,"""Legitimate"""
2010-01-01 06:53:00,2010-01-01,null,"""Unlabeled"""
2010-01-01 06:16:00,2010-01-01,false,"""Legitimate"""
2010-01-01 00:32:00,2010-01-01,false,"""Legitimate"""

Calculamos el porcentaje de operaciones fraudulentas, legítimas y no auditadas, los valores son los que se muestran ela siguiente tabla:

In [134]:
fraud_perc_df = (
    fraud_date_df
    .group_by("target")
    .agg(
        Total = pl.len(),
        Percentage = pl.len() / Rows * 100
    )
    .with_columns(target = label_expr)
    .collect()
)

fraud_perc_df.show()

target,Total,Percentage
str,u32,f64
"""Legitimate""",8901631,66.899804
"""Unlabeled""",4390952,33.0
"""Fraudulent""",13332,0.100196

Estos valores de los porcentajes los representamos en el siguiente *plot pie* donde de forma más visual podemos observar el amplio número de transacciones no auditadas y el alto desbalance de las transacciones registradas como fraudulentas con respecto al total de transacciones realizadas.

In [135]:
fraud_perc_fig = px.pie(
    fraud_perc_df ,
    values='Total', 
    names='target', 
    title= 'Distribución de Transacciones: Legítimas vs Fraude',
    color='target',
    color_discrete_map={'Legitimate': '#263238', 'Fraudulent': '#FF3333', 'Unlabeled': '#90A4AE'},
    hole=0.3
    )
fraud_perc_fig.update_traces(
    textposition='inside', 
    textinfo='percent+label',
    )
fraud_perc_fig.update_layout(width=650, height=450, title_x=0.5, autosize=False)

fraud_perc_fig.show()

A continuación verificamos cual es la fecha más lejana en que se ha realizado una transacción en nuestros datos y cual es la más reciente. Como comprobamos, esto es tal y como está descrito en kaggle.

In [136]:
val_min = fraud_date_df.select(pl.col("day").min()).collect().item()
val_max = fraud_date_df.select(pl.col("day").max()).collect().item()
print(F"Minimum date: {val_min}\nMaximum date: {val_max}")

Minimum date: 2010-01-01
Maximum date: 2019-10-31

A continuación calculamos el número de transacciones fraudulentas, legítimas y no auditadas por fecha.

In [137]:
transactions_evolution_df = (
    fraud_date_df
    .group_by("day", "target") 
    .len()
    .with_columns(target = label_expr)
    .sort("day")
    .collect()
)
transactions_evolution_df.show(5)

day,target,len
date,str,u32
2010-01-01,"""Fraudulent""",1
2010-01-01,"""Legitimate""",2328
2010-01-01,"""Unlabeled""",1134
2010-01-02,"""Legitimate""",1971
2010-01-02,"""Unlabeled""",1018

Representamos estos datos en el siguiente gráfico, separando cada tipo de transacción en un subplot, como podemos observar nuestros datos están sesgados para los días 29 de Febrero de 2012 y 2016, los cuales son años bisiesto,y apenas cuentan con registro en nuestros datos. Por otro lado observamos que el registro de operaciones fraudulentas presenta uns sesgo en función del tiempo, hay amplios periodos de tiempo donde no se registra ninguna operación fraudulenta.

In [138]:
transactions_evolution_false = transactions_evolution_df.filter(pl.col('target') == 'Legitimate')
transactions_evolution_true = transactions_evolution_df.filter(pl.col('target') == 'Fraudulent')
transactions_evolution_null = transactions_evolution_df.filter(pl.col('target') == 'Unlabeled')

transactions_evolution_plot = go.Figure()

transactions_evolution_plot.add_trace(go.Scatter(
    x=transactions_evolution_false['day'], 
    y=transactions_evolution_false['len'], 
    name='Legitimate',
    line=dict(color='#263238', width=2),
    yaxis='y' 
))

transactions_evolution_plot.add_trace(go.Scatter(
    x=transactions_evolution_null['day'], 
    y=transactions_evolution_null['len'], 
    name='Unlabeled',
    line=dict(color='#90A4AE', width=2),
    yaxis='y2' 
))

transactions_evolution_plot.add_trace(go.Scatter(
    x=transactions_evolution_true['day'], 
    y=transactions_evolution_true['len'], 
    name='Fraudulent',
    line=dict(color='#FF3333', width=2),
    yaxis='y3' 
))

transactions_evolution_plot.update_layout(
    title_text='Transaction Trends over Time by Fraud Label', title_x=0.5, 
    width=900, height=750, autosize = False,
    hovermode='x',
    legend_title_text='', showlegend=False,
    
    yaxis=dict(
        title= dict(text='Legitimate', standoff=10),
        domain=[0.7, 1.0],
        showspikes=True, spikemode='across', spikethickness=1, spikedash='dash', spikecolor="#040404"
    ),
    
    yaxis2=dict(
        title= dict(text='Unlabeled', standoff=10), 
        domain=[0.35, 0.65], 
        showspikes=True, spikemode='across', spikethickness=1, spikedash='dash', spikecolor="#040404"
    ),

    yaxis3=dict(
        title=dict(text='Fraudulent', standoff=10), 
        domain=[0.0, 0.30],
        showspikes=True, spikemode='across', spikethickness=1, spikedash='dash', spikecolor="#040404"
    ),
    
    xaxis=dict(
        title='Fecha',
        tickformat='%b %Y',
        hoverformat='%A, %d %b %Y',
        showspikes=True, spikemode='across', spikethickness=1, spikedash='dash', spikecolor="#040404",
        anchor='y3',      
        side='bottom' 
    )
)

transactions_evolution_plot.show()

<br>Para evitar que estos sesgos puedan alterar nuestro análisis, procederemos a filtrar nuestros datos seleccionando aquellos periodos de tiempo donde el registro de operaciones fraudulentas haya sido exhaustivo, además obviaremos las transacciones no auditadas.

In [139]:
date_fraud_unbiased_df = (
    fraud_date_df
    .filter(unbiased_expr)
    .with_columns(
        hour = pl.col("date").dt.hour(),
        minute = pl.col("date").dt.minute(),
        time_str = pl.col("date").dt.to_string("%H:%M"),
    )
    .with_columns(minutes_of_day = (pl.col("hour").cast(pl.Int32) * 60) + pl.col("minute"))
    .select("target", "day", "time_str", "minutes_of_day")
)

Rows_unbiased = date_fraud_unbiased_df.select(pl.len()).collect().item()
Columns_unbiased = len(date_fraud_unbiased_df.collect_schema().names())

print(f"Rows: {Rows_unbiased}, Columns: {Columns_unbiased}")
date_fraud_unbiased_df.show(5)

Rows: 3121274, Columns: 4

target,day,time_str,minutes_of_day
bool,date,str,i32
false,2010-01-01,"""03:08""",188
false,2010-01-01,"""07:33""",453
false,2010-01-01,"""06:16""",376
false,2010-01-01,"""00:32""",32
false,2010-01-01,"""04:54""",294

A continuación calculamos el número de transacciones fraudulentas, legítimas y no auditadas por fecha, tras el filtro de sesgo.

In [140]:
fraud_unbiased_perc_df = (
    date_fraud_unbiased_df
    .group_by("target")
    .agg(
        Total = pl.len(),
        Percentage = pl.len() / Rows_unbiased * 100
    )
    .with_columns(target = label_expr)
    .collect()
)

fraud_unbiased_perc_df.show()

target,Total,Percentage
str,u32,f64
"""Legitimate""",3112100,99.706082
"""Fraudulent""",9174,0.293918

Estos valores de los porcentajes los representamos en el siguiente *plot pie* donde de forma más visual podemos observar que se sigue manteniendo el alto desbalance de las transacciones registradas como fraudulentas con respecto al total de transacciones realizadas.

In [141]:
fraud_unbiased_perc_fig = px.pie(
    fraud_unbiased_perc_df,
    values='Total', 
    names='target', 
    title= 'Transaction Distribution: Legitimate vs Fraud',
    color='target',
    color_discrete_map={'Legitimate': '#263238', 'Fraudulent': '#FF3333'},
    hole=0.3
    )

fraud_unbiased_perc_fig.update_traces(
    textposition='inside', 
    textinfo='percent+label',
    )
fraud_unbiased_perc_fig.update_layout(width=650, height=450, title_x=0.5, autosize=False)

fraud_unbiased_perc_fig.show()

<br>A continuación calculamos el número de transacciones fraudulentas y legítimas por fecha, tras el filtro de sesgo.

In [142]:
transactions_evolution_unbiased_df = (
    date_fraud_unbiased_df
    .group_by("day", "target") 
    .len()
    .with_columns(target = label_expr)
    .sort("day")
    .collect()
)

transactions_evolution_unbiased_df.show(5)

day,target,len
date,str,u32
2010-01-01,"""Legitimate""",2328
2010-01-01,"""Fraudulent""",1
2010-01-02,"""Legitimate""",1971
2010-01-03,"""Fraudulent""",1
2010-01-03,"""Legitimate""",2200

De igual manera a como hicimos anteriormente representamos estos datos en el siguiente gráfico, separando cada tipo de transacción en un subplot, donde podemos observar, que en el general el historiald e transacciones según si es fraudulenta o legítima se mantiene consistente a lo largo del tiempo. Señalar que los períodos en los que hay un *gap* temporal están marcados con línea discontinúa.

In [143]:
transactions_evolution_unbiased_false = transactions_evolution_unbiased_df.filter(pl.col('target') == 'Legitimate')
transactions_evolution_unbiased_true = transactions_evolution_unbiased_df.filter(pl.col('target') == 'Fraudulent')

transactions_evolution_unbiased_plot = go.Figure()

transactions_evolution_unbiased_plot.add_trace(go.Scatter(
    x=transactions_evolution_unbiased_false['day'], 
    y=transactions_evolution_unbiased_false['len'], 
    name='Legitimate',
    line=dict(color='#263238', width=2),
    xaxis='x',
    yaxis='y' 
))

transactions_evolution_unbiased_plot.add_trace(go.Scatter(
    x=transactions_evolution_unbiased_true['day'], 
    y=transactions_evolution_unbiased_true['len'], 
    name='Fraudulent',
    line=dict(color='#FF3333', width=2),
    xaxis='x',
    yaxis='y2' 
))

transactions_evolution_unbiased_plot.update_layout(
    title_text='Transaction Trends over Time by Fraud Label', title_x=0.5,
    width=900, height=750, autosize=False,
    hovermode='x',
    legend_title_text='', showlegend=False,
    
    yaxis=dict(
        title= dict(text='Legitimate', standoff=10),
        domain=[0.52, 1.0],
        showspikes=True, spikemode='across', spikethickness=1, spikedash='dash', spikecolor="#040404"
    ),
    
    yaxis2=dict(
        title= dict(text='Fraudulent', standoff=20),
        domain=[0.0, 0.48],
        showspikes=True, spikemode='across', spikethickness=1, spikedash='dash', spikecolor="#040404"
    ),
    
    xaxis=dict(
        title='Fecha',
        type='date', tickformat='%b %Y', hoverformat='%A, %d %b %Y',
        showspikes=True, spikemode='across', spikethickness=1, spikedash='dash', spikecolor="#040404",
        anchor='y2', side='bottom',
        rangebreaks=[
            dict(bounds=["2011-01-09", "2013-07-18"]), 
            dict(bounds=["2014-04-09", "2015-03-29"])
        ] 
    )
)

for fecha in ["2011-01-09", "2013-07-18", "2014-04-09", "2015-03-29"]:
    transactions_evolution_unbiased_plot.add_shape(
        type="line", xref="x", yref="paper",
        x0=fecha, x1=fecha, y0=0.52, y1=1.0,
        line=dict(color="gray", width=1.5, dash="dash")
)

for fecha in ["2011-01-09", "2013-07-18", "2014-04-09", "2015-03-29"]:
    transactions_evolution_unbiased_plot.add_shape(
        type="line", xref="x", yref="paper",
        x0=fecha, x1=fecha, y0=0.0, y1=0.48,
        line=dict(color="gray", width=1.5, dash="dash")
)

transactions_evolution_unbiased_plot.show()

<br>A continuación agrupamos por mes, y calculamos el promedio de transacciones legitimas y fraudulentas diarias por mes, de manera que estos valores sean comparables ya que no todos los meses tienen el mismo número de días.

In [144]:
monthly_unbiased_df = (
    transactions_evolution_unbiased_df
    .with_columns(
        month_num = pl.col("day").dt.month(), #Extraemos el número de mes para poder ordenar y graficar posteriormente
        month_name= pl.col("day").dt.to_string("%B")
    )
    .group_by("month_num", "month_name", "target")
    .agg(Average_Transactions = pl.col("len").mean())
    .sort("month_num", "target")
)

monthly_unbiased_df.show(5)

month_num,month_name,target,Average_Transactions
i8,str,str,f64
1,"""January""","""Fraudulent""",8.662162
1,"""January""","""Legitimate""",2409.2
2,"""February""","""Fraudulent""",10.171875
2,"""February""","""Legitimate""",2398.529412
3,"""March""","""Fraudulent""",11.296875

Al representar estos datos en un gráfico de barras podemos observar que los meses de Marzo y Diciembre son los meses con mayor promedio de fraudes diarias, mientras que los meses de Enero y Junio son los menos que menor promedio de transacciones fraudulentas presentan. Mientras que apenas hay una variacion proporcional en el número de transacciones legítimas.

In [78]:
monthly_unbiased_plot = px.bar(
    monthly_unbiased_df,
    x="month_name",                  
    y="Average_Transactions",        
    color="target",
    facet_col="target",             
    facet_col_spacing=0.08,       
    barmode="group",
    title="Average Transactions by Month",
    labels={
        "month_name": "Month of the Year", 
        "Average_Transactions": "Average Transactions",
        "target": ""
    },
    color_discrete_map={'Legitimate': "#263238", 'Fraudulent': "#FF3333"},
    category_orders={"target": ["Legitimate", "Fraudulent"]}
)

monthly_unbiased_plot.update_traces(
    hovertemplate="Avg: %{y:,.2f}<extra></extra>"
)

monthly_unbiased_plot.update_yaxes(matches=None, showticklabels=True)
monthly_unbiased_plot.update_xaxes(showticklabels=True, tickangle=-50) 

monthly_unbiased_plot.update_layout(
    title_x=0.5, hovermode="closest", 
    width=900, height=400, autosize=False,
    showlegend=False
)
#Eliminamos el símbolo = de las labels del target.
monthly_unbiased_plot.for_each_annotation(lambda a: a.update(text=a.text.split('=')[-1]))

monthly_unbiased_plot.show()

<br>En esta sección agruparemos por día de la semana, para identificar si hay días en los que es más frecuente el fraude.

In [50]:
weekday_unbiased_df = (
    transactions_evolution_unbiased_df
    .with_columns(
        weekday_num = pl.col("day").dt.weekday(),
        weekday_name = pl.col("day").dt.to_string("%A")
    )
    .group_by("weekday_num", "weekday_name", "target")
    .agg(Avg = pl.col("len").mean())
    .sort("weekday_num")
)

weekday_unbiased_df.show(10)

weekday_num,weekday_name,target,Avg
i8,str,str,f64
1,"""Monday""","""Legitimate""",2519.414365
1,"""Monday""","""Fraudulent""",8.506494
2,"""Tuesday""","""Legitimate""",2480.626374
2,"""Tuesday""","""Fraudulent""",9.207547
3,"""Wednesday""","""Fraudulent""",5.448276
3,"""Wednesday""","""Legitimate""",2482.662983
4,"""Thursday""","""Legitimate""",2463.022099
4,"""Thursday""","""Fraudulent""",9.309524
5,"""Friday""","""Fraudulent""",11.162791
5,"""Friday""","""Legitimate""",2326.379121

Como observamos en el siguiente gráfico de barras, los días Miércoles es cuando menor promedio de transacciones fraudulentas se registran, mientras que los Viernes, Sábados y Domingos es cuando mayor promedio hay. En el caso de las transacciones legítimas apenas oberservamos diferencias en los promedios, solo un ligero descenso en las transacciones de los días Viernes y Sábados, lo cual es destacable, ya que pese a haber un menor registro de transacciones legítimas con respecto a los otros días, es precisamente en estos días donde más se registran transacciones fraudulentas.

In [79]:
weekday_unbiased_plot = px.bar(
    weekday_unbiased_df,
    x="weekday_name",
    y="Avg",
    color="target",
    facet_col="target",
    facet_col_spacing=0.08,
    barmode="group",
    title="Average Transactions by Weekday",
    labels={"weekday_name": "Day of the Week", "Avg": "Average Transactions","target": ""},
    color_discrete_map={'Legitimate': "#263238", 'Fraudulent': "#FF3333"},
    category_orders={"target": ["Legitimate", "Fraudulent"]}
)

weekday_unbiased_plot.update_traces(
    hovertemplate="Avg: %{y:,.2f}<extra></extra>"
)

weekday_unbiased_plot.update_yaxes(matches=None, showticklabels=True)
weekday_unbiased_plot.update_xaxes(showticklabels=True, tickangle=-50) 

weekday_unbiased_plot.update_layout(
    title_x=0.5,
    width=900, height=400, autosize=False,
    hovermode="closest",
    showlegend=False
)

weekday_unbiased_plot.for_each_annotation(lambda a: a.update(text=a.text.split('=')[-1]))

weekday_unbiased_plot.show()

<br>Para verificar si hay algún día del mes donde sea más frecuente el fraude, por ejemplo al inico de mes o finales de este, agruparemos nuestros datos en funciónd el día de mes y calculares el promedio diario de transacciones legítimas y fraudulentas.

In [54]:
monthday_unbiased_df = (
    transactions_evolution_unbiased_df
    .with_columns(day_of_month = pl.col("day").dt.day())
    .group_by("day_of_month", "target")
    .agg(Average_Transactions = pl.col("len").mean())
    .sort("day_of_month")
)

monthday_unbiased_df.show(5)

day_of_month,target,Average_Transactions
i8,str,f64
1,"""Legitimate""",2486.069767
1,"""Fraudulent""",8.764706
2,"""Legitimate""",2440.093023
2,"""Fraudulent""",8.870968
3,"""Legitimate""",2434.27907

Como podemos observar, hay un ascenso en el registro de las transacciones fraudulentas en el día 6, 16 y a finales de mes. Si bien es cierto que estos datos han sido creados artificialmente por CaixaBank Tech, debemos señalar que muchos empleadores pagan a sus trabajadores el día 5 y que hay países que pagan por quincenas.

In [80]:
month_day_plot = px.bar(
    monthday_unbiased_df,
    x="day_of_month",
    y="Average_Transactions",
    color="target",
    facet_col="target",      
    facet_col_spacing=0.08,  
    title="Average Transactions by Day of the Month",
    labels={
        "day_of_month": "Day of the Month", 
        "Average_Transactions": "Average Transactions", 
        "target": ""
    },
    color_discrete_map={'Legitimate': "#263238", 'Fraudulent': "#FF3333"},
    category_orders={"target": ["Legitimate", "Fraudulent"]}
)

month_day_plot.update_traces(
    hovertemplate="Average: %{y:,.2f}<extra></extra>"
)

month_day_plot.update_yaxes(matches=None, showticklabels=True)
month_day_plot.update_xaxes(showticklabels=True)

month_day_plot.update_layout(
    title_x=0.5,
    width=900, height=400, autosize=False,
    hovermode="x unified",
    showlegend=False

)

month_day_plot.for_each_annotation(lambda a: a.update(text=a.text.split('=')[-1]))

month_day_plot.show()

<br>Además debemos tener en cuenta que no es lo mismo cobrar un Lunes, que cobrar en fin de semana, el comportamiento del cliente y el del defraudador puede ser distinto. Es por tanto que a continuación agruparemos nuestros datos por día de la semana y día del mes, de manera que por ejemplo, podamos distinguir los Lunes 1 de los Viernes 1.

In [56]:
detailed_calendar_unbiased_df = (
    transactions_evolution_unbiased_df
    .with_columns(
        day_of_month = pl.col("day").dt.day(),
        weekday_num = pl.col("day").dt.weekday(),
        weekday_name = pl.col("day").dt.to_string("%A")
    )
    .group_by("day_of_month", "weekday_num", "weekday_name", "target")
    .agg(Avg = pl.col("len").mean())
    .sort("day_of_month", "weekday_num", "target")
)

Rows_cal = detailed_calendar_unbiased_df.height
Columns_cal = detailed_calendar_unbiased_df.width
print(f"Rows: {Rows_cal}, Columns: {Columns_cal}")
detailed_calendar_unbiased_df.show(20)

Rows: 434, Columns: 5

day_of_month,weekday_num,weekday_name,target,Avg
i8,i8,str,str,f64
1,1,"""Monday""","""Fraudulent""",8.4
1,1,"""Monday""","""Legitimate""",2493.166667
1,2,"""Tuesday""","""Fraudulent""",9.333333
1,2,"""Tuesday""","""Legitimate""",2553.285714
1,3,"""Wednesday""","""Fraudulent""",4.0
1,3,"""Wednesday""","""Legitimate""",2531.5
1,4,"""Thursday""","""Fraudulent""",7.0
1,4,"""Thursday""","""Legitimate""",2492.166667
1,5,"""Friday""","""Fraudulent""",10.4
1,5,"""Friday""","""Legitimate""",2384.857143
1,6,"""Saturday""","""Fraudulent""",13.0
1,6,"""Saturday""","""Legitimate""",2444.833333
1,7,"""Sunday""","""Fraudulent""",10.8
1,7,"""Sunday""","""Legitimate""",2512.8
2,1,"""Monday""","""Fraudulent""",5.5
2,1,"""Monday""","""Legitimate""",2559.6
2,2,"""Tuesday""","""Fraudulent""",8.5
2,2,"""Tuesday""","""Legitimate""",2458.833333
2,3,"""Wednesday""","""Fraudulent""",9.6
2,3,"""Wednesday""","""Legitimate""",2503.142857

Como podemos observar en el siguiente gráfico, donde los días de la semana están ordenados en diferentes subplots verticales, y las transacciones fraudulentas a la derecha. Como observamos, no encontramos grandes diferencias en las transacciones legítimas. Mientras que las transacciones fraudulentas se disparan en Viernes y Sábados de fin de mes, mientras que mediados de mes es en general días de riesgo salvo para Lunes y Domingos.

In [57]:
detailed_calendar_unbiased_df = detailed_calendar_unbiased_df.with_columns(
    pl.col("day_of_month").cast(pl.String)
)

fig_calendar = px.bar(
    detailed_calendar_unbiased_df,
    x="day_of_month",          
    y="Avg",
    color="target",
    facet_col="target",         
    facet_row="weekday_name",   
    facet_row_spacing=0.02,
    facet_col_spacing=0.06,     
    title="Calendar Breakdown by Weekday and Target",
    labels={"day_of_month": "Day of Month", "Avg": "Avg Transactions", "target": "Is Fraud?"},
    color_discrete_map={'Legitimate': "#263238", 'Fraudulent': "#FF3333"},
    category_orders={"target": ["Legitimate", "Fraudulent"]}
)

fig_calendar.update_yaxes(matches="y", showticklabels=True, col=1)
fig_calendar.update_yaxes(matches="y2", showticklabels=True, col=2, range=[0.0, 25])

fig_calendar.update_xaxes(showticklabels=True) 

fig_calendar.update_traces(hovertemplate="Day:%{x}<br>Avg: %{y:,.2f}<extra></extra>")

fig_calendar.update_layout(
    title_x=0.5, 
    width=900, height=1400, autosize=False,
    hovermode="closest", showlegend=False
)

fig_calendar.for_each_annotation(lambda a: a.update(text=a.text.split('=')[-1]))

fig_calendar.show()

<br>Por último queremos sabes si hay una hora del día donde el fraude sea más frecuente, es por ello que a continuación agrupamos los datos por minuto del día.

In [83]:
time_fraud_unbiased_df = (
    date_fraud_unbiased_df
    .group_by("minutes_of_day", "time_str", "target")
    .len()
    .with_columns(target = label_expr)
    .sort("minutes_of_day")
    .collect()
)

time_fraud_unbiased_df.show(5)

minutes_of_day,time_str,target,len
i32,str,str,u32
0,"""00:00""","""Legitimate""",551
1,"""00:01""","""Legitimate""",510
1,"""00:01""","""Fraudulent""",1
2,"""00:02""","""Legitimate""",510
3,"""00:03""","""Legitimate""",482

Como podemos observar en el siguiente gráfico el número de transacciones cambia a lo largo del día, como es lógico, posterior a la jornada laboral hay una caída en el número de transacciones, mientras que a alrededor de la medianoche y hasta la madrugada apenas hay registro de transacciones. Por otro lado observamos que las transacciones fraudulentas presentan una hora pico de 10 a 12 de la mañana. Este comportamiento es interesante ya que el registro de crímenes publicado por el departamento de policía de los Ángeles presenta un pico similar.

In [84]:
time_fraud_false = time_fraud_unbiased_df.filter(pl.col('target') == 'Legitimate')
time_fraud_true = time_fraud_unbiased_df.filter(pl.col('target') == 'Fraudulent')

time_evolution_plot = go.Figure()

time_evolution_plot.add_trace(go.Scatter(
    x=time_fraud_false['minutes_of_day'],
    y=time_fraud_false['len'], 
    name='Legitimate',
    mode='lines',
    line=dict(color='#263238', width=1.5),
    xaxis='x', yaxis='y',
    customdata=time_fraud_false['time_str'],
    hovertemplate="Time: %{customdata}<br>Count: %{y:,.0f}<extra></extra>"
))

time_evolution_plot.add_trace(go.Scatter(
    x=time_fraud_true['minutes_of_day'],
    y=time_fraud_true['len'], 
    name='Fraudulent',
    mode='lines',
    line=dict(color='#FF3333', width=1.5),
    xaxis='x', yaxis='y2',
    customdata=time_fraud_true['time_str'],
    hovertemplate="Time: %{customdata}<br>Count: %{y:,.0f}<extra></extra>"
))

time_evolution_plot.update_layout(
    title_text='Fraud Trend by Time of Day',
    title_x=0.5,
    width=900, height=750,
    hovermode='closest',
    showlegend=False,
    
    yaxis=dict(
        title=dict(text='Legitimate'), 
        domain=[0.54, 1.0], 
        showspikes=True, spikemode='across', spikethickness=1, spikedash='dash', spikecolor="#040404"),
    yaxis2=dict(
        title=dict(text='Fraudulent'), 
        domain=[0.0, 0.46],
        showspikes=True, spikemode='across', spikethickness=1, spikedash='dash', spikecolor="#040404"),
    
    xaxis=dict(
        title='Time of Day',
        showspikes=True, spikemode='across', spikethickness=1, spikedash='dash', spikecolor="#040404",
        anchor='y2', side='bottom',
        tickmode="array",
        tickvals=[0, 240, 480, 720, 960, 1200, 1439],
        ticktext=["00:00", "04:00", "08:00", "12:00", "16:00", "20:00", "23:59"]
    )
)

time_evolution_plot.show()

---
<br>

### <span id="eda-transaccional"></span> **3.4. Análisis Exploratorio de Datos Transaccionales**

A continuación procederemos a analizar el volumen de dinero defraudado en función del método de pago. Primeramente preparamos el plan de ejecución del lazyframe utilizando las columnas `amount` y `use_chip`.

In [118]:
amountchip_fraud_unbiased_df = (
    fraud_data_df
    .with_columns(day = pl.col("date").cast(pl.Date))
    .filter(unbiased_expr)
    .select("amount", "target", "use_chip", "day")
)

Rows = amountchip_fraud_unbiased_df.select(pl.len()).collect().item()
Columns = len(amountchip_fraud_unbiased_df.collect_schema().names())

print(f"Rows: {Rows}, Columns: {Columns}")
amountchip_fraud_unbiased_df.show(5)

Rows: 3128626, Columns: 4

amount,target,use_chip,day
f64,bool,cat,date
11.18,false,"""Swipe Transaction""",2010-01-01
24.63,false,"""Online Transaction""",2010-01-01
6.58,false,"""Swipe Transaction""",2010-01-01
73.79,false,"""Swipe Transaction""",2010-01-01
8.73,false,"""Swipe Transaction""",2010-01-01

A continuación calculamos el número de trtansacciones por día según el método de pago

In [119]:
chip_evolution_df = (
    amountchip_fraud_unbiased_df
    .group_by("use_chip", "day", "target") 
    .len()
    .with_columns(target = label_expr)
    .sort("use_chip", "day", "target")
    .collect()
)

chip_evolution_df.show(5)

use_chip,day,target,len
cat,date,str,u32
"""Chip Transaction""",2015-03-30,"""Fraudulent""",1
"""Chip Transaction""",2015-03-30,"""Legitimate""",1922
"""Chip Transaction""",2015-03-31,"""Legitimate""",1887
"""Chip Transaction""",2015-04-01,"""Legitimate""",1869
"""Chip Transaction""",2015-04-02,"""Legitimate""",1692

A continuación graficamos estos datos en un *scatter plot*, donde tenemos subplots ordenados verticalmente por el método de pago, en azul, las transacciones con pago *online*, en verde las de pago con *chip* y en naranja las que se pagan con *chip*. A la izquieda tenemos los *subplots* de las transacciones legítimas y a la derecha las fraudulentas. Cabe señalar que los gráficos de transacciones legítimas, los de la izquierda, tienen una escala diferente a los de la derecha, los de transacciones fraudulentas. Como observamos las transacciones con método de pago *swipe* caen drásticamente en número con la llegada del método de pago con chip.

In [27]:
## Aquí establecemos un código de colores y un orden para elmétodo de pago y su posterior graficación 
chip_color = {
    'Online Transaction': '#7EA1B5', 
    'Swipe Transaction': '#F2A183', 
    'Chip Transaction': '#89D3C2'
}

chip_order = ["Online Transaction", "Chip Transaction", "Swipe Transaction"]

In [122]:
ordered_days = chip_evolution_df['day'].unique().sort()

chip_evolution_plot = px.scatter(
    chip_evolution_df,
    x="day",          
    y="len",
    color="use_chip",
    facet_col="target",         
    facet_row="use_chip",   
    facet_row_spacing=0.04,    
    facet_col_spacing=0.08,     
    title="Transaction Trends Over Time by Payment Method and Fraud Label",
    labels={"day": "", "len": "Transactions", "target": "Is Fraud?"},
    color_discrete_map= chip_color,
    category_orders={"use_chip": chip_order, "target": ["Legitimate", "Fraudulent"]},
    custom_data=["target"]     
)

chip_evolution_plot.update_traces(
    mode="lines",               
    line=dict(width=1.5),   
    hovertemplate="<b>Date:</b> %{x|%A, %d %b %Y}<br><b>Transactions:</b> %{y:,}<extra></extra>"
)

chip_evolution_plot.update_yaxes(
    showspikes=True, spikemode='across', spikethickness=1, spikedash='dash', spikecolor="#040404"
)
    
chip_evolution_plot.update_yaxes(matches="y", showticklabels=True, col=1)
chip_evolution_plot.update_yaxes(matches="y2",showticklabels=True, col=2)

chip_evolution_plot.update_xaxes(
    showticklabels=True, tickformat='%b %Y', matches="x", tickangle=-45, nticks=12,
    type='category', categoryorder='array', categoryarray=ordered_days,
    showspikes=True, spikemode='across', spikethickness=1, spikedash='dash', spikecolor="#040404",
) 

chip_evolution_plot.update_xaxes(showticklabels=False, row=2)
chip_evolution_plot.update_xaxes(showticklabels=False, row=3)

chip_evolution_plot.update_layout(
    title_x=0.5,
    width=900, height=900, autosize=False,                
    hovermode="x",     
    legend=dict(title="", orientation="h", yanchor="top", y=1.07, xanchor="left", x=0.15),
)

chip_evolution_plot.for_each_annotation(lambda a: a.update(text=a.text.split('=')[-1]))

chip_evolution_plot.show()

<br>Debido a que hay tendencias que son debidas a la aparición de una nueva tecnología como método de pagoy a que hay un sesgo temporal en los datos. Nosotros para este análisis elegirimos el año fiscal 2016, 30 de Marzo de 2015 a 29 de Marzo de 2016, como referente para evaluar el impacto del fraude en el cómputo total transaccional.

In [126]:
amountchip_fraud_FY2016_df = (
    amountchip_fraud_unbiased_df.filter(pl.col("day").is_between(date(2015, 3, 30), date(2016, 3, 29)))
)

amountchip_fraud_FY2016_df.show(5)

amount,target,use_chip,day
f64,bool,cat,date
23.73,false,"""Swipe Transaction""",2015-03-31
58.83,false,"""Online Transaction""",2015-03-30
160.0,false,"""Chip Transaction""",2015-03-31
200.0,false,"""Swipe Transaction""",2015-03-30
23.52,false,"""Chip Transaction""",2015-03-30

En la siguiente tabla, mostramos el resultado de calcular el número total de transacciones en el año fiscal y la cantidad defraudada según el método de pago.

In [128]:
total_amountchip_df = (
    amountchip_fraud_FY2016_df
    .group_by("target", "use_chip")
    .agg(
        total_transactions = pl.col("amount").len(),
        total_amount = pl.col("amount").sum().round(2)
    )
    .with_columns(target = label_expr)
    .sort("total_amount", descending = True)
    .collect()
)

total_amountchip_df.show(10)

target,use_chip,total_transactions,total_amount
str,cat,u32,f64
"""Legitimate""","""Chip Transaction""",660037,2.6893e7
"""Legitimate""","""Online Transaction""",112161,6.3423e6
"""Legitimate""","""Swipe Transaction""",157719,6.3288e6
"""Fraudulent""","""Online Transaction""",2491,328862.82
"""Fraudulent""","""Chip Transaction""",240,25300.37
"""Fraudulent""","""Swipe Transaction""",183,19764.05

In [129]:
#En esta sección definimos una función para graficar la cantidad defraudada y el total de transacciones
def total_chip_plot (df, y_total, y_axis):
    total_amountchip_plot = px.bar(
        df, 
        x="use_chip", 
        y=y_total, 
        color="use_chip",
        facet_row="target",             
        facet_row_spacing=0.1,         
        color_discrete_map=chip_color,
        category_orders={"use_chip": chip_order},
        text_auto=",",
        custom_data=["target"]         
    )
    
    total_amountchip_plot.update_layout(
        plot_bgcolor="white", paper_bgcolor="white", showlegend=True, 
        width=600, height=600, autosize=False,                     
        margin=dict(l=80, r=30, t=60, b=50),  
        title=dict(text="<b>Fiscal Year 2016 Transaction Breakdown by Payment Method</b>", x=0.5, font=dict(size=14, color="black")),  
        legend=dict(title="", orientation="v", yanchor="top", y=1.05, xanchor="left", x=0.8) 
    )
    
    total_amountchip_plot.update_traces(
        marker_line_color="#4A4A4A", marker_line_width=1.2,
        textposition="outside", textfont=dict(size=11, color="black"), width=0.5,
        hovertemplate="<b>%{x}</b><br>Status: %{customdata[0]}<br>Total: %{y:,}<extra></extra>"
    )
    
    total_amountchip_plot.update_yaxes(
        title= y_axis,
        gridcolor="#EAEAEA", showline=False, zeroline=False, 
        tickfont=dict(size=11, color="black"),
        matches=None, showticklabels=True
    )
    
    total_amountchip_plot.update_xaxes(
        title="", showgrid=False, linecolor="#D3D3D3", 
        tickfont=dict(size=11, color="black", weight="bold"),
        showticklabels=True
    )
    
    total_amountchip_plot.for_each_annotation(
        lambda a: a.update(
            text="<b>Legitimate</b>" if "Legitimate" in a.text 
            else ("<b>Fraudulent</b>" if "Fraudulent" in a.text 
            else f"<b>{a.text.split('=')[-1]}</b>")
        )
    )
    
    return total_amountchip_plot

En la siguiente figura, usando el código de colores establecido para el método de pago, están representadas las cantidades totales defraudadas y el dinero gastado en transacciones legítimas. Como se observa las transacciones online, son en las que mayor cantidad de dinera se defrauda, lo cual contrasta con la tendencia observada en las cantidades totales movidas en transferencias legítimas, donde las transacciones online son las que menor cuantía en transacciones representan.

In [130]:
total_chip_plot (total_amountchip_df, "total_amount", "<b>Total Amount ($)</b>")

<br>Cuando analizamos el número total de transacciones, observamos las mismas tendecias descritas arriba.

In [131]:
total_chip_plot (total_amountchip_df, "total_transactions", "<b>Total Transactions</b>")

Para hacer una comparación más adecuada entre los métodos de pago y una mayor tendecia al fraude, nosotros calcularemos la cantidad de dinero defraudada cada 10.000 transacciones por método de pago.

In [133]:
ratio_fraud = (
    total_amountchip_df
    .pivot(
        on="target", index="use_chip", values="total_transactions", aggregate_function="sum"
    )
    .with_columns(
        Frauds_per_10k_Transactions =
            pl.col("Fraudulent") / (pl.col("Fraudulent") + pl.col("Legitimate")) * 10000
    )
    .sort("Frauds_per_10k_Transactions", descending = True)
)

ratio_fraud.show()

use_chip,Legitimate,Fraudulent,Frauds_per_10k_Transactions
cat,u32,u32,f64
"""Online Transaction""",112161,2491,217.266162
"""Swipe Transaction""",157719,183,11.589467
"""Chip Transaction""",660037,240,3.634838

Como observamos en el siguiente gráfico las transacciones online son las que ampliamente presentan mayor tasa de fraude. Mientras que las transacciones con pago con *chip* son las que menor tasa de fraude presentan.

In [136]:
ratio_fraud_plot = px.bar(
    ratio_fraud, 
    x="use_chip", 
    y="Frauds_per_10k_Transactions", 
    color="use_chip",
    color_discrete_map= chip_color,
    category_orders={"use_chip": chip_order},
    text_auto=",.2f" 
)

ratio_fraud_plot.update_layout(
    plot_bgcolor="white", paper_bgcolor="white", showlegend=True, 
    width=600, height=350, autosize=False, margin=dict(l=60, r=30, t=50, b=50), 
    title=dict(text="<b>Fraud Rate by Payment Method (FY16)</b>", x=0.5, font=dict(size=14, color="black"),),     
    xaxis=dict(title="", showgrid=False, linecolor="#D3D3D3", tickfont=dict(size=12, color="black", weight="bold")),    
    yaxis=dict(title="<b>Amount defrauded per 10k Transactions</b>", gridcolor="#EAEAEA", showline=False, zeroline=False,
               tickfont=dict(size=10, color="black")),   
    legend=dict(title="", orientation="v", yanchor="bottom", y=0.75, xanchor="right", x=1),    
)

ratio_fraud_plot.update_traces(
    marker_line_color="#4A4A4A", marker_line_width=1.2,
    textposition="outside", textfont=dict(size=13, color="black"),
    width=0.5,
    hovertemplate="<b>%{x}</b><br>Total: %{y:,}$<extra></extra>"
)

ratio_fraud_plot.show()

<br>A continuación queremos conocer cual es la distribución de las cantidades movidas en las transacciones y si estas presentan un comportamiento diferente en el fraude. Para su representación, debido al amplio número de datos de las transacciones legítimas, tomaremos una muestra representativa de este grupo, para su posterior verifiación. Para ello creamos un dataset con el siguiente número de transaccciones:

In [146]:
true_amountchip_fraud_FY2016_df = (
    amountchip_fraud_FY2016_df
    .filter(pl.col("target"))
    .with_columns(target = label_expr)
    .drop("day")
    .collect()
)

false_amountchip_fraud_FY2016_df = (
    amountchip_fraud_FY2016_df
    .filter(~pl.col("target"))
    .with_columns(target = label_expr)
    .drop("day")
    .collect()
    .sample(fraction=0.004, seed=777)
)

sample_amountchip_fraud_FY2016_df = pl.concat(
    [false_amountchip_fraud_FY2016_df, true_amountchip_fraud_FY2016_df]
)

print(f"Number of Transactions Legítimas: {false_amountchip_fraud_FY2016_df.height}")
print(f"Number of Transactions Fraudulentas: {true_amountchip_fraud_FY2016_df.height}")

Number of Transactions Legítimas: 3719
Number of Transactions Fraudulentas: 2914

Como se observa en el gráfico, las transacciones fraudulentas presentan una alta concentración de valores atípicos (outliers) en comparación con las legítimas. Asimismo, la curva de distribución demuestra que el fraude tiende a concentrarse en montos significativamente más altos.

In [147]:
fig_violin = px.violin(
    sample_amountchip_fraud_FY2016_df,
    x="target",
    y="amount", 
    color="target",        
    points="outliers",
    labels={"amount": "Transaction Amount ($)", "target": "Is Fraud?"},
    color_discrete_map={'Legitimate': '#263238', 'Fraudulent': '#FF3333'},
    box=True,
)

fig_violin.update_traces(
    box_fillcolor="white", box_line_color="#4A4A4A", box_line_width=1.5, box_width=0.1, 
    meanline_visible=True,
    width=0.8, bandwidth=6, 
    # hoveron="violins",    
)

fig_violin.update_layout(
    plot_bgcolor="white", paper_bgcolor="white", showlegend=False,
    width=900, height=700, margin=dict(l=60, r=30, t=80, b=80),
    title=dict(text="<b>Transaction Amount Breakdown by Fraud</b>", x=0.12,font=dict(size=12),),
    xaxis=dict(title="", showgrid=False, linecolor="#D3D3D3", tickfont=dict(size=11, color="black", weight="bold")),
    yaxis=dict(title="<b>Transaction Amount ($)</b>", gridcolor="#EAEAEA", showline=False, zeroline=False),   
)

fig_violin.show()

<br>Cuando desglosamos estos valores por método de pago observamos que estas tendencias se mantienen de igual manera a lo observado arriba en todos los métodos de pago.

In [149]:
fig = px.violin(
    sample_amountchip_fraud_FY2016_df,  
    x="target",  
    y="amount",  
    color="use_chip", 
    facet_col="use_chip",             
    facet_col_spacing=0.04,
    color_discrete_map=chip_color, 
    category_orders={"target": chip_order},
    box=True,  
    points=False,
)

fig.update_layout(
    violinmode="group", boxmode="group",
    plot_bgcolor="white", paper_bgcolor="white", showlegend=True,
    width=900, height=600, autosize=False, margin=dict(l=60, r=30, t=80, b=80),
    title=dict(text="<b>Transaction Amount Breakdown by Fraud and Payment Method</b>", 
               x=0.12,font=dict(size=12),),
    legend=dict(title="", orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    yaxis=dict(title="<b>Transaction Amount ($)</b>", gridcolor="#EAEAEA", showline=False, 
               zeroline=False, 
               range=[-115, 600] 
              ),   
)

fig.update_traces(
    box_fillcolor="white", box_line_color="#4A4A4A", box_line_width=1.5, box_width=0.1, 
    meanline_visible=True,
    line=dict(color="#4A4A4A", width=1.2),    
    width=1,
    bandwidth=6, 
    hoveron="violins",    
)

fig.update_yaxes(showgrid=True, gridcolor="#EAEAEA", showline=False, zeroline=False)
fig.update_xaxes(title_text="")
fig.update_annotations(text="")

fig.for_each_trace(lambda trace: trace.update(fillcolor=chip_color.get(trace.name, "#CCCCCC")))
  
fig.show()

---
<br>

### <span id="eda-espacial"></span> **3.5. Análisis Exploratorio de Datos Espaciales**

A continuación haremos un análisis del fraude en función del lugar del comercio donde se produce, sin embargo no haremos un filtro temporal, ya que en este análisis exploratorio queremos tener disponibles todos los valores de los datos espaciales

In [38]:
location_fraud_unbiased_df = (
    fraud_data_df
    .with_columns(day = pl.col("date").cast(pl.Date))
    .filter((pl.col("target").is_not_null()))
    .with_columns(merchant_state = pl.col("merchant_state").fill_null("No_Country"))    
    .select("merchant_city", "merchant_state", "zip", 
            "merchant_latitude", "merchant_longitude",
            "client_latitude", "client_longitude",
            "target", "use_chip", "amount", "day", "date"
           )
)

Rows = location_fraud_unbiased_df.select(pl.len()).collect().item()
Columns = len(location_fraud_unbiased_df.collect_schema().names())

print(f"Rows: {Rows}, Columns: {Columns}")
location_fraud_unbiased_df.show(5)

Rows: 8914963, Columns: 12

merchant_city,merchant_state,zip,merchant_latitude,merchant_longitude,client_latitude,client_longitude,target,use_chip,amount,day,date
str,str,str,f64,f64,f64,f64,bool,cat,f64,date,datetime[μs]
"""Sumter""","""SC""","""29153""",33.9446,-80.3206,33.94,-80.39,false,"""Swipe Transaction""",11.18,2010-01-01,2010-01-01 03:08:00
"""ONLINE""","""No_Country""",null,null,null,28.7,-81.34,false,"""Online Transaction""",24.63,2010-01-01,2010-01-01 07:33:00
"""Wethersfield""","""CT""","""06109""",41.7013,-72.6763,41.7,-72.67,false,"""Swipe Transaction""",6.58,2010-01-01,2010-01-01 06:16:00
"""Erie""","""PA""","""16511""",42.1553,-80.0177,41.47,-81.67,false,"""Swipe Transaction""",73.79,2010-01-01,2010-01-01 00:32:00
"""Spring Creek""","""NV""","""89815""",40.7519,-115.5956,39.21,-119.71,false,"""Swipe Transaction""",8.73,2010-01-01,2010-01-01 04:54:00

En este dataset, la columna de estados tiene registrado las operaciones dentro de los estados de Estados Unidos como de los países extranjeros. El total de "estados" diferentes registrados es de:

In [39]:
n_states = location_fraud_unbiased_df.select(pl.col('merchant_state').n_unique()).collect().item()
print(f"Number of states: {n_states}")

Number of states: 200

A continuación creamos una nueva columna, `merchant_country`, donde registramos el país del comercio destino de la transacción. Para ello creamos una lista de los estados de Estados Unidos por su código USPS y aplicamos una condición: si el estado del comercio se encuentra en dicha lista, se asigna 'USA'; de lo contrario, se conserva el valor original de la región.

In [40]:
USA_states = [
    "CA", "NY", "TX", "FL", "ID", "CT", "IL", "PA", "OH", "GA", 
    "MI", "NC", "NJ", "VA", "WA", "AZ", "AK", "AL", "AR", "CO", 
    "DE", "HI", "IA", "IN", "KS", "KY", "LA", "MA", "MD", "ME", 
    "MN", "MO", "MS", "MT", "ND", "NE", "NH", "NM", "NV", "OK", 
    "OR", "RI", "SC", "SD", "TN", "UT", "VT", "WI", "WV", "WY",
    "DC"
]

location_fraud_unbiased_df = (
    location_fraud_unbiased_df
    .with_columns(
        merchant_country = pl.when(pl.col("merchant_state").is_in(USA_states))
                             .then(pl.lit("USA")).otherwise(pl.col("merchant_state"))
    )
)

location_fraud_unbiased_df.show(5)

merchant_city,merchant_state,zip,merchant_latitude,merchant_longitude,client_latitude,client_longitude,target,use_chip,amount,day,date,merchant_country
str,str,str,f64,f64,f64,f64,bool,cat,f64,date,datetime[μs],str
"""Sumter""","""SC""","""29153""",33.9446,-80.3206,33.94,-80.39,false,"""Swipe Transaction""",11.18,2010-01-01,2010-01-01 03:08:00,"""USA"""
"""ONLINE""","""No_Country""",null,null,null,28.7,-81.34,false,"""Online Transaction""",24.63,2010-01-01,2010-01-01 07:33:00,"""No_Country"""
"""Wethersfield""","""CT""","""06109""",41.7013,-72.6763,41.7,-72.67,false,"""Swipe Transaction""",6.58,2010-01-01,2010-01-01 06:16:00,"""USA"""
"""Erie""","""PA""","""16511""",42.1553,-80.0177,41.47,-81.67,false,"""Swipe Transaction""",73.79,2010-01-01,2010-01-01 00:32:00,"""USA"""
"""Spring Creek""","""NV""","""89815""",40.7519,-115.5956,39.21,-119.71,false,"""Swipe Transaction""",8.73,2010-01-01,2010-01-01 04:54:00,"""USA"""

Contamos el número de países resultantes, el resultado consistente, teniendo en cuenta que Estados Unidos tiene 50 estados.

In [41]:
n_countries = location_fraud_unbiased_df.select(pl.col('merchant_country').n_unique()).collect().item()
print(f"Number of countries: {n_countries}")

Number of countries: 150

Listamos los países que presentan como destino transacciones fraudulentas.

In [42]:
fraudulent_countries_df = (
    location_fraud_unbiased_df
    .filter(pl.col("target"))
    .select(pl.col("merchant_country").unique())
    .collect() 
)

fraudulent_countries_list = fraudulent_countries_df["merchant_country"].to_list()
fraudulent_countries_list

['Haiti', 'Italy', 'No_Country', 'USA', 'Tuvalu']

A continuación calculamos el número de transacciones legítimas y fraudulentas que se registran en estos países.

In [43]:
iso_country = {
    "Haiti": "HTI",
    "Tuvalu": "TUV",
    "Italy": "ITA",
    "USA": "USA" 
}

rate_country_fraud_unbiased_df = (
    location_fraud_unbiased_df
    .filter(
        pl.col("merchant_country").is_in(fraudulent_countries_list) &
        (pl.col("merchant_country") != "No_Country")
    )
    .group_by("merchant_country", "target")
    .agg(Total = pl.col("target").len())
    .with_columns(
        fraud_rate = (pl.col("Total") / pl.col("Total").sum().over("target") * 100).round(2),
        merchant_country = pl.col("merchant_country").replace(iso_country)
    )
    .with_columns(target = label_expr)
    .sort("Total", descending=True)
    .collect()
)

rate_country_fraud_unbiased_df.show(10)

merchant_country,target,Total,fraud_rate
str,str,u32,f64
"""USA""","""Legitimate""",7806349,99.98
"""ITA""","""Fraudulent""",3061,67.23
"""ITA""","""Legitimate""",1645,0.02
"""USA""","""Fraudulent""",1234,27.1
"""HTI""","""Fraudulent""",253,5.56
"""HTI""","""Legitimate""",11,0.0
"""TUV""","""Fraudulent""",5,0.11

A continuación, presentamos una visualización geográfica donde representamos las regiones afectadas mediante una escala de calor, la cual refleja la frecuencia del fraude en relación con el número total de transacciones fraudulentas o legítimas según el caso. Donde observamos que Italia es un punto caliente de destino para las transacciones fraudulentas.

In [44]:
min_tasa = rate_country_fraud_unbiased_df['fraud_rate'].min()
max_tasa = rate_country_fraud_unbiased_df['fraud_rate'].max()

rate_country_fraud_unbiased_map = px.choropleth(
    rate_country_fraud_unbiased_df,
    locations="merchant_country", 
    locationmode="ISO-3",   
    color="fraud_rate",
    facet_row="target",
    scope="world",                 
    color_continuous_scale="YlOrRd", 
    range_color=[min_tasa, max_tasa],
    title="<b>Geographic Distribution: Transaction Rate by Country and Legitimacy</b>",
    labels={"fraud_rate": "Transactions(%)", "merchant_country": "País"}
)


rate_country_fraud_unbiased_map.update_geos(
    projection_type="natural earth",
    lakecolor="white", showlakes=True,
    lataxis_range=[-13, 71],   
    lonaxis_range=[-187, 20]  
)

coords = {
    'Italy': {'lat': 41.87, 'lon': 12.56},
    'USA': {'lat': 37.09, 'lon': -95.71},
    'Haiti': {'lat': 18.97, 'lon': -72.28},
    'Tuvalu': {'lat': -8.52, 'lon': 179.21} 
}

for pais, pos in coords.items():
    rate_country_fraud_unbiased_map.add_trace(
        go.Scattergeo(
            lat=[pos['lat']], lon=[pos['lon']],
            name=pais,
            mode='markers',
            marker=dict(size=30, color='black', symbol='circle-open', opacity=1),
            showlegend=True,
            hoverinfo="skip",
            geo="geo" 
        )
    )
    rate_country_fraud_unbiased_map.add_trace(
        go.Scattergeo(
            lat=[pos['lat']], lon=[pos['lon']],
            name=pais,
            mode='markers',
            marker=dict(size=30, color='black', symbol='circle-open', opacity=1),
            showlegend=False,
            hoverinfo="skip",
            geo="geo2" 
        )
    )

rate_country_fraud_unbiased_map.update_layout(
    title_x=0.05,                
    width=900, height=800, autosize=False,                 
    margin=dict(l=10, r=10, t=50, b=50),    
    coloraxis_colorbar=dict(
        title="%",
        orientation="h", thickness=15, len=0.3,       
        xanchor="center", x=0.2,
        yanchor="top",  y= -0.
    ),
    legend=dict(
        orientation="h", 
        yanchor="bottom", y=-0.049,          
        xanchor="center", x=0.69, 
        title_text="<b>Countries:</b>"
    )
)

rate_country_fraud_unbiased_map.for_each_annotation(lambda a: a.update(
    text=f"<b>{a.text.split('=')[-1]}</b>",
    font=dict(size=14, color="black")
    )
)

rate_country_fraud_unbiased_map.show()

<br> A continuación desglosamos el resultado anterior por método de pago.

In [45]:
number_country_fraud_unbiased_df = (
    location_fraud_unbiased_df
    .filter(pl.col("merchant_country").is_in(fraudulent_countries_list))
    .group_by("merchant_country", "target", "use_chip")
    .agg(Total = pl.col("target").len())
    .with_columns(target = label_expr)
    .sort("Total", descending=True)
    .collect()
)

number_country_fraud_unbiased_df.show(10)

merchant_country,target,use_chip,Total
str,str,cat,u32
"""USA""","""Legitimate""","""Swipe Transaction""",4634888
"""USA""","""Legitimate""","""Chip Transaction""",3171461
"""No_Country""","""Legitimate""","""Online Transaction""",1035196
"""No_Country""","""Fraudulent""","""Online Transaction""",8779
"""No_Country""","""Legitimate""","""Chip Transaction""",3890
"""Italy""","""Fraudulent""","""Chip Transaction""",2786
"""Italy""","""Legitimate""","""Swipe Transaction""",888
"""USA""","""Fraudulent""","""Swipe Transaction""",844
"""Italy""","""Legitimate""","""Chip Transaction""",757
"""USA""","""Fraudulent""","""Chip Transaction""",390

En la siguiente figura están representados los datos descritos arriba, aquí se observa que el método de pago *chip* es el predominante en las transacciones fraudulentas en Italia. Mientras que en USA hay una mayor proporción de fraude en las transaciones que se pagan con *chip* que con *swipe*.

In [46]:
number_country_fraud_unbiased_fig = px.bar(
    number_country_fraud_unbiased_df,
    x="Total",
    y="merchant_country",
    color="use_chip",
    facet_col= "target",
    orientation="h",
    barmode="stack",
    title="Total Transactions by Country, Legitimacy, and Payment Method",
    color_discrete_map= chip_color,
        labels={"Total": "Number of Frauds", "merchant_country": "Country", 
            "use_chip": "Payment Method"}
)

number_country_fraud_unbiased_fig.update_traces(
    marker_line_color='black', marker_line_width=0.9
)

number_country_fraud_unbiased_fig.update_xaxes(matches=None, showgrid=True, gridcolor="#EAEAEA")
number_country_fraud_unbiased_fig.update_yaxes(autorange="reversed", showgrid=True, gridcolor="#EAEAEA")

number_country_fraud_unbiased_fig.update_layout(
    plot_bgcolor="white", paper_bgcolor="white",
    width=900, height=350, autosize=False,
    legend=dict(title="", orientation="h", yanchor="top", y=1.28, xanchor="left", x=0.15)
)

number_country_fraud_unbiased_fig.for_each_annotation(lambda a: a.update(text=a.text.split('=')[-1]))

number_country_fraud_unbiased_fig.show()

El análisis anterior lo repetimos teniendo en cuenta ahora la cuantía defraudada para evidenciar el impacto económico sobre la entidad bancaria.

In [47]:
amount_country_fraud_unbiased_df = (
    location_fraud_unbiased_df
    .filter(pl.col("merchant_country").is_in(fraudulent_countries_list))
    .group_by("merchant_country", "target", "use_chip")
    .agg(Total = pl.col("amount").sum())
    .with_columns(target = label_expr)
    .sort("Total", descending=True)
    .collect()
)

amount_country_fraud_unbiased_df.show(5)

merchant_country,target,use_chip,Total
str,str,cat,f64
"""USA""","""Legitimate""","""Swipe Transaction""",1.9111e8
"""USA""","""Legitimate""","""Chip Transaction""",1.2990e8
"""No_Country""","""Legitimate""","""Online Transaction""",5.8667e7
"""No_Country""","""Fraudulent""","""Online Transaction""",1.0616e6
"""Italy""","""Fraudulent""","""Chip Transaction""",238236.91

En la lista del volumen de dinero de transaccciones por *chip*, observamos que aquellos sitios donde no hay un registro del pais la suma es negativa (en la anterior tabla observamos que este subconjunto representa un total de 3890 operaciones), deducimos que esto es por alguna particularidad de la naturaleza de algunos reembolsos por chip o por algún error o sesgo del dataset. Dado que este número es ínfimo en comparación al resto de transacciones legítimas sin país atribuido, continuaremos con la misma forma de representar los gráficos, y evitaremos el uso de gráficos de divergencia. En el siguiente gráfico observamos la misma tendencia que en los casos anteriores. Siendo destacable que la cantidad defraudada en Italia es superior a la de USA, país de origen de los clientes.

In [48]:
amount_country_fraud_unbiased_fig = px.bar(
    amount_country_fraud_unbiased_df,
    x="Total",
    y="merchant_country",
    color="use_chip",
    facet_col = "target",
    orientation="h",
    barmode="stack",
    title="Transaction Amount Breakdown by Country, Legitimacy, and Payment Method",
    color_discrete_map= chip_color,
    labels={"Total": "Amount", "merchant_country": "Country", 
            "use_chip": "Payment Method"}
)

amount_country_fraud_unbiased_fig.update_traces(
    marker_line_color='black', marker_line_width=0.9
)

amount_country_fraud_unbiased_fig.update_xaxes(matches=None, showgrid=True, gridcolor="#EAEAEA",
                                              title="Total Amount ($)")
amount_country_fraud_unbiased_fig.update_yaxes(autorange="reversed", showgrid=True, gridcolor="#EAEAEA")

amount_country_fraud_unbiased_fig.update_layout(
    plot_bgcolor="white", paper_bgcolor="white",
    width=900, height=350, autosize=False,
    legend=dict(title="", orientation="h", yanchor="top", y=1.27, xanchor="left", x=0.15)
)

amount_country_fraud_unbiased_fig.for_each_annotation(lambda a: a.update(text=a.text.split('=')[-1]))

amount_country_fraud_unbiased_fig.show()

<br>Para evaluar si el destino de las transacciones fradulentas cambia a lo largo del tiempo, agrupamos nuestras transacciones fraudulentas por día y país del comercio.

In [49]:
count_year_fraud_df = (
    location_fraud_unbiased_df
    .filter(pl.col("target"))
    .select("merchant_country", "day")
    .group_by("day", "merchant_country")
    .len()
    .collect()
)

count_year_fraud_df.show(5)

day,merchant_country,len
date,str,u32
2010-01-15,"""No_Country""",1
2010-01-28,"""No_Country""",19
2010-01-17,"""No_Country""",3
2010-01-19,"""Tuvalu""",1
2010-01-27,"""No_Country""",1

Establecemos un código de colores para representar las transacciones fraudlentas de estos países en un *scatter plot*, adem'as establecemos un orden para que los países con menor número de fraudes no queden ocultos por los que más fraude tienen.

In [50]:
country_color = {
    'USA': '#636EFA', 
    'Italy': '#FFA15A', 
    'Haiti': '#EF553B',
    'Tuvalu': '#AB63FA', 
    'No_Country': '#00CC96'    
}
country_order= ['Italy', 'No_Country', 'USA', 'Haiti', 'Tuvalu']

Como podemos observar en el *scatter plot* y ya habíamos mencionado en el análisis temporal, tenemos un gap en el registro de las transacciones fradulentas. Por otro lado, observamos que efectivamente hay un cambio en el país destino de las transacciones fradulentas en el tiempo. Solo en el año 2010 encontramos transaccciones fraudulentas con destino en Tuvalu y Haiti, mientras que solo a partir del año 2018 encontramos transacciones fraudulentas en Italia. Tambi'en es destacable que en nuestro dataset no hay registro de transacciones fraudulentas en comercios de Estados Unidos antes de 2012.

In [51]:
count_year_fraud_fig = px.scatter(
    count_year_fraud_df,
    x="day",        
    y="len",    
    color="merchant_country", 
    opacity=0.6,
    category_orders={"merchant_country": country_order},
    color_discrete_map= country_color,
    title="<b>Total Fraudulent Transactions by Country and Year</b>",
    labels={"day": "Timeline", "len": "Total Transactions per day",
            "merchant_country": ""}
)

count_year_fraud_fig.update_traces(
    marker=dict(line=dict(color='black', width=0.45)))

count_year_fraud_fig.update_layout(
    plot_bgcolor="white", paper_bgcolor="white",
    width=900, height=350, autosize=False,
    xaxis=dict(showgrid=True, gridcolor="#EAEAEA"),
    yaxis=dict(showgrid=True, gridcolor="#EAEAEA"),
    legend=dict(title="", orientation="h", yanchor="top", y=1.2, xanchor="left", x=0.15)
)

count_year_fraud_fig.show()

<br>Para evaluar el impacto económico del fraude por país en el tiempo, agrupamos por cantidad total de dinero defraudado por día.

In [52]:
amount_year_fraud_df = (
    location_fraud_unbiased_df
    .filter(pl.col("target"))
    .select("merchant_country", "amount", "day")
    .group_by("day", "merchant_country")
    .agg(Total = pl.col("amount").sum())
    .collect()
)

amount_year_fraud_df.show(5)

day,merchant_country,Total
date,str,f64
2010-09-17,"""Haiti""",54.67
2010-01-12,"""No_Country""",1014.41
2010-01-08,"""No_Country""",383.24
2010-01-10,"""No_Country""",530.01
2010-01-07,"""No_Country""",-48.46

Cuando representamos estos datos en un *scatter plot*, encontramos que las cantidades de dinero defraudadas en Haiti son menores que en Italia o en USA, mientras que en Italia hay unba mayor proporción de mayores cantidades diarias defraudadas.

In [53]:
amount_year_fraud_fig = px.scatter(
    amount_year_fraud_df,
    x="day",        
    y="Total",    
    color="merchant_country", 
    opacity=0.6,
    category_orders={"merchant_country": country_order},
    color_discrete_map= country_color,
    title="<b>Amount Transaction Volume by Country and Year</b>",
    labels={"day": "Timeline", "Total": "Amount Transaction Volume per day ($)", "merchant_country": "Country"}
)

amount_year_fraud_fig.update_traces(
    marker=dict(line=dict(color='black', width=0.45)))

amount_year_fraud_fig.update_layout(
    plot_bgcolor="white", paper_bgcolor="white",
    width=900, height=350, autosize=False,
    xaxis=dict(showgrid=True, gridcolor="#EAEAEA"),
    yaxis=dict(showgrid=True, gridcolor="#EAEAEA"),
    legend=dict(title="", orientation="h", yanchor="top", y=1.2, xanchor="left", x=0.15)
)

amount_year_fraud_fig.show()

<br> A continuación analizamos las regiones externas a USA en las que se registra fraude, observamos que esta se da en las capitales de los países defraudadares. Y que en Tuvalu solo se registran transacciones fraudulentas.

In [54]:
No_USA_fraud_countries_df = (
    location_fraud_unbiased_df
    .filter(pl.col("merchant_country").is_in(['Italy', 'Haiti', 'Tuvalu']))
    .group_by("merchant_country", "merchant_city", "zip", "target")
    .agg(Total = pl.col("target").len())
    .with_columns(
        trx_rate = (pl.col("Total") / pl.col("Total").sum().over("target") * 100).round(2)
    )
    .sort("trx_rate", descending=True)
)

No_USA_fraud_countries_df.show(10)

merchant_country,merchant_city,zip,target,Total,trx_rate
str,str,str,bool,u32,f64
"""Italy""","""Rome""",null,false,1645,99.34
"""Italy""","""Rome""",null,true,3061,92.23
"""Haiti""","""Port au Prince""",null,true,253,7.62
"""Haiti""","""Port au Prince""",null,false,11,0.66
"""Tuvalu""","""Funafuti""",null,true,5,0.15

A continuación nos centraremos en analizar las diferentes regiones de Estados Unidos, a partir de aquí volveremos a filtrar los datos que presentan sesgo. En esta sección analizaremos la frecuencia de las transacciones fraudulentas y de las frecuencias legítimas en los diferentes estados de Estados Unidos.

In [55]:
rate_USAstates_fraud_unbiased_df = (
    location_fraud_unbiased_df
    .filter(unbiased_expr & (pl.col("merchant_country") == 'USA'))
    .group_by("merchant_state", "target")
    .agg(Total = pl.col("target").len())
    .with_columns(trx_rate = (pl.col("Total") / pl.col("Total").sum().over("target") * 100).round(2))
    .with_columns(target = label_expr)
    .sort("trx_rate", descending=True)
    .collect()
)

rate_USAstates_fraud_unbiased_df.show(5)

merchant_state,target,Total,trx_rate
str,str,u32,f64
"""OH""","""Fraudulent""",288,30.22
"""CA""","""Legitimate""",336646,12.32
"""CA""","""Fraudulent""",95,9.97
"""TX""","""Legitimate""",236148,8.64
"""NY""","""Legitimate""",201029,7.36

Los datos de la tabla anterior los gráficamos en una visualización geográfica donde representamos las regiones afectadas mediante una escala de calor, la cual refleja la frecuencia del fraude en relación con el número total de transacciones fraudulentas o legítimas según el caso. Lo más destacado de estos resultados es la alta frecuencia de operaciones frauduletnas en Ohio, estado que concentra el 25,61% de las operaciones fraudulentas, mientras que Alaska no registra ninguna transacción fraudulenta.

In [56]:
min_tasa = rate_USAstates_fraud_unbiased_df['trx_rate'].min()
max_tasa = rate_USAstates_fraud_unbiased_df['trx_rate'].max()

rate_USAstates_fraud_unbiased_map = px.choropleth(
    rate_USAstates_fraud_unbiased_df,
    locations="merchant_state",      
    locationmode="USA-states",        
    color="trx_rate", 
    facet_col="target",
    scope="usa",                      
    color_continuous_scale="Viridis",
    range_color=[min_tasa, max_tasa],
    title="<b>Geographic Distribution: Transaction Rate by State and Legitimacy (USA)</b>",
    labels={"fraud_rate": "Participación de Fraude (%)", "merchant_state": "Estado"}
)

rate_USAstates_fraud_unbiased_map.update_layout(
    title_x=0.05,                
    height=400, width=900, autosize=False,                 
    margin=dict(l=10, r=10, t=10, b=10), 
    
    coloraxis_colorbar=dict(
        title="%",
        orientation="h",  
        thickness=15, len=0.5,           
        x=0.5, xanchor="center",
        y=1.05, yanchor="bottom"
    )
)

rate_USAstates_fraud_unbiased_map.for_each_annotation(lambda a: a.update(
    text=f"<b>{a.text.split('=')[-1]}</b>",
    font=dict(size=14, color="black")
    )
)

rate_USAstates_fraud_unbiased_map.show()

<br>A continuación analizamos la distribución espacial del fraude por código postal en las regiones de Estados Unidos, agrupando por las coordenadas del comercio y la auditoría de la transacción. En la siguiente tabla es destacable que hay una coordenada en la que se registran 213 fraudes, bastante superior al resto de coordenadas.

In [57]:
rate_USAzip_fraud_unbiased_df = (
    location_fraud_unbiased_df
    .filter(unbiased_expr & (pl.col("merchant_country") == 'USA'))
    .group_by("merchant_latitude", "merchant_longitude", "target")
    .agg(Total = pl.col("target").len())
    .with_columns(
        trx_rate = (pl.col("Total") / pl.col("Total").sum().over("target") * 100).round(2)
    )
    .with_columns(target = label_expr)
    .sort("trx_rate", descending=True)
    .collect()
)

rate_USAzip_fraud_unbiased_df.show(5)

merchant_latitude,merchant_longitude,target,Total,trx_rate
f64,f64,str,u32,f64
40.6003,-81.5366,"""Fraudulent""",213,22.35
40.5148,-81.6604,"""Fraudulent""",23,2.41
43.18,-95.4817,"""Fraudulent""",8,0.84
40.9637,-81.4211,"""Fraudulent""",7,0.73
40.8094,-81.9483,"""Fraudulent""",5,0.52

In [56]:
USAzip_fraud_df = rate_USAzip_fraud_unbiased_df.filter(pl.col('target') == 'Fraudulent')
USAzip_leg_df = rate_USAzip_fraud_unbiased_df.filter(pl.col('target') == 'Legitimate')

print("Total Fraudulent Transactions in USA:", USAzip_fraud_df["Total"].sum())
print("Total Legitimate Transactions in USA:", USAzip_leg_df["Total"].sum())
print("Fraudulent Transaction Map Points:", len(USAzip_fraud_df))
print("Legitimate Transaction Map Points:", len(USAzip_leg_df))

Total Fraudulent Transactions in USA: 954
Total Legitimate Transactions in USA: 2738481
Fraudulent Transaction Map Points: 617
Legitimate Transaction Map Points: 19481

En la siguiente visualización gráfica dibujamos mapas de dendidad para representar la frecuencia de las transacciones. Como podemos observar hay una alta concentración de comercios en Ohio en el que se registra fraude, lugar que presenta la coordenada en la que se registraron 213 fraudes.

In [58]:
rate_USAzip_fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=("<b>Fraudulent</b>", "<b>Legitimate</b>"),
    specs=[[{"type": "map"}, {"type": "map"}]],
    horizontal_spacing=0.01
)

rate_USAzip_fig.add_trace(
    go.Densitymap(
        lat= USAzip_fraud_df['merchant_latitude'], 
        lon= USAzip_fraud_df['merchant_longitude'], 
        z= USAzip_fraud_df['trx_rate'],
        radius=8, opacity=0.8,
        colorscale="Inferno", showscale=True, 
        zmin=0.0, zmax=2,  
        colorbar=dict(
            title="Percentage (%)", orientation="h", 
            y=1.05, x=0.5, 
            xanchor="center",thickness=15, len=0.6
        )
    ), row=1, col=1
)

rate_USAzip_fig.add_trace(
    go.Densitymap(
        lat=USAzip_leg_df['merchant_latitude'], 
        lon=USAzip_leg_df['merchant_longitude'], 
        z=USAzip_leg_df['trx_rate'],
        radius=8, opacity=0.8,
        colorscale="Inferno", showscale=False,
        zmin=0.0, zmax=2                 
    ), row=1, col=2
)

rate_USAzip_fig.update_layout(
    title_text="<b>Geographic Distribution: Transaction Rate by ZIP merchant and Legitimacy</b>",
    title_x=0.02,
    margin={"r":15, "t":120, "l":15, "b":15},
    height=500, width=900, autosize=False,
    map=dict(style="carto-positron", center=dict(lat=37.0902, lon=-95.7129), zoom=2.1),
    map2=dict(style="carto-positron", center=dict(lat=37.0902, lon=-95.7129), zoom=2.1)
)

rate_USAzip_fig.show()

<br>Un análisis en el que se busque encontrar si hay una región de residencia de los clientes donde sa más probabable ser víctima de fraude financiero está descartado para este trabajo
ya que en este dataset de 1219 clientes, 1196 fueron víctimas de fraude.

---
<br>

### <span id="client-behaviour"></span> **3.6. Comportamiento de Compra**

A continuación queremos analziar el comportamiento de compra de cada cliente, primeramente creamos una lista de clientes defraudados para intentar encontrar alguna tendencia en las operaciones de fraude.

In [55]:
fraudulent_client_df = (
    fraud_data_df
    .select("client_id", "target", "gender", "current_age", "client_latitude", "client_longitude")
    .filter(pl.col("target"))
    .unique()
    .sort("client_id")
    .drop("target")
    .collect()
)

fraudulent_client_list = fraudulent_client_df["client_id"].to_list()
print("Total Clients with Fraudulent Transactions:", len(fraudulent_client_list))

fraudulent_client_df.show(5)

Total Clients with Fraudulent Transactions: 1196

client_id,gender,current_age,client_latitude,client_longitude
i64,cat,i64,f64,f64
0,"""Male""",33,43.59,-70.33
1,"""Female""",43,30.44,-87.18
2,"""Male""",48,40.84,-73.87
3,"""Male""",49,33.89,-98.51
4,"""Female""",54,47.61,-122.3

Creamos el `lazyframe` con las variables que utilizaremos para graficar el comportamiento del cliente.

In [109]:
client_df = (
    fraud_data_df
    .with_columns(
        day = pl.col("date").cast(pl.Date),
        hour = pl.col("date").dt.hour(),
        minute = pl.col("date").dt.minute(),
        time_str = pl.col("date").dt.to_string("%H:%M"),
    )
    .filter(unbiased_expr & (pl.col("client_id").is_in(fraudulent_client_list)))
    .with_columns(
        target = label_expr,
        minutes_of_day = (pl.col("hour").cast(pl.Int32) * 60) + pl.col("minute"),
        hover_date_str = pl.col("day").dt.to_string("%A, %d %b %Y"),
        amount_absolute = pl.col("amount").abs(),
        amount_sign = pl.when(pl.col("amount") >= 0).then(pl.lit("Positive")).otherwise(pl.lit("Negative")),
        day_str = pl.col("day").dt.to_string("%Y-%m-%d")
    )
    .select("client_id", "target",
            "day", "day_str", "time_str", "minutes_of_day", "hover_date_str",
            "use_chip", "amount", "amount_absolute" , "amount_sign",
            "mcc_description", 
            "merchant_latitude", "merchant_longitude"
    )   
)

Rows_client = client_df.select(pl.len()).collect().item()
Columns_client = len(client_df.collect_schema().names())

print(f"Rows: {Rows_client}, Columns: {Columns_client}")
client_df.show(5)

Rows: 3077399, Columns: 14

client_id,target,day,day_str,time_str,minutes_of_day,hover_date_str,use_chip,amount,amount_absolute,amount_sign,mcc_description,merchant_latitude,merchant_longitude
i64,str,date,str,str,i32,str,cat,f64,f64,str,str,f64,f64
169,"""Legitimate""",2010-01-01,"""2010-01-01""","""03:08""",188,"""Friday, 01 Jan 2010""","""Swipe Transaction""",11.18,11.18,"""Positive""","""Drinking Places (Alcoholic Bev…",33.9446,-80.3206
1296,"""Legitimate""",2010-01-01,"""2010-01-01""","""07:33""",453,"""Friday, 01 Jan 2010""","""Online Transaction""",24.63,24.63,"""Positive""","""Tolls and Bridge Fees""",null,null
1678,"""Legitimate""",2010-01-01,"""2010-01-01""","""06:16""",376,"""Friday, 01 Jan 2010""","""Swipe Transaction""",6.58,6.58,"""Positive""","""Eating Places and Restaurants""",41.7013,-72.6763
646,"""Legitimate""",2010-01-01,"""2010-01-01""","""00:32""",32,"""Friday, 01 Jan 2010""","""Swipe Transaction""",73.79,73.79,"""Positive""","""Automotive Service Shops""",42.1553,-80.0177
33,"""Legitimate""",2010-01-01,"""2010-01-01""","""04:54""",294,"""Friday, 01 Jan 2010""","""Swipe Transaction""",8.73,8.73,"""Positive""","""Grocery Stores, Supermarkets""",40.7519,-115.5956

Definimos una función para graficar el historial de transacciones de un cliente en el tiempo, donde en el eje X se representa la decha de la transacción en el eje Y la hora del a transacción. Las transacciones fraudulentas están representadas en rojo y las legítimas en azul. La cuantía de la transacción está representada por el tamaño de la burguja, además la cauntía exacta figura en el hover de cada punto. Para identificar las cuantías negativas de las positivas, hemos utilizado los símbolos "X".

In [75]:
def plot_client_behaviour_time(client_ID):
    client_transaction_df = (
        client_df
        .filter(pl.col("client_id") == client_ID)
        .sort("day")
        .drop("day", "mcc_description", "merchant_latitude", "merchant_longitude")
        .collect() 
    )
    
    ordered_days = client_transaction_df["day_str"].unique(maintain_order=True).to_list()
    age = fraudulent_client_df.filter(pl.col("client_id") == client_ID).select("current_age").item()
    gender = fraudulent_client_df.filter(pl.col("client_id") == client_ID).select("gender").item()
    
    client_transaction_fig = px.scatter(
        client_transaction_df,
        x="day_str",        
        y="minutes_of_day",
        size="amount_absolute",
        symbol="amount_sign",     
        symbol_sequence=['circle', 'x'],
        color="target",
        facet_row="use_chip",         
        facet_row_spacing=0.08,       
        height=750, width=850,                
        opacity=0.6,
        category_orders={"target": ["Legitimate", "Fraudulent"],
                         "use_chip": ["Online Transaction", "Swipe Transaction", "Chip Transaction"]},
        custom_data=["hover_date_str", "use_chip", "time_str", "amount", "target"],
        title= (f"<b>Transactions Behaviour:</b> Temporal | "
                f"<b>ClientID:</b> {client_ID} | <b>Gender:</b> {gender} | <b>Age:<b> {age}</b>"),
        labels={"day_str": "Date", "minutes_of_day": "Time"}
    )
    
    client_transaction_fig.update_traces(
        marker=dict(line=dict(color='black', width=0.45)),
        hovertemplate="<b>%{customdata[0]}</b><br>%{customdata[4]}<br>Chip: %{customdata[1]}\
        <br>time: %{customdata[2]}<br>amount: %{customdata[3]}<extra></extra>"
    )
    
    client_transaction_fig.update_layout(
        plot_bgcolor="#F5F5F5", paper_bgcolor="white", 
        width=900, height=900, autosize=False,
        legend=dict(title="", orientation="h", yanchor="top", y=1.05, xanchor="left", x=0.1)
    )
    
    client_transaction_fig.update_xaxes(
        showticklabels=True, tickformat="%A, %d %b %Y", matches="x", tickangle=-45, nticks=12,
        type='category', categoryorder='array', categoryarray=ordered_days,
        showspikes=True, spikemode='across', spikethickness=1, spikedash='dash', spikecolor="#040404",
    
    ) 
    
    client_transaction_fig.update_xaxes(showticklabels=False, row=2)
    client_transaction_fig.update_xaxes(showticklabels=False, row=3)
    
    client_transaction_fig.update_yaxes(
        showgrid=True, gridcolor="#EAEAEA",
        tickvals=[0, 240, 480, 720, 960, 1200, 1439],
        ticktext=["00:00", "04:00", "08:00", "12:00", "16:00", "20:00", "23:59"]
    )
    
    client_transaction_fig.for_each_annotation(lambda a: a.update(
        text=f"<b>{a.text.split('=')[-1]}</b>",
        font=dict(size=14, color="black")
        )
    )
    
    client_transaction_fig.add_vline(x="2011-01-08", line_width=1.5, line_dash="dash")
    client_transaction_fig.add_vline(x="2015-03-30", line_width=1.5, line_dash="dash")
                
    return client_transaction_fig

En este función queremos evaluar los tipos de comercio que habitúa el cliente, para ello hemos adaptado la función anterior, donde el símbolo "X" representa las transacciones fraudulentas. Además establecemos un código de colores en función del tipo de comercio, la leyenda se muestra en el gráfico, debido al gran tamaño se ha incorporado una barra de desplazamiento para localizar los múltiples elementos de esta.

In [46]:
def plot_client_behaviour_mcc(client_ID):
    client_transaction_df = (
        client_df
        .filter(pl.col("client_id") == client_ID)
        .sort("day")
        .drop("day", "merchant_latitude", "merchant_longitude")
        .collect() 
    )
    
    ordered_days = client_transaction_df["day_str"].unique(maintain_order=True).to_list()
    ordered_mcc = sorted(client_transaction_df["mcc_description"].unique().to_list())
    age = fraudulent_client_df.filter(pl.col("client_id") == client_ID).select("current_age").item()
    gender = fraudulent_client_df.filter(pl.col("client_id") == client_ID).select("gender").item()
    
    client_transaction_fig = px.scatter(
        client_transaction_df,
        x="day_str",        
        y="minutes_of_day",
        size="amount_absolute",
        symbol="target",   
        symbol_sequence=['circle', 'x'],
        color="mcc_description",
        facet_row="use_chip",         
        facet_row_spacing=0.08,       
        height=750, width=850,                
        opacity=0.6,
        category_orders={"target": ["Legitimate", "Fraudulent"],
                         "use_chip": ["Online Transaction", "Swipe Transaction", "Chip Transaction"],
                         "mcc_description": ordered_mcc
        },
        custom_data=["hover_date_str", "mcc_description", "time_str", "amount", "target"],
        title= (f"<b>Transactions Behaviour:</b> Merchant Category | "
                f"<b>ClientID:</b> {client_ID} | <b>Gender:</b> {gender} | <b>Age:<b> {age}</b>"),
        labels={"day_str": "", "minutes_of_day": "Time"}
    )
   
    client_transaction_fig.update_traces(
        marker=dict(line=dict(color='black', width=0.45)),
        hovertemplate="<b>%{customdata[0]}</b><br>%{customdata[4]}<br>mcc: %{customdata[1]}\
        <br>time: %{customdata[2]}<br>amount: %{customdata[3]}<extra></extra>"
    )
    
    client_transaction_fig.update_layout(
        plot_bgcolor="#F5F5F5", paper_bgcolor="white", 
        width=900, height=1000, autosize=False,
        legend=dict(
            title="", orientation="h", yanchor="top", y=-0.13, xanchor="left", x=-0.1, 
            maxheight=100, valign="top", traceorder="normal", font=dict(size=8.2)
        ),
        legend_tracegroupgap=1
    )
    
    client_transaction_fig.update_xaxes(
        showticklabels=True, tickformat="%A, %d %b %Y", matches="x", tickangle=-45, nticks=12,
        type='category', categoryorder='array', categoryarray=ordered_days,
        showspikes=True, spikemode='across', spikethickness=1, spikedash='dash', spikecolor="#040404",
    
    ) 
    
    client_transaction_fig.update_xaxes(showticklabels=False, row=2)
    client_transaction_fig.update_xaxes(showticklabels=False, row=3)
    
    client_transaction_fig.update_yaxes(
        showgrid=True, gridcolor="#EAEAEA",
        tickvals=[0, 240, 480, 720, 960, 1200, 1439],
        ticktext=["00:00", "04:00", "08:00", "12:00", "16:00", "20:00", "23:59"]
    )
    
    client_transaction_fig.for_each_annotation(lambda a: a.update(
        text=f"<b>{a.text.split('=')[-1]}</b>",
        font=dict(size=14, color="black")
        )
    )
    
    client_transaction_fig.add_vline(x="2011-01-08", line_width=1.5, line_dash="dash")
    client_transaction_fig.add_vline(x="2015-03-30", line_width=1.5, line_dash="dash")
                
    return client_transaction_fig

In [115]:
def plot_client_behaviour_spatial(client_ID):
    client_transaction_df = (
        client_df
        .filter(pl.col("client_id") == client_ID)
        .select("client_id", "target", "merchant_latitude", "merchant_longitude", 
                "amount", "hover_date_str", "time_str", "mcc_description",
        )    
        .collect() 
    )

    age = fraudulent_client_df.filter(pl.col("client_id") == client_ID).select("current_age").item()
    gender = fraudulent_client_df.filter(pl.col("client_id") == client_ID).select("gender").item()
    client_lat = fraudulent_client_df.filter(pl.col("client_id") == client_ID).select("client_latitude").item()
    client_lon = fraudulent_client_df.filter(pl.col("client_id") == client_ID).select("client_longitude").item()
    
    client_fig_fraud = px.scatter_map(
        client_transaction_df,
        lat="merchant_latitude",     
        lon="merchant_longitude",
        color="target", 
        color_discrete_map={"Fraudulent": "#FF4B4B", "Legitimate": "#00CC96"},
        category_orders={"target": ["Legitimate", "Fraudulent"]},
        custom_data=["hover_date_str", "mcc_description", "time_str", "amount", "target"],
    )

    client_fig_fraud.update_traces(
        marker=dict(size=8),
        hovertemplate="<b>%{customdata[0]}</b><br>%{customdata[4]}<br>mcc: %{customdata[1]}\
            <br>time: %{customdata[2]}<br>amount: %{customdata[3]}<extra></extra>"
    )
    
    client_fig_fraud.add_trace(
        go.Scattermap(lat=[client_lat], lon=[client_lon], mode="markers", marker=dict(size=15, color="#00BFFF", 
            symbol="circle"), name="Client Residence", hovertemplate="<b>Client Residence</b><extra></extra>"
        )
    )

    client_fig_fraud.update_layout(
        title=(f"<b>Transactions Behaviour:</b> Spatial | "
                f"<b>ClientID:</b> {client_ID} | <b>Gender:</b> {gender} | <b>Age:</b> {age}"),
        title_x=0.02,
        width=900, height=700, autosize=False, 
        margin={"r":15, "t":120, "l":15, "b":15},
        legend=dict(title="", orientation="h", yanchor="top", y=1.06, xanchor="left", x=0.5),
        map=dict(style="carto-darkmatter", center={"lat": client_lat, "lon": client_lon}, zoom=6),
    )
    
    return client_fig_fraud

A continuación representamos el comportamiento transaccional de un cliente aleatorio que ha sido víctima de fraude

In [110]:
plot_client_behaviour_time(fraudulent_client_list[228])

In [111]:
plot_client_behaviour_mcc(fraudulent_client_list[228])

In [117]:
plot_client_behaviour_spatial(fraudulent_client_list[228])

---
<br>

### <span id="FE"></span> **3.7. Ingeniería de Características**

En esta sección procederemos a realizar las transformaciones que consideramos pueden ser útiles para el entrenamiento de un modelo de predección de fraude.

In [23]:
fraud_data_df = (
    pl.scan_parquet(f"{path}/data/bronze/Polars/complete_fraud_data.parquet")
    .select(
        pl.all().exclude([
            "mcc", "per_capita_income", "current_age",
            "card_number", "cvv", "year_pin_last_changed","card_on_dark_web",
            "address", "merchant_id", "merchant_state", "merchant_city", "zip",
            "client_latitude", "client_longitude",
        ])
    )
# Para facilitar las operaciones y la combinación de los diferentes dataframes que crearemos, 
# ordenaremos nuestros datos en función del id del cliente, la tarjeta, la transacción y la fecha 
# en la que está se realizó.
   .sort(["client_id", "card_id", "date", "id"])
# Además crearemos una nueva columna identificadora para separar transacciones que son coincidentes en fecha y hora,
# y que podrían generar conflictos en las funciones de agregación y ventana que generaremos.
    .with_columns(
        row_id = pl.int_range(0, pl.len())
    )
    .with_columns(
        date = pl.col("date") + pl.duration(microseconds=pl.col("row_id"))
    )  
)

fraud_data_df.show(5)

id,date,client_id,card_id,amount,use_chip,errors,merchant_latitude,merchant_longitude,mcc_description,retirement_age,birth_year,birth_month,gender,yearly_income,total_debt,credit_score,num_credit_cards,card_brand,card_type,expires,has_chip,num_cards_issued,credit_limit,acct_open_date,target,row_id
i64,datetime[μs],i64,i64,f64,cat,cat,f64,f64,str,i64,i64,i64,cat,f64,f64,i64,i64,cat,cat,date,bool,i64,f64,date,bool,i64
9097921,2011-02-01 07:12:00,0,1271,81.1,"""Swipe Transaction""",null,43.7719,-70.6396,"""Grocery Stores, Supermarkets""",69,1986,3,"""Male""",59613.0,36199.0,763,4,"""Mastercard""","""Debit""",2021-04-01,true,2,31490.0,2011-02-01,false,0
9099562,2011-02-01 12:30:00.000001,0,1271,55.0,"""Swipe Transaction""",null,43.5835,-70.3457,"""Miscellaneous Food Stores""",69,1986,3,"""Male""",59613.0,36199.0,763,4,"""Mastercard""","""Debit""",2021-04-01,true,2,31490.0,2011-02-01,null,1
9099585,2011-02-01 12:34:00.000002,0,1271,26.33,"""Swipe Transaction""",null,43.5835,-70.3457,"""Miscellaneous Food Stores""",69,1986,3,"""Male""",59613.0,36199.0,763,4,"""Mastercard""","""Debit""",2021-04-01,true,2,31490.0,2011-02-01,null,2
9099695,2011-02-01 12:53:00.000003,0,1271,-55.0,"""Swipe Transaction""",null,43.5835,-70.3457,"""Miscellaneous Food Stores""",69,1986,3,"""Male""",59613.0,36199.0,763,4,"""Mastercard""","""Debit""",2021-04-01,true,2,31490.0,2011-02-01,false,3
9099949,2011-02-01 13:46:00.000004,0,1271,3.2,"""Swipe Transaction""",null,43.5835,-70.3457,"""Grocery Stores, Supermarkets""",69,1986,3,"""Male""",59613.0,36199.0,763,4,"""Mastercard""","""Debit""",2021-04-01,true,2,31490.0,2011-02-01,false,4

In [9]:
(
    fraud_data_df  
    .sort(["client_id", "card_id", "date", "id"]) 
    .sink_parquet(f"{path}/data/silver/Polars/fraud_data.parquet")
)

In [6]:
FE_fraud_data = pl.scan_parquet(f"{path}/data/silver/Polars/fraud_data.parquet")

A continuación haremos las transformaciones que conciernen al tratamiento de datos temporales creando funciones ventana e intervalos de confianza siguiendo la distribución de Von Mises, tal y como se recomienda en el artículo de 
http://dx.doi.org/10.1016/j.eswa.2015.12.030. Nosotros utilizaremos una ventana de 7 días. Normalizaremos los ángulos con los que trabajaremos y aplicamos transformaciones para el cálculo de la media periódica y de la desviación estándar periódica, cuyas fórmulas están indicadas en la metodología.

In [33]:
temporal_features_fraud_data_df = (
    FE_fraud_data
    .select(["id", "client_id", "card_id", "date", "target"])
    .filter(unbiased_w7_expr)
    .with_columns(
        hour = pl.col("date").dt.hour(),
        minute = pl.col("date").dt.minute(),
    )
    .with_columns(
        hour_of_day = (pl.col("hour") + (pl.col("minute") / 60.0)),
        theta = normalize_angle((pl.col("hour") + (pl.col("minute") / 60.0)) * (2 * PI / 24.0))
    )
    .with_columns(
        sin_theta = pl.col("theta").sin(),
        cos_theta = pl.col("theta").cos(),
    )
    # Ordenamos los datos para hacer el rolling
    .sort(["client_id", "card_id", "date"])
    # En esta parte desplazamos los valores de la transacción previa para evitar el data leakage en el
    # cálculo de las métricas de la transacción actual
    .with_columns(
        sin_theta_prev = pl.col("sin_theta").shift(1).over(["client_id", "card_id"]).fill_null(0),
        cos_theta_prev = pl.col("cos_theta").shift(1).over(["client_id", "card_id"]).fill_null(0),
    )     
    # Seleccionamos una ventana de 7 días, como se recomienda en el artículo
    .rolling(index_column="date", period="7d", group_by=["client_id", "card_id"])
    .agg([
        pl.all().last(),
        (pl.len() -1).clip(lower_bound=1).alias("N_7d"),
        pl.col("sin_theta_prev").sum().alias("sum_sin_7d"),
        pl.col("cos_theta_prev").sum().alias("sum_cos_7d"),
    ])
    .filter(unbiased_expr)
    .with_columns(
        day_of_week = pl.col("date").dt.weekday(),
        # El weekend lo definiremos incluyendo los dias Viernes, Sábado y Domingo
        weekend = (pl.col("date").dt.weekday() >= 5),
        # La fórmula utilizada es la que se indica en el artículo
        mu_vM_7d = pl.arctan2("sum_sin_7d", "sum_cos_7d"),
        R_sq_7d = (pl.col("sum_sin_7d") / pl.col("N_7d")).pow(2) + (pl.col("sum_cos_7d") / pl.col("N_7d")).pow(2)
    )
    .with_columns(
        sigma_vM_7d = (1.0 / pl.col("R_sq_7d").clip(lower_bound=1e-6)).clip(lower_bound=1.0).log().sqrt()
    )
    .with_columns(
        SE_7D = pl.col("sigma_vM_7d") / pl.col("N_7d").sqrt()
    ) 
    .with_columns(
        me_90 = calculate_Zt_value("N_7d", 90) * pl.col("SE_7D"),
        me_95 = calculate_Zt_value("N_7d", 95) * pl.col("SE_7D"),
        me_99 = calculate_Zt_value("N_7d", 99) * pl.col("SE_7D"),
    )
    # Creamos los Intervalos de Confianza (90%, 95%, 99%) como se recomiendo en el articulo
    .with_columns(
        ic_lower_vm_90_7d = normalize_angle(pl.col("mu_vM_7d") - pl.col("me_90")),
        ic_upper_vm_90_7d = normalize_angle(pl.col("mu_vM_7d") + pl.col("me_90")),
        ic_lower_vm_95_7d = normalize_angle(pl.col("mu_vM_7d") - pl.col("me_95")),
        ic_upper_vm_95_7d = normalize_angle(pl.col("mu_vM_7d") + pl.col("me_95")),
        ic_lower_vm_99_7d = normalize_angle(pl.col("mu_vM_7d") - pl.col("me_99")),
        ic_upper_vm_99_7d = normalize_angle(pl.col("mu_vM_7d") + pl.col("me_99")),
    )
    # Creamos una etiqueta para indicar si la transacción se encuentra dentro los IC definidos antes
    .with_columns(
        is_time_in_IC_90 = 
            pl.when(pl.col("N_7d") == 1).then(True).otherwise(
                pl.when(pl.col("ic_lower_vm_90_7d") <= pl.col("ic_upper_vm_90_7d"))
                  .then(pl.col("theta").is_between(pl.col("ic_lower_vm_90_7d"), pl.col("ic_upper_vm_90_7d")))
                  .otherwise((pl.col("theta") >= pl.col("ic_lower_vm_90_7d")) | 
                             (pl.col("theta") <= pl.col("ic_upper_vm_90_7d"))
                            )
        ),
        is_time_in_IC_95 = 
            pl.when(pl.col("N_7d") == 1).then(True).otherwise(
                pl.when(pl.col("ic_lower_vm_95_7d") <= pl.col("ic_upper_vm_95_7d"))
                  .then(pl.col("theta").is_between(pl.col("ic_lower_vm_95_7d"), pl.col("ic_upper_vm_95_7d")))
                  .otherwise((pl.col("theta") >= pl.col("ic_lower_vm_95_7d")) | 
                             (pl.col("theta") <= pl.col("ic_upper_vm_95_7d"))
                            )
        ),
        is_time_in_IC_99 = 
            pl.when(pl.col("N_7d") == 1).then(True).otherwise(
                pl.when(pl.col("ic_lower_vm_99_7d") <= pl.col("ic_upper_vm_99_7d"))
                  .then(pl.col("theta").is_between(pl.col("ic_lower_vm_99_7d"), pl.col("ic_upper_vm_99_7d")))
                  .otherwise((pl.col("theta") >= pl.col("ic_lower_vm_99_7d")) | 
                             (pl.col("theta") <= pl.col("ic_upper_vm_99_7d"))
                            )
        ),
    )
    .drop(["target", "hour", "minute", "sin_theta_prev", "cos_theta_prev",
           "sum_sin_7d", "sum_cos_7d", "R_sq_7d", "SE_7D", "me_90", "me_95", "me_99"])
)

temporal_features_fraud_data_df.show(10)

client_id,card_id,date,id,hour_of_day,theta,sin_theta,cos_theta,N_7d,day_of_week,weekend,mu_vM_7d,sigma_vM_7d,ic_lower_vm_90_7d,ic_upper_vm_90_7d,ic_lower_vm_95_7d,ic_upper_vm_95_7d,ic_lower_vm_99_7d,ic_upper_vm_99_7d,is_time_in_IC_90,is_time_in_IC_95,is_time_in_IC_99
i64,i64,datetime[μs],i64,f64,f64,f64,f64,u32,i8,bool,f64,f64,f64,f64,f64,f64,f64,f64,bool,bool,bool
0,1271,2013-07-19 13:23:00.001906,13047138,13.383333,-2.779437,-0.354291,-0.935135,14,5,true,-1.787862,1.140618,-2.327718,-1.248005,-2.446435,-1.129288,-2.706133,-0.869591,false,false,false
0,1271,2013-07-19 20:35:00.001908,13048785,20.583333,-0.894481,-0.779884,0.625923,15,5,true,-1.695244,1.117504,-2.203449,-1.187038,-2.314096,-1.076391,-2.554176,-0.836311,false,false,true
0,1271,2013-07-20 13:18:00.001909,13051758,13.3,-2.801253,-0.333807,-0.942641,14,6,true,-1.780181,1.143653,-2.321474,-1.238888,-2.440507,-1.119855,-2.700896,-0.859466,false,false,false
0,1271,2013-07-23 06:42:00.001911,13063377,6.7,1.754056,0.983255,-0.182236,11,2,false,-2.28379,1.151315,-2.912958,-1.654622,-3.057254,-1.510326,2.899231,-1.183626,false,false,false
0,1271,2013-07-23 14:15:00.001912,13065451,14.25,-2.552544,-0.55557,-0.83147,11,2,false,-2.602641,1.165326,3.043719,-1.965817,2.897667,-1.819764,2.566991,-1.489089,true,true,true
0,1271,2013-07-23 19:16:00.001913,13066587,19.266667,-1.239184,-0.945519,0.325568,12,2,false,-2.595028,1.09661,3.119645,-2.026515,2.991405,-1.898275,2.704971,-1.611841,false,false,false
0,1271,2013-07-23 19:58:00.001914,13066690,19.966667,-1.055924,-0.870356,0.492424,13,2,false,-2.452136,1.130628,-3.011025,-1.893246,-3.135368,-1.768904,2.873207,-1.494294,false,false,false
0,1271,2013-07-24 12:48:00.001916,13069180,12.8,-2.932153,-0.207912,-0.978148,13,3,false,-2.535424,1.218231,-3.137617,-1.93323,3.011592,-1.799254,2.715704,-1.503366,true,true,true
0,1271,2013-07-24 13:18:00.001917,13069336,13.3,-2.801253,-0.333807,-0.942641,14,3,false,-2.5897,1.162566,-3.139945,-2.039456,3.022239,-1.918455,2.757544,-1.65376,true,true,true
0,1271,2013-07-24 19:58:00.001918,13070919,19.966667,-1.055924,-0.870356,0.492424,15,3,false,-2.615617,1.109782,-3.12031,-2.110923,3.052992,-2.00104,2.814571,-1.762619,false,false,false

Verificamos que tras las agregaciones y funciones ventana, mantengamos el mismo número de filas

In [34]:
check_row_id(temporal_features_fraud_data_df)

shape: (1, 2)
 rows     unique_ids
 ---      ---
 u32      u32
 3121274  3121274

Verificamos que tras los cálculos haya valores que no sean infinitos o nulos:

In [35]:
calculate_INF_NULL_NAN(temporal_features_fraud_data_df)

shape: (17, 4)
 COLUMN             INF  NULL  NAN
 ---                ---  ---   ---
 str                u32  u32   u32
 client_id          0    0     0
 card_id            0    0     0
 id                 0    0     0
 hour_of_day        0    0     0
 theta              0    0     0
 sin_theta          0    0     0
 cos_theta          0    0     0
 N_7d               0    0     0
 day_of_week        0    0     0
 mu_vM_7d           0    0     0
 sigma_vM_7d        0    0     0
 ic_lower_vm_90_7d  0    0     0
 ic_upper_vm_90_7d  0    0     0
 ic_lower_vm_95_7d  0    0     0
 ic_upper_vm_95_7d  0    0     0
 ic_lower_vm_99_7d  0    0     0
 ic_upper_vm_99_7d  0    0     0

In [36]:
(
    temporal_features_fraud_data_df
    .sort(["client_id", "card_id", "date", "id"])
    .sink_parquet(f"{path}/data/silver/Polars/temporal_features_fraud_data.parquet")
)

A continuación procedemos a crear características basadas en el historial de las cuantías de dinero movidas. Aquí también usaremos una ventana de 7 días para el cálculo.

In [38]:
amount_features_fraud_data_df = (
    FE_fraud_data
    .select("client_id", "card_id", "date", "id", "target", 
            "amount", "credit_limit", "yearly_income", "total_debt",
           )
    .filter(unbiased_w7_expr)
    .with_columns(
        log_amount = (pl.col("amount").abs() + 1.0).log()
    )
    # Ordenamos los datos para hacer el rolling
    .sort(["client_id", "card_id", "date"])
    # En esta parte desplazamos los valores de la transacción previa para evitar el data leakage en el
    # cálculo de las métricas de la transacción actual    
    .with_columns(
        amount_prev = pl.col("amount").shift(1).over(["client_id", "card_id"]).fill_null(0),
        log_amount_prev = pl.col("log_amount").shift(1).over(["client_id", "card_id"]).fill_null(0),
    )
    # Seleccionamos una ventana de 24 horas
    .rolling(index_column="date", period="1d", group_by=["client_id", "card_id"])
    .agg([
        pl.all().last(),
        pl.col("amount_prev").sum().alias("sum_amount_24h")
    ])
    # Volvemos a ordenar los datos para hacer un segundo rolling
    .sort(["client_id", "card_id", "date"])    
    # Hacemos un segundo rolling seleccionando una ventana de 7 días
    .rolling(index_column="date", period="7d", group_by=["client_id", "card_id"])
    .agg([
        pl.all().last(),
        (pl.len() -1).clip(lower_bound=1).alias("N_7d"),
        pl.col("log_amount_prev").mean().fill_null(0.0).alias("mean_log_amount_7d"),
        pl.col("log_amount_prev").std().fill_null(0.0).alias("stddev_log_amount_7d"),
        pl.col("amount_prev").sum().alias("sum_amount_7d"),
    ])
    .filter(unbiased_expr)
    .with_columns(
        is_refund = (pl.col("amount") < 0.0),
        aceleration_ratio_24h_vs_7d = 
            (pl.col("sum_amount_24h") / pl.col("sum_amount_7d")).fill_null(0.0).fill_nan(0.0),
        ratio_24_credit_limit = 
            (pl.col("sum_amount_24h") / pl.col("credit_limit")).fill_null(0.0).fill_nan(0.0),
        ratio_24_yearly_income = 
            (pl.col("sum_amount_24h") / pl.col("yearly_income")).fill_null(0.0).fill_nan(0.0), 
        ratio_24_total_debt = 
            (pl.col("sum_amount_24h") / pl.col("total_debt")).fill_null(0.0).fill_nan(0.0)
    )
    .with_columns(
        SE_7D = pl.col("stddev_log_amount_7d") / pl.col("N_7d").sqrt()
    )
    .with_columns(
        me_90 = calculate_Zt_value("N_7d", 90) * pl.col("SE_7D"),
        me_95 = calculate_Zt_value("N_7d", 95) * pl.col("SE_7D"),
        me_99 = calculate_Zt_value("N_7d", 99) * pl.col("SE_7D"),
    )    
    # Creamos los Intervalos de Confianza (90%, 95%, 99%)
    .with_columns(
        ic_lower_amt_90_7d = pl.col("mean_log_amount_7d") - pl.col("me_90"),
        ic_upper_amt_90_7d = pl.col("mean_log_amount_7d") + pl.col("me_90"),
        ic_lower_amt_95_7d = pl.col("mean_log_amount_7d") - pl.col("me_95"),
        ic_upper_amt_95_7d = pl.col("mean_log_amount_7d") + pl.col("me_95"),
        ic_lower_amt_99_7d = pl.col("mean_log_amount_7d") - pl.col("me_99"),
        ic_upper_amt_99_7d = pl.col("mean_log_amount_7d") + pl.col("me_99"),
    )
    # Creamos una etiqueta para indicar si la transacción se encuentra dentro los IC definidos antes
    .with_columns(
        is_amt_in_ic_90 = pl.when(pl.col("N_7d") == 1).then(True).otherwise(
            (pl.col("log_amount") >= pl.col("ic_lower_amt_90_7d")) & 
            (pl.col("log_amount") <= pl.col("ic_upper_amt_90_7d"))
        ),
        is_amt_in_ic_95 = pl.when(pl.col("N_7d") == 1).then(True).otherwise(
            (pl.col("log_amount") >= pl.col("ic_lower_amt_95_7d")) & 
            (pl.col("log_amount") <= pl.col("ic_upper_amt_95_7d"))
        ),
        is_amt_in_ic_99 = pl.when(pl.col("N_7d") == 1).then(True).otherwise(
            (pl.col("log_amount") >= pl.col("ic_lower_amt_99_7d")) & 
            (pl.col("log_amount") <= pl.col("ic_upper_amt_99_7d"))
        )
    )
    .drop(["target", "log_amount", "amount_prev", "log_amount_prev", 
           "N_7d", "SE_7D", "me_90", "me_95", "me_99"])
)

amount_features_fraud_data_df.show(10)

client_id,card_id,date,id,amount,credit_limit,yearly_income,total_debt,sum_amount_24h,mean_log_amount_7d,stddev_log_amount_7d,sum_amount_7d,is_refund,aceleration_ratio_24h_vs_7d,ratio_24_credit_limit,ratio_24_yearly_income,ratio_24_total_debt,ic_lower_amt_90_7d,ic_upper_amt_90_7d,ic_lower_amt_95_7d,ic_upper_amt_95_7d,ic_lower_amt_99_7d,ic_upper_amt_99_7d,is_amt_in_ic_90,is_amt_in_ic_95,is_amt_in_ic_99
i64,i64,datetime[μs],i64,f64,f64,f64,f64,f64,f64,f64,f64,bool,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,bool,bool,bool
0,1271,2013-07-19 13:23:00.001906,13047138,42.52,31490.0,59613.0,36199.0,178.57,3.704316,0.847393,637.14,false,0.280268,0.005671,0.002995,0.004933,3.303243,4.105389,3.215046,4.193586,3.02211,4.386522,true,true,true
0,1271,2013-07-19 20:35:00.001908,13048785,37.51,31490.0,59613.0,36199.0,-14.21,3.589914,0.860677,615.63,false,-0.023082,-0.000451,-0.000238,-0.000393,3.198506,3.981323,3.113287,4.066541,2.928383,4.251445,true,true,true
0,1271,2013-07-20 13:18:00.001909,13051758,44.17,31490.0,59613.0,36199.0,23.3,3.6503,0.828995,594.2,false,0.039212,0.00074,0.000391,0.000644,3.257935,4.042665,3.171653,4.128947,2.982906,4.317694,true,true,true
0,1271,2013-07-23 06:42:00.001911,13063377,14.5,31490.0,59613.0,36199.0,91.64,3.844047,0.589087,497.54,false,0.184186,0.00291,0.001537,0.002532,3.522124,4.16597,3.448292,4.239801,3.281131,4.406962,false,false,false
0,1271,2013-07-23 14:15:00.001912,13065451,16.73,31490.0,59613.0,36199.0,61.97,3.72537,0.657981,448.65,false,0.138125,0.001968,0.00104,0.001712,3.365798,4.084942,3.283332,4.167408,3.096622,4.354119,false,false,false
0,1271,2013-07-23 19:16:00.001913,13066587,8.74,31490.0,59613.0,36199.0,78.7,3.659977,0.672646,465.38,false,0.169109,0.002499,0.00132,0.002174,3.311259,4.008695,3.232598,4.087356,3.056903,4.263051,false,false,false
0,1271,2013-07-23 19:58:00.001914,13066690,9.73,31490.0,59613.0,36199.0,87.44,3.561139,0.74459,474.12,false,0.184426,0.002777,0.001467,0.002416,3.193074,3.929203,3.111187,4.01109,2.930339,4.191938,false,false,false
0,1271,2013-07-24 12:48:00.001916,13069180,53.57,31490.0,59613.0,36199.0,195.67,3.575386,0.896589,556.18,false,0.351811,0.006214,0.003282,0.005405,3.132186,4.018586,3.033583,4.117189,2.815817,4.334956,true,true,true
0,1271,2013-07-24 13:18:00.001917,13069336,31.37,31490.0,59613.0,36199.0,249.24,3.603659,0.870886,609.75,false,0.408758,0.007915,0.004181,0.006885,3.191467,4.015852,3.100825,4.106494,2.90254,4.304779,true,true,true
0,1271,2013-07-24 19:58:00.001918,13070919,10.2,31490.0,59613.0,36199.0,240.64,3.595758,0.84195,641.12,false,0.375343,0.007642,0.004037,0.006648,3.212866,3.97865,3.129501,4.062014,2.94862,4.242895,false,false,false

Verificamos que tras las agregaciones y funciones ventana, mantengamos el mismo número de filas

In [39]:
check_row_id(amount_features_fraud_data_df)

shape: (1, 2)
 rows     unique_ids
 ---      ---
 u32      u32
 3121274  3121274

Verificamos que tras los cálculos haya valores que no sean infinitos ni nulos:

In [40]:
calculate_INF_NULL_NAN(amount_features_fraud_data_df)

shape: (21, 4)
 COLUMN                       INF     NULL  NAN
 ---                          ---     ---   ---
 str                          u32     u32   u32
 client_id                    0       0     0
 card_id                      0       0     0
 id                           0       0     0
 amount                       0       0     0
 credit_limit                 0       0     0
 yearly_income                0       0     0
 total_debt                   0       0     0
 sum_amount_24h               0       0     0
 mean_log_amount_7d           0       0     0
 stddev_log_amount_7d         0       0     0
 sum_amount_7d                0       0     0
 aceleration_ratio_24h_vs_7d  6       0     0
 ratio_24_credit_limit        12005   0     0
 ratio_24_yearly_income       0       0     0
 ratio_24_total_debt          164371  0     0
 ic_lower_amt_90_7d           0       0     0
 ic_upper_amt_90_7d           0       0     0
 ic_lower_amt_95_7d           0       0     0
 ic_upper_amt_95_7d           0       0     0
 ic_lower_amt_99_7d           0       0     0
 ic_upper_amt_99_7d           0       0     0

Debido a estos resultados crearemos una etiqueta que indique las filas de la columna que presentan valores infinitos y sustituiremos estos valores por los máximos de la columna para evitar errores en el entrenamiento posterior.

In [41]:
INF_cols = [
    "aceleration_ratio_24h_vs_7d",
    "ratio_24_credit_limit",
    "ratio_24_total_debt",
]

amount_features_fraud_data_df = (
    amount_features_fraud_data_df
    .with_columns(
        [pl.when(pl.col(col).is_infinite()).then(True).otherwise(False).alias(f"{col}_is_inf")
         for col in INF_cols
        ] +
        [pl.when(pl.col(col).is_infinite())
           .then(pl.col(col).filter(~pl.col(col).is_infinite()).max())
           .otherwise(pl.col(col))
         .alias(col)
         for col in INF_cols
        ]
    )
)

In [42]:
(
    amount_features_fraud_data_df
    .sort(["client_id", "card_id", "date", "id"])
    .sink_parquet(f"{path}/data/silver/Polars/amount_features_fraud_data.parquet")
)

A continuación procedemos a crear características basadas en la rapidez con la que se producen las transacciones.

In [44]:
time_diff_features_fraud_data_df = (
    FE_fraud_data
    .select("client_id", "card_id", "date", "id", "target")
    .filter(unbiased_w7_expr)
    # Ordenamos los datos para hacer el shift y después el rolling
    .sort(["client_id", "card_id", "date"])
    # Calculamos los minutos desde la última transacción
    .with_columns(
        time_diff_m = 
            (pl.col("date") - pl.col("date").shift(1).over(["client_id", "card_id"])).dt.total_minutes()
    )
    .with_columns(
        log_time_diff_m = (pl.col("time_diff_m").fill_null(0.0) + 1.0).log()
    )
    # En esta parte desplazamos los valores de la transacción previa para evitar el data leakage en el
    # cálculo de las métricas de la transacción actual  
    .with_columns(
        log_time_diff_m_prev = pl.col("log_time_diff_m").shift(1).over(["client_id", "card_id"]).fill_null(0),
    )    
    # Seleccionamos una ventana de 7 días
    .rolling(index_column="date", period="7d", group_by=["client_id", "card_id"])
    .agg([
        pl.all().last(),
        (pl.len() -1).clip(lower_bound=1).alias("N_7d"),
        pl.col("log_time_diff_m_prev").mean().fill_null(0.0).alias("mean_time_diff_m"),
        pl.col("log_time_diff_m_prev").std().fill_null(0.0).alias("stddev_time_diff_m")
    ])
    .filter(unbiased_expr)
    .with_columns(
        SE_7D = pl.col("stddev_time_diff_m") / pl.col("N_7d").sqrt()
    )
    .with_columns(
        me_90 = calculate_Zt_value("N_7d", 90) * pl.col("SE_7D"),
        me_95 = calculate_Zt_value("N_7d", 95) * pl.col("SE_7D"),
        me_99 = calculate_Zt_value("N_7d", 99) * pl.col("SE_7D"),
    )
    # Creamos los Intervalos de Confianza (90%, 95%, 99%)
    .with_columns(
        ic_lower_tdiffm_90 = pl.col("mean_time_diff_m") - pl.col("me_90"),
        ic_upper_tdiffm_90 = pl.col("mean_time_diff_m") + pl.col("me_90"),
        ic_lower_tdiffm_95 = pl.col("mean_time_diff_m") - pl.col("me_95"),
        ic_upper_tdiffm_95 = pl.col("mean_time_diff_m") + pl.col("me_95"),
        ic_lower_tdiffm_99 = pl.col("mean_time_diff_m") - pl.col("me_99"),
        ic_upper_tdiffm_99 = pl.col("mean_time_diff_m") + pl.col("me_99"),
    )
    # Creamos una etiqueta para indicar si la transacción se encuentra dentro los IC definidos antes
    .with_columns(
        is_tdiffm_in_IC90 = 
            pl.when(pl.col("N_7d") == 1).then(True).otherwise(
                pl.col("log_time_diff_m").is_between(
                    pl.col("ic_lower_tdiffm_90"), pl.col("ic_upper_tdiffm_90"))
        ),
        is_tdiffm_in_IC95 = 
            pl.when(pl.col("N_7d") == 1).then(True).otherwise(
                pl.col("log_time_diff_m").is_between(
                    pl.col("ic_lower_tdiffm_95"), pl.col("ic_upper_tdiffm_95"))
        ),
        is_tdiffm_in_IC99 = 
            pl.when(pl.col("N_7d") == 1).then(True).otherwise(
                pl.col("log_time_diff_m").is_between(
                    pl.col("ic_lower_tdiffm_99"), pl.col("ic_upper_tdiffm_99"))
        )
    )
    .drop(["target", "N_7d", "time_diff_m", "log_time_diff_m_prev", "SE_7D", "me_90", "me_95", "me_99"])
)

time_diff_features_fraud_data_df.show(10)

client_id,card_id,date,id,log_time_diff_m,mean_time_diff_m,stddev_time_diff_m,ic_lower_tdiffm_90,ic_upper_tdiffm_90,ic_lower_tdiffm_95,ic_upper_tdiffm_95,ic_lower_tdiffm_99,ic_upper_tdiffm_99,is_tdiffm_in_IC90,is_tdiffm_in_IC95,is_tdiffm_in_IC99
i64,i64,datetime[μs],i64,f64,f64,f64,f64,f64,f64,f64,f64,f64,bool,bool,bool
0,1271,2013-07-19 13:23:00.001906,13047138,7.248504,5.388894,1.966031,4.458368,6.31942,4.253742,6.524046,3.806112,6.971676,false,false,false
0,1271,2013-07-19 20:35:00.001908,13048785,2.833213,5.665579,1.880844,4.810231,6.520927,4.624002,6.707156,4.21993,7.111228,false,false,false
0,1271,2013-07-20 13:18:00.001909,13051758,6.911747,5.578957,2.02505,4.620497,6.537417,4.409728,6.748186,3.948661,7.209253,false,false,true
0,1271,2013-07-23 06:42:00.001911,13063377,6.957497,5.688408,2.348834,4.404823,6.971993,4.11044,7.266376,3.443929,7.932887,true,true,true
0,1271,2013-07-23 14:15:00.001912,13065451,6.118097,5.653595,2.32453,4.383291,6.923898,4.091954,7.215235,3.43234,7.87485,true,true,true
0,1271,2013-07-23 19:16:00.001913,13066587,5.710427,5.689326,2.229294,4.533599,6.845052,4.2729,7.105751,3.69061,7.688042,true,true,true
0,1271,2013-07-23 19:58:00.001914,13066690,3.7612,5.690833,2.141843,4.632082,6.749584,4.39653,6.985136,3.876313,7.505353,false,false,false
0,1271,2013-07-24 12:48:00.001916,13069180,5.820083,5.488516,2.181103,4.410358,6.566673,4.170488,6.806543,3.640736,7.336296,true,true,true
0,1271,2013-07-24 13:18:00.001917,13069336,3.433987,5.51062,2.103506,4.515027,6.506214,4.296092,6.725149,3.817162,7.204079,false,false,false
0,1271,2013-07-24 19:58:00.001918,13070919,5.993961,5.380831,2.097446,4.426979,6.334683,4.219304,6.542358,3.768697,6.992965,true,true,true

Verificamos que tras las agregaciones y funciones ventana, mantengamos el mismo número de filas

In [46]:
check_row_id(time_diff_features_fraud_data_df)

shape: (1, 2)
 rows     unique_ids
 ---      ---
 u32      u32
 3121274  3121274

Verificamos que tras los cálculos haya valores que no sean infinitos ni nulos:

In [47]:
calculate_INF_NULL_NAN(time_diff_features_fraud_data_df)

shape: (12, 4)
 COLUMN              INF  NULL  NAN
 ---                 ---  ---   ---
 str                 u32  u32   u32
 client_id           0    0     0
 card_id             0    0     0
 id                  0    0     0
 log_time_diff_m     0    0     0
 mean_time_diff_m    0    0     0
 stddev_time_diff_m  0    0     0
 ic_lower_tdiffm_90  0    0     0
 ic_upper_tdiffm_90  0    0     0
 ic_lower_tdiffm_95  0    0     0
 ic_upper_tdiffm_95  0    0     0
 ic_lower_tdiffm_99  0    0     0
 ic_upper_tdiffm_99  0    0     0

In [48]:
(
    time_diff_features_fraud_data_df
    .sort(["client_id", "card_id", "date", "id"])
    .sink_parquet(f"{path}/data/silver/Polars/time_diff_features_fraud_data.parquet")
)

A continuación procedemos a crear características basadas en la distancia de los comercios, para este cálculo usamos la fórmula definida en metodología. Además aprovecharemos el cálculo de estas distancias para calcular la velocidad a la que se desplaza el cliente entre transferencias.

In [56]:
spatial_features_fraud_data_df = (
    FE_fraud_data
    .select("client_id", "card_id", "date", "id", "target", "merchant_latitude", "merchant_longitude")
    .filter(unbiased_w7_expr)
    .with_columns(
        merchant_latitude_rad = pl.col("merchant_latitude").radians(), 
        merchant_longitude_rad = pl.col("merchant_longitude").radians()
    )
    .sort(["client_id", "card_id", "date"])
    #Las transacciones online no tienen coordenadas, para evitar errores las rellenamos con la anterior no nula
    .with_columns(
        pl.col(["merchant_latitude_rad", "merchant_longitude_rad"])
            .forward_fill().backward_fill().over(["client_id", "card_id"])
    )
    # Obtenemos las coordenadas de las transacciones previas
    .with_columns(
        prev_merchant_latitude_rad = pl.col("merchant_latitude_rad").shift(1).over(["client_id", "card_id"]),
        prev_merchant_longitude_rad = pl.col("merchant_longitude_rad").shift(1).over(["client_id", "card_id"]),
        time_diff_s = (
            pl.col("date") - pl.col("date").shift(1).over(["client_id", "card_id"])
        ).dt.total_microseconds()/1_000_000
    )
    .with_columns(
        distance_km = calculate_haversine("merchant_latitude_rad", "merchant_longitude_rad", 
                                       "prev_merchant_latitude_rad", "prev_merchant_longitude_rad").fill_null(0.0),
    )
    .with_columns(
        speed_km_s = (pl.col("distance_km") / pl.col("time_diff_s").clip(lower_bound=0.1)).fill_null(0.0)
    )
    # En esta parte desplazamos los valores de la transacción previa para evitar el data leakage en el
    # cálculo de las métricas de la transacción actual  
    .with_columns(
        speed_km_s_prev = pl.col("speed_km_s").shift(1).over(["client_id", "card_id"]).fill_null(0),
    )    
    .rolling(index_column="date", period="2h", group_by=["client_id", "card_id"])
    .agg([
        pl.all().last(),
        (pl.len() -1).clip(lower_bound=1).alias("N_2h"),
        pl.col("speed_km_s_prev").mean().fill_null(0.0).alias("mean_speed_km_s"),
        pl.col("speed_km_s_prev").std().fill_null(0.0).alias("stddev_speed_km_s")
    ])
    .filter(unbiased_expr)
    .with_columns(
        SE_2h = pl.col("stddev_speed_km_s") / pl.col("N_2h").sqrt()
    )
    .with_columns(
        me_90 = calculate_Zt_value("N_2h", 90) * pl.col("SE_2h"),
        me_95 = calculate_Zt_value("N_2h", 95) * pl.col("SE_2h"),
        me_99 = calculate_Zt_value("N_2h", 99) * pl.col("SE_2h"),
    )
    # Creamos los Intervalos de Confianza (90%, 95%, 99%)
    .with_columns(
        ic_lower_speed_90 = pl.col("mean_speed_km_s") - pl.col("me_90"),
        ic_upper_speed_90 = pl.col("mean_speed_km_s") + pl.col("me_90"),
        ic_lower_speed_95 = pl.col("mean_speed_km_s") - pl.col("me_95"),
        ic_upper_speed_95 = pl.col("mean_speed_km_s") + pl.col("me_95"),
        ic_lower_speed_99 = pl.col("mean_speed_km_s") - pl.col("me_99"),
        ic_upper_speed_99 = pl.col("mean_speed_km_s") + pl.col("me_99"),
    )
    # Creamos una etiqueta para indicar si la transacción se encuentra dentro los IC definidos antes
    .with_columns(
        is_tdiffm_in_IC90 = 
            pl.when(pl.col("N_2h") == 1).then(True).otherwise(
                pl.col("speed_km_s").is_between(
                    pl.col("ic_lower_speed_90"), pl.col("ic_upper_speed_90"))
        ),
        is_tdiffm_in_IC95 = 
            pl.when(pl.col("N_2h") == 1).then(True).otherwise(
                pl.col("speed_km_s").is_between(
                    pl.col("ic_lower_speed_95"), pl.col("ic_upper_speed_95"))
        ),
        is_tdiffm_in_IC99 = 
            pl.when(pl.col("N_2h") == 1).then(True).otherwise(
                pl.col("speed_km_s").is_between(
                    pl.col("ic_lower_speed_99"), pl.col("ic_upper_speed_99"))
        )
    )
    .drop(["prev_merchant_latitude_rad", "prev_merchant_longitude_rad", 
           "merchant_latitude_rad", "merchant_longitude_rad", 
           "time_diff_s", "speed_km_s_prev", "SE_2h", "me_90", "me_95", "me_99", "target",
          ])
)

spatial_features_fraud_data_df.show(10)

client_id,card_id,date,id,merchant_latitude,merchant_longitude,distance_km,speed_km_s,N_2h,mean_speed_km_s,stddev_speed_km_s,ic_lower_speed_90,ic_upper_speed_90,ic_lower_speed_95,ic_upper_speed_95,ic_lower_speed_99,ic_upper_speed_99,is_tdiffm_in_IC90,is_tdiffm_in_IC95,is_tdiffm_in_IC99
i64,i64,datetime[μs],i64,f64,f64,f64,f64,u32,f64,f64,f64,f64,f64,f64,f64,f64,bool,bool,bool
0,1271,2013-07-19 13:23:00.001906,13047138,44.6653,-70.1329,143.23463,0.001699,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,true,true,true
0,1271,2013-07-19 20:35:00.001908,13048785,43.5835,-70.3457,0.0,0.0,1,0.003283,0.00224,0.003283,0.003283,0.003283,0.003283,0.003283,0.003283,true,true,true
0,1271,2013-07-20 13:18:00.001909,13051758,44.8242,-68.7918,185.398039,0.003081,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,true,true,true
0,1271,2013-07-23 06:42:00.001911,13063377,43.5835,-70.3457,11.059665,0.000176,1,0.001011,0.0,0.001011,0.001011,0.001011,0.001011,0.001011,0.001011,true,true,true
0,1271,2013-07-23 14:15:00.001912,13065451,null,null,0.0,0.0,1,0.000176,0.0,0.000176,0.000176,0.000176,0.000176,0.000176,0.000176,true,true,true
0,1271,2013-07-23 19:16:00.001913,13066587,43.5835,-70.3457,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,true,true,true
0,1271,2013-07-23 19:58:00.001914,13066690,43.5835,-70.3457,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,true,true,true
0,1271,2013-07-24 12:48:00.001916,13069180,43.4715,-70.8064,0.0,0.0,1,0.000969,0.0,0.000969,0.000969,0.000969,0.000969,0.000969,0.000969,true,true,true
0,1271,2013-07-24 13:18:00.001917,13069336,43.5835,-70.3457,39.174471,0.021764,1,0.000484,0.000685,0.000484,0.000484,0.000484,0.000484,0.000484,0.000484,true,true,true
0,1271,2013-07-24 19:58:00.001918,13070919,43.5835,-70.3457,0.0,0.0,1,0.021764,0.0,0.021764,0.021764,0.021764,0.021764,0.021764,0.021764,true,true,true

Verificamos que tras las agregaciones y funciones ventana, mantengamos el mismo número de filas

In [57]:
check_row_id(spatial_features_fraud_data_df)

shape: (1, 2)
 rows     unique_ids
 ---      ---
 u32      u32
 3121274  3121274

Verificamos que tras los cálculos haya valores que no sean infinitos ni nulos:

In [58]:
calculate_INF_NULL_NAN(spatial_features_fraud_data_df)

shape: (16, 4)
 COLUMN              INF  NULL    NAN
 ---                 ---  ---     ---
 str                 u32  u32     u32
 client_id           0    0       0
 card_id             0    0       0
 id                  0    0       0
 merchant_latitude   0    372516  0
 merchant_longitude  0    372516  0
 distance_km         0    0       0
 speed_km_s          0    0       0
 N_2h                0    0       0
 mean_speed_km_s     0    0       0
 stddev_speed_km_s   0    0       0
 ic_lower_speed_90   0    0       0
 ic_upper_speed_90   0    0       0
 ic_lower_speed_95   0    0       0
 ic_upper_speed_95   0    0       0
 ic_lower_speed_99   0    0       0
 ic_upper_speed_99   0    0       0

Los nulos que observamos en `merchant_latitude` y `merchant_longitude` son valores que esperabamos debido a la falta de coordenadas para los comercios de transacciones online.

In [59]:
(
    spatial_features_fraud_data_df
    .sort(["client_id", "card_id", "date", "id"])
    .sink_parquet(f"{path}/data/silver/Polars/spatial_features_fraud_data.parquet")
)

En esta sección calcularemos la frecuencia con la que un cliente consume en un tipo de comercio, y la frecuencia de fraude de ese tipo de comercio, expresado con el parámetro Log2RiskFactor, descrito anteriormente. Estos cálculos lo haremos utilando un `.rolling` de 28 días. Dado que estos cálculos los haremos en función de si una transacción es legítima o fraudulenta, no aplicaremos una ventana de 28 días para filtrar previamente, ya que los valores nulos meterán ruido a los cálculos. Por tanto aplicamos directamente el filtro final de sesgo (`unbiased_expr`).

In [60]:
Metrics_OHE_fraud_data_df = (
    FE_fraud_data
    .select("client_id", "card_id", "date", "id", "target",
            "birth_year", "birth_month", "retirement_age", "acct_open_date", "expires",
            "errors", "card_brand", "card_type", "use_chip", "gender",
            "mcc_description",
    )
    .filter(unbiased_expr)
    # Para analizar el comportamiento de  compras crearemos un rolling de 28 días y calcularemos la frecuencia
    # de compra por tipo de comercio
    .rolling(index_column="date", period="28d", group_by=["client_id", "card_id", "mcc_description"])
    .agg([
        pl.all().last(),
        (pl.len() - 1).alias("mcc_count_prev")
    ])
     # Volvemos a ordenar nuestros datos para hacer un segundo rolling
    .sort(["client_id", "card_id", "date", "id"])
    .rolling(index_column="date", period="28d", group_by=["client_id", "card_id"])
    .agg([
        pl.all().last(),
        (pl.len() - 1).clip(lower_bound=1).alias("N_28d")
    ])
    .with_columns(
        mcc_rate = pl.col("mcc_count_prev") / pl.col("N_28d")
    )
    # En esta subsección calcularemos el Log2RiskFactor haciendo un rolling de 28 días
    # Volvemos a ordenar nuestros datos para hacer un tercer rolling ahora por fecha, ya que ahora 
    # no tendremos en cuenta el comportamiento del cliente sino el historial de todos los fraudes 
    .sort("date")
    .with_columns(
        Fraudulent = pl.when(pl.col("target")).then(1).otherwise(0),
        Legitimate = pl.when(~pl.col("target")).then(1).otherwise(0)
    )
    .with_columns(
        mcc_Fraudulent_prev = pl.col("Fraudulent").shift(1).over("mcc_description").fill_null(0),
        mcc_Legitimate_prev = pl.col("Legitimate").shift(1).over("mcc_description").fill_null(0),
    )
    .rolling(index_column="date", period="28d", group_by="mcc_description")
    .agg([
        pl.all().last(),
        pl.col("mcc_Fraudulent_prev").sum().fill_null(0).alias("mcc_fraud_prev"),
        pl.col("mcc_Legitimate_prev").sum().fill_null(0).alias("mcc_leg_prev"),
    ])
    .sort("date")
    .with_columns(
        Fraudulent_prev = pl.col("Fraudulent").shift(1).fill_null(0),
        Legitimate_prev = pl.col("Legitimate").shift(1).fill_null(0),
    )
    .rolling(index_column="date", period="28d")        
    .agg([
        pl.all().last(),
        pl.col("Fraudulent_prev").sum().fill_null(0).alias("total_fraud_prev"),
        pl.col("Legitimate_prev").sum().fill_null(0).alias("total_leg_prev")
    ])
    .with_columns(
        mcc_fraud_rate = pl.col("mcc_fraud_prev") / (pl.col("mcc_leg_prev") + 1),
        total_fraud_rate = pl.col("total_fraud_prev") / (pl.col("total_leg_prev") + 1)
    )
    .with_columns(
        mcc_risk_factor = pl.col("mcc_fraud_rate") / (pl.col("total_fraud_rate") + 0.00001)
    )
    .with_columns(
        Log2_risk_factor = (pl.col("mcc_risk_factor") + 0.00001).log(base=2).round(2)
    )
    
    # A continuación dejamos de trabajar con las métricas de los tipos de comercio y procedemos
    # a seguir con el resto de las variables
    .with_columns(
        pl.col("errors").cast(pl.String),
        pl.col("card_brand").cast(pl.String),
        pl.col("card_type").cast(pl.String),
        pl.col("use_chip").cast(pl.String),
        pl.col("gender").cast(pl.String),
        # En esta seccion nos dedicamos a calcular las últimas métricas temporales
        agemonth_at_event = (
            (pl.col("date").dt.year() - pl.col("birth_year")) * 12 +
            (pl.col("date").dt.month() - pl.col("birth_month"))
        ),
        days_acct_open = (pl.col("date") - pl.col("acct_open_date")).dt.total_days(),
        days_expires = (pl.col("expires") - pl.col("date")).dt.total_days()
    )
    .with_columns(
        retirement_month = pl.col("retirement_age") * 12 - pl.col("agemonth_at_event")    
    )
    # En esta seccion hacemos One Hot Encoding para el género, el tipo de transacción 
    # los errores, la marca y tipo de tarjeta
    .with_columns(
        No_Errors = pl.col("errors").is_null(),
        Bad_Card_Number = pl.col("errors").str.contains("Bad Card Number", literal=True).fill_null(False),
        Bad_CVV = pl.col("errors").str.contains("Bad CVV", literal=True).fill_null(False),
        Bad_Expiration = pl.col("errors").str.contains("Bad Expiration", literal=True).fill_null(False),
        Bad_PIN = pl.col("errors").str.contains("Bad PIN", literal=True).fill_null(False),
        Bad_Zipcode = pl.col("errors").str.contains("Bad Zipcode", literal=True).fill_null(False),
        Insufficient_Balance  = pl.col("errors").str.contains("Insufficient Balance ", literal=True).fill_null(False),
        Technical_Glitch = pl.col("errors").str.contains("Technical Glitch", literal=True).fill_null(False),

        Visa = pl.col("card_brand").str.contains("Visa", literal=True).fill_null(False),
        Discover = pl.col("card_brand").str.contains("Discover", literal=True).fill_null(False),
        Amex = pl.col("card_brand").str.contains("Amex", literal=True).fill_null(False),
        Mastercard = pl.col("card_brand").str.contains("Mastercard", literal=True).fill_null(False),

        Debit_Prepaid = pl.col("card_type").str.contains("Debit (Prepaid)", literal=True).fill_null(False),
        Credit = pl.col("card_type").str.contains("Credit", literal=True).fill_null(False),
        Debit = pl.col("card_type").str.contains("Debit", literal=True).fill_null(False),

        Online_Transaction = pl.col("use_chip").str.contains("Online Transaction", literal=True).fill_null(False),
        Chip_Transaction = pl.col("use_chip").str.contains("Chip Transaction", literal=True).fill_null(False),
        Swipe_Transaction = pl.col("use_chip").str.contains("Swipe Transaction", literal=True).fill_null(False),

        Male = pl.col("gender").str.contains("Male", literal=True),  
    )
    .sort(["client_id", "card_id", "date", "id"])        
    .drop([
        "errors", "card_brand", "card_type", "use_chip", "gender", "birth_year", "birth_month", "retirement_age",
        "acct_open_date", "expires", "mcc_description", 
        "N_28d", "mcc_risk_factor", "mcc_count_prev", "Fraudulent", "Legitimate", 
        "mcc_Fraudulent_prev", "mcc_Legitimate_prev", "mcc_fraud_prev", "mcc_leg_prev", 
        "Fraudulent_prev", "Legitimate_prev", "total_fraud_prev", "total_leg_prev", "mcc_fraud_rate", "total_fraud_rate", 
    ])    
)

Metrics_OHE_fraud_data_df.show(10)

date,client_id,card_id,id,target,mcc_rate,Log2_risk_factor,agemonth_at_event,days_acct_open,days_expires,retirement_month,No_Errors,Bad_Card_Number,Bad_CVV,Bad_Expiration,Bad_PIN,Bad_Zipcode,Insufficient_Balance,Technical_Glitch,Visa,Discover,Amex,Mastercard,Debit_Prepaid,Credit,Debit,Online_Transaction,Chip_Transaction,Swipe_Transaction,Male
datetime[μs],i64,i64,i64,bool,f64,f64,i64,i64,i64,i64,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool
2013-07-19 13:23:00.001906,0,1271,13047138,false,0.0,-16.61,328,899,2812,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true
2013-07-19 20:35:00.001908,0,1271,13048785,false,0.0,-16.61,328,899,2812,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true
2013-07-20 13:18:00.001909,0,1271,13051758,false,0.0,-16.61,328,900,2811,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true
2013-07-23 06:42:00.001911,0,1271,13063377,false,0.0,-16.61,328,903,2808,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true
2013-07-23 14:15:00.001912,0,1271,13065451,false,0.0,-16.61,328,903,2808,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,true,false,false,true
2013-07-23 19:16:00.001913,0,1271,13066587,false,0.2,-16.61,328,903,2808,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true
2013-07-23 19:58:00.001914,0,1271,13066690,false,0.333333,-16.61,328,903,2808,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true
2013-07-24 12:48:00.001916,0,1271,13069180,false,0.0,2.4,328,904,2807,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true
2013-07-24 13:18:00.001917,0,1271,13069336,false,0.0,1.72,328,904,2807,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true
2013-07-24 19:58:00.001918,0,1271,13070919,false,0.333333,-16.61,328,904,2807,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true

In [61]:
row_id_check(Metrics_OHE_fraud_data_df)

shape: (1, 2)
 rows     unique_ids
 ---      ---
 u32      u32
 3121274  3121274

Verificamos que tras los cálculos haya valores que no sean infinitos ni nulos:

In [62]:
calculate_INF_NULL_NAN(Metrics_OHE_fraud_data_df)

shape: (9, 4)
 COLUMN             INF  NULL  NAN
 ---                ---  ---   ---
 str                u32  u32   u32
 client_id          0    0     0
 card_id            0    0     0
 id                 0    0     0
 mcc_rate           0    0     0
 Log2_risk_factor   0    0     0
 agemonth_at_event  0    0     0
 days_acct_open     0    0     0
 days_expires       0    0     0
 retirement_month   0    0     0

In [32]:
(
    Metrics_OHE_fraud_data_df
    .sort(["client_id", "card_id", "date", "id"])
    .sink_parquet(f"{path}/data/silver/Polars/Metrics_OHE_fraud_data.parquet")
)

A continuación procedemos a realizar los `.join` de los dataframes que hemos generado en uno solo para usarlo como `input` en el entrenamiento del modelo.

In [63]:
Metrics_OHE_fraud_data_df = pl.scan_parquet(f"{path}/data/silver/Polars/Metrics_OHE_fraud_data.parquet")
amount_features_fraud_data_df = pl.scan_parquet(f"{path}/data/silver/Polars/amount_features_fraud_data.parquet")
spatial_features_fraud_data_df = pl.scan_parquet(f"{path}/data/silver/Polars/spatial_features_fraud_data.parquet")
temporal_features_fraud_data_df = pl.scan_parquet(f"{path}/data/silver/Polars/temporal_features_fraud_data.parquet")
time_diff_features_fraud_data_df = pl.scan_parquet(f"{path}/data/silver/Polars/time_diff_features_fraud_data.parquet")

feature_complete_fraud_data_df = (
    Metrics_OHE_fraud_data_df
    .join(amount_features_fraud_data_df, on=["client_id", "card_id", "date", "id"], how="left")
    .join(spatial_features_fraud_data_df, on=["client_id", "card_id", "date", "id"], how="left")
    .join(temporal_features_fraud_data_df, on=["client_id", "card_id", "date", "id"], how="left")
    .join(time_diff_features_fraud_data_df, on=["client_id", "card_id", "date", "id"], how="left")
)

feature_complete_fraud_data_df.show(5)

date,client_id,card_id,id,target,mcc_rate,Log2_risk_factor,agemonth_at_event,days_acct_open,days_expires,retirement_month,No_Errors,Bad_Card_Number,Bad_CVV,Bad_Expiration,Bad_PIN,Bad_Zipcode,Insufficient_Balance,Technical_Glitch,Visa,Discover,Amex,Mastercard,Debit_Prepaid,Credit,Debit,Online_Transaction,Chip_Transaction,Swipe_Transaction,Male,amount,credit_limit,yearly_income,total_debt,sum_amount_24h,mean_log_amount_7d,stddev_log_amount_7d,…,ic_lower_speed_95,ic_upper_speed_95,ic_lower_speed_99,ic_upper_speed_99,is_tdiffm_in_IC90,is_tdiffm_in_IC95,is_tdiffm_in_IC99,hour_of_day,theta,sin_theta,cos_theta,N_7d,day_of_week,weekend,mu_vM_7d,sigma_vM_7d,ic_lower_vm_90_7d,ic_upper_vm_90_7d,ic_lower_vm_95_7d,ic_upper_vm_95_7d,ic_lower_vm_99_7d,ic_upper_vm_99_7d,is_time_in_IC_90,is_time_in_IC_95,is_time_in_IC_99,log_time_diff_m,mean_time_diff_m,stddev_time_diff_m,ic_lower_tdiffm_90,ic_upper_tdiffm_90,ic_lower_tdiffm_95,ic_upper_tdiffm_95,ic_lower_tdiffm_99,ic_upper_tdiffm_99,is_tdiffm_in_IC90_right,is_tdiffm_in_IC95_right,is_tdiffm_in_IC99_right
datetime[μs],i64,i64,i64,bool,f64,f64,i64,i64,i64,i64,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,f64,f64,f64,f64,f64,f64,f64,…,f64,f64,f64,f64,bool,bool,bool,f64,f64,f64,f64,u32,i8,bool,f64,f64,f64,f64,f64,f64,f64,f64,bool,bool,bool,f64,f64,f64,f64,f64,f64,f64,f64,f64,bool,bool,bool
2013-07-19 13:23:00.001906,0,1271,13047138,false,0.0,-16.61,328,899,2812,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true,42.52,31490.0,59613.0,36199.0,178.57,3.704316,0.847393,…,0.0,0.0,0.0,0.0,true,true,true,13.383333,-2.779437,-0.354291,-0.935135,14,5,true,-1.787862,1.140618,-2.327718,-1.248005,-2.446435,-1.129288,-2.706133,-0.869591,false,false,false,7.248504,5.388894,1.966031,4.458368,6.31942,4.253742,6.524046,3.806112,6.971676,false,false,false
2013-07-19 20:35:00.001908,0,1271,13048785,false,0.0,-16.61,328,899,2812,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true,37.51,31490.0,59613.0,36199.0,-14.21,3.589914,0.860677,…,0.003283,0.003283,0.003283,0.003283,true,true,true,20.583333,-0.894481,-0.779884,0.625923,15,5,true,-1.695244,1.117504,-2.203449,-1.187038,-2.314096,-1.076391,-2.554176,-0.836311,false,false,true,2.833213,5.665579,1.880844,4.810231,6.520927,4.624002,6.707156,4.21993,7.111228,false,false,false
2013-07-23 06:42:00.001911,0,1271,13063377,false,0.0,-16.61,328,903,2808,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true,14.5,31490.0,59613.0,36199.0,91.64,3.844047,0.589087,…,0.001011,0.001011,0.001011,0.001011,true,true,true,6.7,1.754056,0.983255,-0.182236,11,2,false,-2.28379,1.151315,-2.912958,-1.654622,-3.057254,-1.510326,2.899231,-1.183626,false,false,false,6.957497,5.688408,2.348834,4.404823,6.971993,4.11044,7.266376,3.443929,7.932887,true,true,true
2013-07-20 13:18:00.001909,0,1271,13051758,false,0.0,-16.61,328,900,2811,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true,44.17,31490.0,59613.0,36199.0,23.3,3.6503,0.828995,…,0.0,0.0,0.0,0.0,true,true,true,13.3,-2.801253,-0.333807,-0.942641,14,6,true,-1.780181,1.143653,-2.321474,-1.238888,-2.440507,-1.119855,-2.700896,-0.859466,false,false,false,6.911747,5.578957,2.02505,4.620497,6.537417,4.409728,6.748186,3.948661,7.209253,false,false,true
2013-07-23 14:15:00.001912,0,1271,13065451,false,0.0,-16.61,328,903,2808,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,true,false,false,true,16.73,31490.0,59613.0,36199.0,61.97,3.72537,0.657981,…,0.000176,0.000176,0.000176,0.000176,true,true,true,14.25,-2.552544,-0.55557,-0.83147,11,2,false,-2.602641,1.165326,3.043719,-1.965817,2.897667,-1.819764,2.566991,-1.489089,true,true,true,6.118097,5.653595,2.32453,4.383291,6.923898,4.091954,7.215235,3.43234,7.87485,true,true,true

Verificamos que tras los `.join` mantengamos el mismo número de columnas y de ids.

In [65]:
check_row_id(feature_complete_fraud_data_df)

shape: (1, 2)
 rows     unique_ids
 ---      ---
 u32      u32
 3121274  3121274

Verificamos que tras los `.join` haya valores que no sean infinitos ni nulos:

In [66]:
calculate_INF_NULL_NAN(feature_complete_fraud_data_df)

shape: (63, 4)
 COLUMN                       INF  NULL    NAN
 ---                          ---  ---     ---
 str                          u32  u32     u32
 client_id                    0    0       0
 card_id                      0    0       0
 id                           0    0       0
 mcc_rate                     0    0       0
 Log2_risk_factor             0    0       0
 agemonth_at_event            0    0       0
 days_acct_open               0    0       0
 days_expires                 0    0       0
 retirement_month             0    0       0
 amount                       0    0       0
 credit_limit                 0    0       0
 yearly_income                0    0       0
 total_debt                   0    0       0
 sum_amount_24h               0    0       0
 mean_log_amount_7d           0    0       0
 stddev_log_amount_7d         0    0       0
 sum_amount_7d                0    0       0
 aceleration_ratio_24h_vs_7d  0    0       0
 ratio_24_credit_limit        0    0       0
 ratio_24_yearly_income       0    0       0
 ratio_24_total_debt          0    0       0
 ic_lower_amt_90_7d           0    0       0
 ic_upper_amt_90_7d           0    0       0
 ic_lower_amt_95_7d           0    0       0
 ic_upper_amt_95_7d           0    0       0
 ic_lower_amt_99_7d           0    0       0
 ic_upper_amt_99_7d           0    0       0
 merchant_latitude            0    372516  0
 merchant_longitude           0    372516  0
 distance_km                  0    0       0
 speed_km_s                   0    0       0
 N_2h                         0    0       0
 mean_speed_km_s              0    0       0
 stddev_speed_km_s            0    0       0
 ic_lower_speed_90            0    0       0
 ic_upper_speed_90            0    0       0
 ic_lower_speed_95            0    0       0
 ic_upper_speed_95            0    0       0
 ic_lower_speed_99            0    0       0
 ic_upper_speed_99            0    0       0
 hour_of_day                  0    0       0
 theta                        0    0       0
 sin_theta                    0    0       0
 cos_theta                    0    0       0
 N_7d                         0    0       0
 day_of_week                  0    0       0
 mu_vM_7d                     0    0       0
 sigma_vM_7d                  0    0       0
 ic_lower_vm_90_7d            0    0       0
 ic_upper_vm_90_7d            0    0       0
 ic_lower_vm_95_7d            0    0       0
 ic_upper_vm_95_7d            0    0       0
 ic_lower_vm_99_7d            0    0       0
 ic_upper_vm_99_7d            0    0       0
 log_time_diff_m              0    0       0
 mean_time_diff_m             0    0       0
 stddev_time_diff_m           0    0       0
 ic_lower_tdiffm_90           0    0       0
 ic_upper_tdiffm_90           0    0       0
 ic_lower_tdiffm_95           0    0       0
 ic_upper_tdiffm_95           0    0       0
 ic_lower_tdiffm_99           0    0       0
 ic_upper_tdiffm_99           0    0       0

In [67]:
(
    feature_complete_fraud_data_df
    .sort(["client_id", "card_id", "date", "id"])
    .sink_parquet(f"{path}/data/gold/Polars/feature_complete_fraud_data.parquet")
)

---

### <span id="ML"></span> **3.8. Modelado por Machine Learning**

En esta sección se presenta el proceso de entrenamiento y evaluación de los modelos de aprendizaje automático empleados para la clasificación de las transacciones. Para ello, se utilizarán los siguientes algoritmos: 
- Random Forest
- XGBoost
- LightGBM

Cargamos nuestro archivo que creamos en el apartado anterior con todas las características generadas:

In [9]:
features_df = (
    pl.scan_parquet(f"{path}/data/gold/Polars/feature_complete_fraud_data.parquet")
    .select(pl.all().exclude("client_id", "card_id", "date", 
                             # "id", 
                             "merchant_latitude", "merchant_longitude"
                            ))
)

features_df.show(5)

id,target,mcc_rate,Log2_risk_factor,agemonth_at_event,days_acct_open,days_expires,retirement_month,No_Errors,Bad_Card_Number,Bad_CVV,Bad_Expiration,Bad_PIN,Bad_Zipcode,Insufficient_Balance,Technical_Glitch,Visa,Discover,Amex,Mastercard,Debit_Prepaid,Credit,Debit,Online_Transaction,Chip_Transaction,Swipe_Transaction,Male,amount,credit_limit,yearly_income,total_debt,sum_amount_24h,mean_log_amount_7d,stddev_log_amount_7d,sum_amount_7d,is_refund,aceleration_ratio_24h_vs_7d,…,ic_lower_speed_95,ic_upper_speed_95,ic_lower_speed_99,ic_upper_speed_99,is_tdiffm_in_IC90,is_tdiffm_in_IC95,is_tdiffm_in_IC99,hour_of_day,theta,sin_theta,cos_theta,N_7d,day_of_week,weekend,mu_vM_7d,sigma_vM_7d,ic_lower_vm_90_7d,ic_upper_vm_90_7d,ic_lower_vm_95_7d,ic_upper_vm_95_7d,ic_lower_vm_99_7d,ic_upper_vm_99_7d,is_time_in_IC_90,is_time_in_IC_95,is_time_in_IC_99,log_time_diff_m,mean_time_diff_m,stddev_time_diff_m,ic_lower_tdiffm_90,ic_upper_tdiffm_90,ic_lower_tdiffm_95,ic_upper_tdiffm_95,ic_lower_tdiffm_99,ic_upper_tdiffm_99,is_tdiffm_in_IC90_right,is_tdiffm_in_IC95_right,is_tdiffm_in_IC99_right
i64,bool,f64,f64,i64,i64,i64,i64,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,f64,f64,f64,f64,f64,f64,f64,f64,bool,f64,…,f64,f64,f64,f64,bool,bool,bool,f64,f64,f64,f64,u32,i8,bool,f64,f64,f64,f64,f64,f64,f64,f64,bool,bool,bool,f64,f64,f64,f64,f64,f64,f64,f64,f64,bool,bool,bool
13047138,false,0.0,-16.61,328,899,2812,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true,42.52,31490.0,59613.0,36199.0,178.57,3.704316,0.847393,637.14,false,0.280268,…,0.0,0.0,0.0,0.0,true,true,true,13.383333,-2.779437,-0.354291,-0.935135,14,5,true,-1.787862,1.140618,-2.327718,-1.248005,-2.446435,-1.129288,-2.706133,-0.869591,false,false,false,7.248504,5.388894,1.966031,4.458368,6.31942,4.253742,6.524046,3.806112,6.971676,false,false,false
13048785,false,0.0,-16.61,328,899,2812,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true,37.51,31490.0,59613.0,36199.0,-14.21,3.589914,0.860677,615.63,false,-0.023082,…,0.003283,0.003283,0.003283,0.003283,true,true,true,20.583333,-0.894481,-0.779884,0.625923,15,5,true,-1.695244,1.117504,-2.203449,-1.187038,-2.314096,-1.076391,-2.554176,-0.836311,false,false,true,2.833213,5.665579,1.880844,4.810231,6.520927,4.624002,6.707156,4.21993,7.111228,false,false,false
13051758,false,0.0,-16.61,328,900,2811,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true,44.17,31490.0,59613.0,36199.0,23.3,3.6503,0.828995,594.2,false,0.039212,…,0.0,0.0,0.0,0.0,true,true,true,13.3,-2.801253,-0.333807,-0.942641,14,6,true,-1.780181,1.143653,-2.321474,-1.238888,-2.440507,-1.119855,-2.700896,-0.859466,false,false,false,6.911747,5.578957,2.02505,4.620497,6.537417,4.409728,6.748186,3.948661,7.209253,false,false,true
13063377,false,0.0,-16.61,328,903,2808,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true,14.5,31490.0,59613.0,36199.0,91.64,3.844047,0.589087,497.54,false,0.184186,…,0.001011,0.001011,0.001011,0.001011,true,true,true,6.7,1.754056,0.983255,-0.182236,11,2,false,-2.28379,1.151315,-2.912958,-1.654622,-3.057254,-1.510326,2.899231,-1.183626,false,false,false,6.957497,5.688408,2.348834,4.404823,6.971993,4.11044,7.266376,3.443929,7.932887,true,true,true
13065451,false,0.0,-16.61,328,903,2808,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,true,false,false,true,16.73,31490.0,59613.0,36199.0,61.97,3.72537,0.657981,448.65,false,0.138125,…,0.000176,0.000176,0.000176,0.000176,true,true,true,14.25,-2.552544,-0.55557,-0.83147,11,2,false,-2.602641,1.165326,3.043719,-1.965817,2.897667,-1.819764,2.566991,-1.489089,true,true,true,6.118097,5.653595,2.32453,4.383291,6.923898,4.091954,7.215235,3.43234,7.87485,true,true,true

Materializamos nuestro lazyframe, ya que el algoritmo Random Forest solo acepta datos previamente materializados.

In [10]:
df = features_df.collect()

Como se puede observar, existe un marcado desbalance en la variable objetivo (`target`) que se pretende clasificar mediante los modelos de aprendizaje automático. Por lo tanto para la evaluación del modelo haremos ciertos cambios como seleccionar solo una porción de las transacciones legítimas.

In [13]:
proportions = (
    df
    .group_by("target")
    .agg([
        pl.len().alias("cantidad"),
        (pl.len() / len(df) * 100).alias("porcentaje")
    ])
    .with_columns(target = label_expr)
)

proportions

shape: (2, 3)
 target      cantidad  porcentaje
 ---         ---       ---
 str         u32       f64
 Legitimate  3112100   99.706082
 Fraudulent  9174      0.293918

Además debemos tener en cuenta que al haber un alto desbalance en las clases, en la evaluación del modelo, métricas como el `accuracy` no son las adecuadas para la selección del modelo más idóneos para nuestros objetivos, que es la detección de fraude, ya que si el modelo decide clasificar cualquier transacción como legítima, obtendrá un `accuracy` superior al 99%. Es por ello que las métricas que debemos  buscar que optimice el modelo son el `recall` (4), la `precision` (5) y el `F1 Score` (6).  
$$Precision = \frac{TP}{TP + FP}, \tag{4}$$
$$Recall = \frac{TP}{TP + FN}, \tag{5}$$
$$F1\text{-}Score = 2 \cdot \frac{Precision \cdot Recall}{Precision + Recall}. \tag{6}$$

El conjunto de datos se particionó en tres subconjuntos: entrenamiento, validación y prueba, destinados respectivamente al ajuste de los modelos, la selección de hiperparámetros y la evaluación final de su rendimiento.

In [14]:
False_df = df.filter(~pl.col("target"))
False_train_df = False_df.sample(fraction=0.70, seed=777)
False_valtest_df = False_df.join(False_train_df, on="id", how="anti")
False_val_df = False_valtest_df.sample(fraction=0.50, seed=777)
False_test_df = False_valtest_df.join(False_val_df, on="id", how="anti")

True_df = df.filter(pl.col("target"))
True_train_df = True_df.sample(fraction=0.70, seed=777)
True_valtest_df = True_df.join(True_train_df, on="id", how="anti")
True_val_df = True_valtest_df.sample(fraction=0.50, seed=777)
True_test_df = True_valtest_df.join(True_val_df, on="id", how="anti")

## Tomaremos solo 100_000 transaciones legitimas para el entrenamiento ya que hay un alto desbalance entre
## las transacciones legítimas y las fraudulentas
balanced_False_train_df = False_train_df.sample(n=100_000, seed=777)

train_df = pl.concat([balanced_False_train_df, True_train_df]).sample(fraction=1.0, shuffle=True, seed=777)
val_df = pl.concat([False_val_df, True_val_df]).sample(fraction=1.0, shuffle=True, seed=777)
test_df = pl.concat([False_test_df, True_test_df]).sample(fraction=1.0, shuffle=True, seed=777)

## Definimos los datos que usaremos para el entrenamiento, la validación, el testeo del modelo
## y la búsqueda de hiperparámetros
X_train = train_df.drop("target", "id")
y_train = train_df["target"].cast(pl.Int8).to_numpy()

X_val = val_df.drop("target", "id")
y_val = val_df["target"].cast(pl.Int8).to_numpy()

X_test = test_df.drop("target", "id")
y_test = test_df["target"].cast(pl.Int8).to_numpy()

X_search = pl.concat([X_train, X_val])
y_search = np.concatenate((y_train, y_val))

split_indices = np.zeros(len(X_search))
split_indices[:len(X_train)] = -1  
split_indices[len(X_train):] = 0   
pds = PredefinedSplit(test_fold=split_indices)

#### **ALGORITMO RANDOM FOREST**

Como punto de partida, se entrenó un modelo inicial basado en el algoritmo Random Forest. Debido al marcado desbalance existente en la variable objetivo, se utilizó el parámetro `class_weight="balanced`.

In [77]:
rf_0 = RandomForestClassifier(
    n_estimators=100, 
    max_depth=12, 
    class_weight="balanced", 
    random_state=777, 
    n_jobs=-1,
    verbose=0
)

rf_0.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=12, n_jobs=-1,
                       random_state=777)

In [89]:
# En esta sección guardamos el modelo entrenado
joblib.dump(rf_0, f"{path}/mldl/ML_RandomForest_0.pkl");

El modelo se evaluó sobre el conjunto de validación con el objetivo de seleccionar el umbral de clasificación que permitiera maximizar el recall manteniendo un nivel adecuado de precision, de acuerdo con las necesidades del problema de detección de fraude. En este apartado y en los siguientes lo dejamos fijado en 0.45, para que todos los modelos sean lo más comparables.

In [91]:
create_validation_report(rf_0)

-------- VALIDATION REPORT --------
              precision    recall  f1-score   support

           0       1.00      0.97      0.99    466815
           1       0.08      0.87      0.15      1376

    accuracy                           0.97    468191
   macro avg       0.54      0.92      0.57    468191
weighted avg       1.00      0.97      0.98    468191

PR-AUC Score: 0.4965
Average Precision (AP) Score: 0.4966

El modelo se evaluó sobre el conjunto de prueba y se extrajeron las métricas necesarias para su posterior graficación. Como se observa obtenemos un PR-AUC Score de `0.4929`.

In [97]:
precision_rf_0, recall_rf_0, pr_auc_rf_0, ap_rf_0 = create_test_report(rf_0)

----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      0.97      0.99    466815
           1       0.08      0.88      0.15      1377

    accuracy                           0.97    468192
   macro avg       0.54      0.93      0.57    468192
weighted avg       1.00      0.97      0.98    468192

PR-AUC Score: 0.4929
Average Precision (AP) Score: 0.4931

A continuación, se representa la curva Precision-Recall, con el objetivo de analizar el comportamiento del modelo para distintos umbrales de clasificación.

In [98]:
plot_PRAUC(precision_rf_0, recall_rf_0, pr_auc_rf_0, ap_rf_0, "Random Forest", "Model 0", "lightblue")

En esta sección se lleva a cabo una búsqueda de hiperparámetros con el objetivo de identificar la configuración que proporciona el mejor rendimiento del modelo Random Forest, tomando como referencia las métricas de evaluación seleccionadas. Para ello se utiliza la métrica Average Precision (AP) como criterio de optimización durante el proceso de búsqueda.

In [81]:
param_dist = {
    'n_estimators': [100, 300, 500],         
    'max_depth': [12, 16, 20, None],     
    'min_samples_split': [2, 5, 10],        
    'min_samples_leaf': [1, 2, 5],     
    'max_features': ['sqrt', 'log2', 0.3]
}

In [82]:
grid_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(
        class_weight="balanced", 
        random_state=777, 
        n_jobs=1  
    ),
    param_distributions=param_dist,
    n_iter=10,    
    cv=pds,
    scoring="average_precision", 
    verbose=0,  
    n_jobs=2,
    random_state=777
)

grid_search.fit(X_search, y_search)
best_rf_1 = grid_search.best_estimator_

print("--- BEST HYPERPARAMETERS FOUND ---")
print(grid_search.best_params_)

--- BEST HYPERPARAMETERS FOUND ---
{'n_estimators': 300, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2', 'max_depth': None}

El modelo se evaluó sobre el conjunto de prueba, como se observa obtenemos un PR-AUC Score de `0.5737`.

In [100]:
create_test_report(best_rf_1)

----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    466815
           1       0.58      0.52      0.55      1377

    accuracy                           1.00    468192
   macro avg       0.79      0.76      0.77    468192
weighted avg       1.00      1.00      1.00    468192

PR-AUC Score: 0.5737
Average Precision (AP) Score: 0.5738

En esta segunda búsqueda se mantienen fijos algunos de los hiperparámetros del modelo anterior, mientras que se exploran diferentes valores para aquellos parámetros considerados susceptibles de mejorar su rendimiento.

In [101]:
param_dist_rf_1 = {
    'n_estimators': [300],         
    'max_depth': [None],     
    'min_samples_split': [5],        
    'min_samples_leaf': [2],     
    'max_features': ['log2'],
    'bootstrap': [True, False],
    'criterion': ["gini", "entropy"],
}

grid_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(class_weight="balanced", random_state=777, n_jobs=-1),
    param_distributions=param_dist_rf_1,
    n_iter=4,    
    cv=pds,
    scoring="average_precision", 
    verbose=0,  
    n_jobs=1,
    random_state=777
)

grid_search.fit(X_search, y_search)
best_rf_1 = grid_search.best_estimator_

print("--- BEST HYPERPARAMETERS FOUND ---")
print(grid_search.best_params_)

--- BEST HYPERPARAMETERS FOUND ---
{'n_estimators': 300, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2', 'max_depth': None, 'criterion': 'entropy', 'bootstrap': False}

In [103]:
joblib.dump(best_rf_1, f"{path}/mldl/ML_RandomForest_1.pkl");

El modelo se evaluó sobre el conjunto de prueba y se extrajeron las métricas necesarias para su posterior graficación. Como se observa obtenemos un PR-AUC Score de `0.6074`.

In [104]:
precision_rf_1, recall_rf_1, pr_auc_rf_1, ap_rf_1 = create_test_report(best_rf_1)

----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    466815
           1       0.62      0.53      0.57      1377

    accuracy                           1.00    468192
   macro avg       0.81      0.77      0.79    468192
weighted avg       1.00      1.00      1.00    468192

PR-AUC Score: 0.6073
Average Precision (AP) Score: 0.6074

A continuación, se representa la curva Precision-Recall, con el objetivo de analizar el comportamiento del modelo para distintos umbrales de clasificación.

In [105]:
plot_PRAUC(precision_rf_1, recall_rf_1, pr_auc_rf_1, ap_rf_1, "Random Forest", "Model 1", "darkorange")

En esta sección se lleva a cabo una búsqueda de hiperparámetros tomando como criterio de optimización la métrica F1 Score (F1).

In [108]:
grid_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(
        class_weight="balanced", 
        random_state=777, 
        n_jobs=1  
    ),
    param_distributions=param_dist,
    n_iter=10,    
    cv=pds,
    scoring="f1", 
    verbose=0,  
    n_jobs=2,
    random_state=777
)

grid_search.fit(X_search, y_search)
best_rf_2 = grid_search.best_estimator_

print("--- BEST HYPERPARAMETERS FOUND ---")
print(grid_search.best_params_)

--- BEST HYPERPARAMETERS FOUND ---
{'n_estimators': 300, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2', 'max_depth': None}

El modelo se evaluó sobre el conjunto de prueba, como se observa obtenemos un PR-AUC Score de `0.5737`.

In [109]:
create_test_report(best_rf_2)

----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    466815
           1       0.58      0.52      0.55      1377

    accuracy                           1.00    468192
   macro avg       0.79      0.76      0.77    468192
weighted avg       1.00      1.00      1.00    468192

PR-AUC Score: 0.5737
Average Precision (AP) Score: 0.5738

En esta segunda búsqueda se mantienen fijos algunos de los hiperparámetros del modelo anterior, mientras que se exploran diferentes valores para aquellos parámetros considerados susceptibles de mejorar su rendimiento.

In [110]:
param_dist_rf_2 = {
    'n_estimators': [300],         
    'max_depth': [None],     
    'min_samples_split': [5],        
    'min_samples_leaf': [2],     
    'max_features': ['log2'],
    'bootstrap': [True, False],
    'criterion': ["gini", "entropy"],
}

grid_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(class_weight="balanced", random_state=777, n_jobs=-1),
    param_distributions=param_dist_rf_2,
    n_iter=4,    
    cv=pds,
    scoring="f1", 
    verbose=0,  
    n_jobs=1,
    random_state=777
)

grid_search.fit(X_search, y_search)
best_rf_2 = grid_search.best_estimator_

print("--- BEST HYPERPARAMETERS FOUND ---")
print(grid_search.best_params_)

--- BEST HYPERPARAMETERS FOUND ---
{'n_estimators': 300, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2', 'max_depth': None, 'criterion': 'entropy', 'bootstrap': True}

In [111]:
joblib.dump(best_rf_2, f"{path}/mldl/ML_RandomForest_2.pkl");

El modelo se evaluó sobre el conjunto de prueba y se extrajeron las métricas necesarias para su posterior graficación. Como se observa obtenemos un PR-AUC Score de `0.5932`.

In [112]:
precision_rf_2, recall_rf_2, pr_auc_rf_2, ap_rf_2 = create_test_report(best_rf_2)

----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    466815
           1       0.62      0.51      0.56      1377

    accuracy                           1.00    468192
   macro avg       0.81      0.76      0.78    468192
weighted avg       1.00      1.00      1.00    468192

PR-AUC Score: 0.5931
Average Precision (AP) Score: 0.5932

A continuación, se representa la curva Precision-Recall, con el objetivo de analizar el comportamiento del modelo para distintos umbrales de clasificación.

In [113]:
plot_PRAUC(precision_rf_2, recall_rf_2, pr_auc_rf_2, ap_rf_2, "Random Forest", "Model 2", "darkgreen")

#### **ALGORITMO XGBOOST**

Como punto de partida, se entrenó un modelo inicial basado en el algoritmo XGBoost. Debido al marcado desbalance existente entre las clases de la variable objetivo, se empleó el parámetro `scale_pos_weight`, utilizando `imbalance_weight` para compensar el peso de la clase minoritaria.

In [115]:
xgb_0 = xgb.XGBClassifier(
    n_estimators=300,        
    max_depth=6,               
    learning_rate=0.05,         
    scale_pos_weight=imbalance_weight,
    random_state=777,
    n_jobs=-1,                  
    eval_metric="logloss"       
)

xgb_0.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=-1,
              num_parallel_tree=None, ...)

In [117]:
joblib.dump(xgb_0, f"{path}/mldl/ML_XGBoost_0.pkl");

El modelo se evaluó sobre el conjunto de validación con un umbral de clasificación de 0.45.

In [118]:
create_validation_report(xgb_0)

-------- VALIDATION REPORT --------
              precision    recall  f1-score   support

           0       1.00      0.97      0.99    466815
           1       0.09      0.92      0.17      1376

    accuracy                           0.97    468191
   macro avg       0.55      0.95      0.58    468191
weighted avg       1.00      0.97      0.98    468191

PR-AUC Score: 0.6488
Average Precision (AP) Score: 0.6488

El modelo se evaluó sobre el conjunto de prueba y se extrajeron las métricas necesarias para su posterior graficación. Como se observa obtenemos un PR-AUC Score de `0.6421`.

In [119]:
precision_xgb_0, recall_xgb_0, pr_auc_xgb_0, ap_xgb_0 = create_test_report(xgb_0)

----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      0.97      0.99    466815
           1       0.09      0.94      0.17      1377

    accuracy                           0.97    468192
   macro avg       0.55      0.95      0.58    468192
weighted avg       1.00      0.97      0.98    468192

PR-AUC Score: 0.6421
Average Precision (AP) Score: 0.6422

A continuación, se representa la curva Precision-Recall, con el objetivo de analizar el comportamiento del modelo para distintos umbrales de clasificación.

In [120]:
plot_PRAUC(precision_xgb_0, recall_xgb_0, pr_auc_xgb_0, ap_xgb_0, "XGBoost", "Model 0", "lightblue")

En esta sección se lleva a cabo una búsqueda de hiperparámetros con el objetivo de identificar la configuración que proporciona el mejor rendimiento del modelo XGBoost, tomando como referencia las métricas de evaluación seleccionadas. Para ello se utiliza la métrica Average Precision (AP) como criterio de optimización durante el proceso de búsqueda.

In [14]:
num_legitimate = (y_train == 0).sum()
num_frauds = (y_train == 1).sum()
imbalance_weight = num_legitimate / num_frauds

param_dist_xgb = {
    'n_estimators': [200, 400, 600, 800],
    'max_depth': [3, 5, 7, 9],     
    'learning_rate': [0.01, 0.05, 0.1],
    'subsample': [0.7, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.9, 1.0],
    "min_child_weight": [1,3,5],
    "gamma": [0,0.2,0.5],
    "reg_alpha": [0,0.1,1],
    "reg_lambda": [1,2,5]
}

In [121]:
xgb_search = RandomizedSearchCV(
    estimator=xgb.XGBClassifier(
        scale_pos_weight=imbalance_weight,
        random_state=777,
        n_jobs=-1,
        eval_metric="logloss"
    ),
    param_distributions=param_dist_xgb,
    n_iter=5,                             
    cv=pds,                               
    scoring="average_precision",          
    verbose=0,
    n_jobs=1,
    random_state=777
)

xgb_search.fit(X_search, y_search)
best_xgb_1 = xgb_search.best_estimator_

print("--- BEST HYPERPARAMETERS FOUND ---")
print(xgb_search.best_params_)

--- BEST HYPERPARAMETERS FOUND ---
{'subsample': 0.9, 'reg_lambda': 5, 'reg_alpha': 1, 'n_estimators': 600, 'min_child_weight': 3, 'max_depth': 5, 'learning_rate': 0.1, 'gamma': 0.5, 'colsample_bytree': 0.7}

In [122]:
joblib.dump(best_xgb_1, f"{path}/mldl/ML_XGBoost_1.pkl");

El modelo se evaluó sobre el conjunto de prueba y se extrajeron las métricas necesarias para su posterior graficación. Como se observa obtenemos un PR-AUC Score de `0.7181`.

In [123]:
precision_xgb_1, recall_xgb_1, pr_auc_xgb_1, ap_xgb_1 = create_test_report(best_xgb_1)

----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      0.99      1.00    466815
           1       0.26      0.87      0.40      1377

    accuracy                           0.99    468192
   macro avg       0.63      0.93      0.70    468192
weighted avg       1.00      0.99      0.99    468192

PR-AUC Score: 0.7181
Average Precision (AP) Score: 0.7182

A continuación, se representa la curva Precision-Recall, con el objetivo de analizar el comportamiento del modelo para distintos umbrales de clasificación.

In [124]:
plot_PRAUC(precision_xgb_1, recall_xgb_1, pr_auc_xgb_1, ap_xgb_1, "XGBoost", "Model 1", "darkorange")

En esta sección se lleva a cabo una búsqueda de hiperparámetros tomando como criterio de optimización la métrica F1 Score (F1).

In [125]:
xgb_search = RandomizedSearchCV(
    estimator=xgb.XGBClassifier(
        scale_pos_weight=imbalance_weight,
        random_state=777,
        n_jobs=-1,
        eval_metric="logloss"
    ),
    param_distributions=param_dist_xgb,
    n_iter=5,                             
    cv=pds,                               
    scoring="f1",          
    verbose=0,
    n_jobs=1,
    random_state=777
)

xgb_search.fit(X_search, y_search)
best_xgb_2 = xgb_search.best_estimator_

print("--- BEST HYPERPARAMETERS FOUND ---")
print(xgb_search.best_params_)

--- BEST HYPERPARAMETERS FOUND ---
{'subsample': 0.9, 'reg_lambda': 5, 'reg_alpha': 1, 'n_estimators': 600, 'min_child_weight': 3, 'max_depth': 5, 'learning_rate': 0.1, 'gamma': 0.5, 'colsample_bytree': 0.7}

In [128]:
joblib.dump(best_xgb_2, f"{path}/mldl/ML_XGBoost_2.pkl");

El modelo se evaluó sobre el conjunto de prueba y se extrajeron las métricas necesarias para su posterior graficación. Como se observa obtenemos un PR-AUC Score de `0.7181`.

In [130]:
precision_xgb_2, recall_xgb_2, pr_auc_xgb_2, ap_xgb_2 = create_test_report(best_xgb_2)

----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      0.99      1.00    466815
           1       0.26      0.87      0.40      1377

    accuracy                           0.99    468192
   macro avg       0.63      0.93      0.70    468192
weighted avg       1.00      0.99      0.99    468192

PR-AUC Score: 0.7181
Average Precision (AP) Score: 0.7182

A continuación, se representa la curva Precision-Recall, con el objetivo de analizar el comportamiento del modelo para distintos umbrales de clasificación.

In [131]:
plot_PRAUC(precision_xgb_2, recall_xgb_2, pr_auc_xgb_2, ap_xgb_2, "XGBoost", "Model 2", "darkgreen")

#### **ALGORITMO LIGHTGBM**

Como punto de partida, se entrenó un modelo inicial basado en el algoritmo LightGBM. Debido al marcado desbalance existente entre las clases de la variable objetivo, se empleó el parámetro `scale_pos_weight`, utilizando `imbalance_weight` para compensar el peso de la clase minoritaria.

In [64]:
lgb_0 = lgb.LGBMClassifier(
    n_estimators=300,          
    num_leaves=31,             
    learning_rate=0.05,         
    scale_pos_weight=imbalance_weight,
    random_state=777,
    n_jobs=-1,                 
    verbosity=-1            
)

lgb_0.fit(X_train, y_train)

LGBMClassifier(learning_rate=0.05, n_estimators=300, n_jobs=-1,
               random_state=777, scale_pos_weight=15.57389814670612,
               verbosity=-1)

In [65]:
joblib.dump(lgb_0, f"{path}/mldl/ML_LightGBM_0.pkl");

El modelo se evaluó sobre el conjunto de validación con un umbral de clasificación de 0.45.

In [66]:
create_validation_report(lgb_0)

-------- VALIDATION REPORT --------
              precision    recall  f1-score   support

           0       1.00      0.97      0.99    466815
           1       0.09      0.93      0.16      1376

    accuracy                           0.97    468191
   macro avg       0.54      0.95      0.57    468191
weighted avg       1.00      0.97      0.98    468191

PR-AUC Score: 0.6457
Average Precision (AP) Score: 0.6458

El modelo se evaluó sobre el conjunto de prueba y se extrajeron las métricas necesarias para su posterior graficación. Como se observa obtenemos un PR-AUC Score de `0.6423`.

In [68]:
precision_lgb_0, recall_lgb_0, pr_auc_lgb_0, ap_lgb_0 = create_test_report(lgb_0)

----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      0.97      0.99    466815
           1       0.09      0.94      0.16      1377

    accuracy                           0.97    468192
   macro avg       0.54      0.95      0.57    468192
weighted avg       1.00      0.97      0.98    468192

PR-AUC Score: 0.6423
Average Precision (AP) Score: 0.6424

A continuación, se representa la curva Precision-Recall, con el objetivo de analizar el comportamiento del modelo para distintos umbrales de clasificación.

In [69]:
plot_PRAUC(precision_lgb_0, recall_lgb_0, pr_auc_lgb_0, ap_lgb_0, "LightGBM", "Model 0", "lightblue")

En esta sección se lleva a cabo una búsqueda de hiperparámetros con el objetivo de identificar la configuración que proporciona el mejor rendimiento del modelo LightGBM, tomando como referencia las métricas de evaluación seleccionadas. Para ello se utiliza la métrica Average Precision (AP) como criterio de optimización durante el proceso de búsqueda.

In [63]:
lgb_param_dist = {
    'n_estimators': [200, 400, 600, 800],
    'num_leaves': [31, 63, 127, 255],    
    'learning_rate': [0.01, 0.05, 0.1],     
    'subsample': [0.7, 0.9, 1.0],           
    'colsample_bytree': [0.7, 0.9, 1.0], 
    'min_child_samples': [10, 20, 50]      
}

In [70]:
lgb_search = RandomizedSearchCV(
    estimator=lgb.LGBMClassifier(
        scale_pos_weight=imbalance_weight,  
        random_state=777,
        n_jobs=-1,
        verbosity=-1                        
    ),
    param_distributions=lgb_param_dist,
    n_iter=5,                               
    cv=pds,                                 
    scoring="average_precision",           
    verbose=0,
    n_jobs=1,
    random_state=77                               
)

lgb_search.fit(X_search, y_search)
best_lgb_1 = lgb_search.best_estimator_

print("--- BEST HYPERPARAMETERS FOUND (LIGHTGBM) ---")
print(lgb_search.best_params_)

--- BEST HYPERPARAMETERS FOUND (LIGHTGBM) ---
{'subsample': 0.9, 'num_leaves': 63, 'n_estimators': 400, 'min_child_samples': 10, 'learning_rate': 0.1, 'colsample_bytree': 0.9}

In [71]:
joblib.dump(best_lgb_1, f"{path}/mldl/ML_LightGBM_1.pkl");

El modelo se evaluó sobre el conjunto de prueba y se extrajeron las métricas necesarias para su posterior graficación. Como se observa obtenemos un PR-AUC Score de `0.6844`.

In [73]:
precision_lgb_1, recall_lgb_1, pr_auc_lgb_1, ap_lgb_1 = create_test_report(best_lgb_1)

----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    466815
           1       0.33      0.80      0.46      1377

    accuracy                           0.99    468192
   macro avg       0.66      0.90      0.73    468192
weighted avg       1.00      0.99      1.00    468192

PR-AUC Score: 0.6844
Average Precision (AP) Score: 0.6845

A continuación, se representa la curva Precision-Recall, con el objetivo de analizar el comportamiento del modelo para distintos umbrales de clasificación.

In [74]:
plot_PRAUC(precision_lgb_1, recall_lgb_1, pr_auc_lgb_1, ap_lgb_1, "LightGBM", "Model 1", "darkorange")

En esta sección se lleva a cabo una búsqueda de hiperparámetros tomando como criterio de optimización la métrica F1 Score (F1).

In [75]:
lgb_search = RandomizedSearchCV(
    estimator=lgb.LGBMClassifier(
        scale_pos_weight=imbalance_weight,  
        random_state=777,
        n_jobs=-1,
        verbosity=-1                        
    ),
    param_distributions=lgb_param_dist,
    n_iter=5,                               
    cv=pds,                                 
    scoring="f1",           
    verbose=0,
    n_jobs=1,
    random_state=77                               
)

lgb_search.fit(X_search, y_search)
best_lgb_2 = lgb_search.best_estimator_

print("--- BEST HYPERPARAMETERS FOUND (LIGHTGBM) ---")
print(lgb_search.best_params_)

--- BEST HYPERPARAMETERS FOUND (LIGHTGBM) ---
{'subsample': 0.9, 'num_leaves': 127, 'n_estimators': 800, 'min_child_samples': 20, 'learning_rate': 0.05, 'colsample_bytree': 0.7}

In [76]:
joblib.dump(best_lgb_2, f"{path}/mldl/ML_LightGBM_2.pkl");

El modelo se evaluó sobre el conjunto de prueba y se extrajeron las métricas necesarias para su posterior graficación. Como se observa obtenemos un PR-AUC Score de `0.7462`.

In [77]:
precision_lgb_2, recall_lgb_2, pr_auc_lgb_2, ap_lgb_2 = create_test_report(best_lgb_2)

----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    466815
           1       0.49      0.78      0.60      1377

    accuracy                           1.00    468192
   macro avg       0.74      0.89      0.80    468192
weighted avg       1.00      1.00      1.00    468192

PR-AUC Score: 0.7462
Average Precision (AP) Score: 0.7463

A continuación, se representa la curva Precision-Recall, con el objetivo de analizar el comportamiento del modelo para distintos umbrales de clasificación.

In [78]:
plot_PRAUC(precision_lgb_2, recall_lgb_2, pr_auc_lgb_2, ap_lgb_2, "LightGBM", "Model 2", "darkgreen")

---

### <span id="DL"></span> **3.9. Modelado por Deep Learning**

En esta sección se presenta el proceso de entrenamiento y evaluación de los modelos de Deep Learning empleados para la clasificación de las transacciones. Para ello, se implementaron y evaluaron las siguientes arquitecturas:
- MLP (Multilayer Perceptron)
- CNN 1D (Convolutional Neural Network)
- CNN 1D + LSTM (Long Short-Term Memory)

Cargamos nuestro archivo que creamos en el apartado anterior con todas las características generadas:

In [9]:
features_df = (
    pl.scan_parquet(f"{path}/data/gold/Polars/feature_complete_fraud_data.parquet")
    .select(pl.all().exclude("merchant_latitude", "merchant_longitude"))
)

features_df.show(5)

date,client_id,card_id,id,target,mcc_rate,Log2_risk_factor,agemonth_at_event,days_acct_open,days_expires,retirement_month,No_Errors,Bad_Card_Number,Bad_CVV,Bad_Expiration,Bad_PIN,Bad_Zipcode,Insufficient_Balance,Technical_Glitch,Visa,Discover,Amex,Mastercard,Debit_Prepaid,Credit,Debit,Online_Transaction,Chip_Transaction,Swipe_Transaction,Male,amount,credit_limit,yearly_income,total_debt,sum_amount_24h,mean_log_amount_7d,stddev_log_amount_7d,…,ic_lower_speed_95,ic_upper_speed_95,ic_lower_speed_99,ic_upper_speed_99,is_tdiffm_in_IC90,is_tdiffm_in_IC95,is_tdiffm_in_IC99,hour_of_day,theta,sin_theta,cos_theta,N_7d,day_of_week,weekend,mu_vM_7d,sigma_vM_7d,ic_lower_vm_90_7d,ic_upper_vm_90_7d,ic_lower_vm_95_7d,ic_upper_vm_95_7d,ic_lower_vm_99_7d,ic_upper_vm_99_7d,is_time_in_IC_90,is_time_in_IC_95,is_time_in_IC_99,log_time_diff_m,mean_time_diff_m,stddev_time_diff_m,ic_lower_tdiffm_90,ic_upper_tdiffm_90,ic_lower_tdiffm_95,ic_upper_tdiffm_95,ic_lower_tdiffm_99,ic_upper_tdiffm_99,is_tdiffm_in_IC90_right,is_tdiffm_in_IC95_right,is_tdiffm_in_IC99_right
datetime[μs],i64,i64,i64,bool,f64,f64,i64,i64,i64,i64,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,f64,f64,f64,f64,f64,f64,f64,…,f64,f64,f64,f64,bool,bool,bool,f64,f64,f64,f64,u32,i8,bool,f64,f64,f64,f64,f64,f64,f64,f64,bool,bool,bool,f64,f64,f64,f64,f64,f64,f64,f64,f64,bool,bool,bool
2013-07-19 13:23:00.001906,0,1271,13047138,false,0.0,-16.61,328,899,2812,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true,42.52,31490.0,59613.0,36199.0,178.57,3.704316,0.847393,…,0.0,0.0,0.0,0.0,true,true,true,13.383333,-2.779437,-0.354291,-0.935135,14,5,true,-1.787862,1.140618,-2.327718,-1.248005,-2.446435,-1.129288,-2.706133,-0.869591,false,false,false,7.248504,5.388894,1.966031,4.458368,6.31942,4.253742,6.524046,3.806112,6.971676,false,false,false
2013-07-19 20:35:00.001908,0,1271,13048785,false,0.0,-16.61,328,899,2812,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true,37.51,31490.0,59613.0,36199.0,-14.21,3.589914,0.860677,…,0.003283,0.003283,0.003283,0.003283,true,true,true,20.583333,-0.894481,-0.779884,0.625923,15,5,true,-1.695244,1.117504,-2.203449,-1.187038,-2.314096,-1.076391,-2.554176,-0.836311,false,false,true,2.833213,5.665579,1.880844,4.810231,6.520927,4.624002,6.707156,4.21993,7.111228,false,false,false
2013-07-20 13:18:00.001909,0,1271,13051758,false,0.0,-16.61,328,900,2811,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true,44.17,31490.0,59613.0,36199.0,23.3,3.6503,0.828995,…,0.0,0.0,0.0,0.0,true,true,true,13.3,-2.801253,-0.333807,-0.942641,14,6,true,-1.780181,1.143653,-2.321474,-1.238888,-2.440507,-1.119855,-2.700896,-0.859466,false,false,false,6.911747,5.578957,2.02505,4.620497,6.537417,4.409728,6.748186,3.948661,7.209253,false,false,true
2013-07-23 06:42:00.001911,0,1271,13063377,false,0.0,-16.61,328,903,2808,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true,14.5,31490.0,59613.0,36199.0,91.64,3.844047,0.589087,…,0.001011,0.001011,0.001011,0.001011,true,true,true,6.7,1.754056,0.983255,-0.182236,11,2,false,-2.28379,1.151315,-2.912958,-1.654622,-3.057254,-1.510326,2.899231,-1.183626,false,false,false,6.957497,5.688408,2.348834,4.404823,6.971993,4.11044,7.266376,3.443929,7.932887,true,true,true
2013-07-23 14:15:00.001912,0,1271,13065451,false,0.0,-16.61,328,903,2808,500,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,true,false,false,true,16.73,31490.0,59613.0,36199.0,61.97,3.72537,0.657981,…,0.000176,0.000176,0.000176,0.000176,true,true,true,14.25,-2.552544,-0.55557,-0.83147,11,2,false,-2.602641,1.165326,3.043719,-1.965817,2.897667,-1.819764,2.566991,-1.489089,true,true,true,6.118097,5.653595,2.32453,4.383291,6.923898,4.091954,7.215235,3.43234,7.87485,true,true,true

Materializamos nuestro lazyframe.

In [10]:
df = features_df.collect()

Como señalamos anteriormente existe un marcado desbalance en la variable objetivo (target) que se pretende clasificar mediante los modelos de aprendizaje automático.

In [11]:
proportions = (
    df
    .group_by("target")
    .agg([
        pl.len().alias("cantidad"),
        (pl.len() / len(df) * 100).alias("porcentaje")
    ])
    .with_columns(target = label_expr)
)

proportions

shape: (2, 3)
 target      cantidad  porcentaje
 ---         ---       ---
 str         u32       f64
 Legitimate  3112100   99.706082
 Fraudulent  9174      0.293918

El conjunto de datos se particionó en tres subconjuntos: entrenamiento, validación y prueba, destinados respectivamente al entrenamiento de los modelos, al seguimiento de su rendimiento durante el proceso de entrenamiento y a la evaluación final sobre datos no utilizados durante dicho proceso.

In [12]:
False_df = df.filter(~pl.col("target"))
False_train_df = False_df.sample(fraction=0.70, seed=777)
False_valtest_df = False_df.join(False_train_df, on="id", how="anti")
False_val_df = False_valtest_df.sample(fraction=0.50, seed=777)
False_test_df = False_valtest_df.join(False_val_df, on="id", how="anti")

True_df = df.filter(pl.col("target"))
True_train_df = True_df.sample(fraction=0.70, seed=777)
True_valtest_df = True_df.join(True_train_df, on="id", how="anti")
True_val_df = True_valtest_df.sample(fraction=0.50, seed=777)
True_test_df = True_valtest_df.join(True_val_df, on="id", how="anti")

train_df = pl.concat([False_train_df, True_train_df]).sort(["client_id", "card_id", "date", "id"]) 
val_df = pl.concat([False_val_df, True_val_df]).sort(["client_id", "card_id", "date", "id"]) 
test_df = pl.concat([False_test_df, True_test_df]).sort(["client_id", "card_id", "date", "id"]) 

## Definimos los datos que usaremos para el entrenamiento, la validación y el testeo del modelo
scaler = StandardScaler()

X_train = scaler.fit_transform(
    train_df
    .drop("target", "client_id", "card_id", "date", "id")
    .cast(pl.Float32).to_numpy()
)
y_train = train_df["target"].cast(pl.Int8).to_numpy()

X_val = scaler.transform(
    val_df
    .drop("target", "client_id", "card_id", "date", "id")
    .cast(pl.Float32).to_numpy()
)
y_val = val_df["target"].cast(pl.Int8).to_numpy()

X_test = scaler.transform(
    test_df
    .drop("target", "client_id", "card_id", "date", "id")
    .cast(pl.Float32).to_numpy()
)
y_test = test_df["target"].cast(pl.Int8).to_numpy()

classes = np.unique(y_train)
weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_train)
class_weight_dict = dict(zip(classes, weights))

pos = int(len(train_df)*proportions[1, 2]/100)
neg = len(train_df) - pos
initial_bias = np.log([pos / neg])
output_bias = tf.keras.initializers.Constant(initial_bias)

En esta sección se entrenará una red neuronal MLP y se evaluarán dos estrategias de función de pérdida para abordar el desequilibrio entre las clases:
- Binary Cross-Entropy + class_weight
- Binary Focal Cross-Entropy

In [5]:
early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor="val_pr_auc",
    mode="max",
    patience=10,
    restore_best_weights=True
)

def create_checkpoint(fpath):
    return tf.keras.callbacks.ModelCheckpoint(
        filepath=fpath,
        monitor="val_pr_auc",
        mode="max",
        save_best_only=True,
        verbose=0
)

In [9]:
def create_model():
    return tf.keras.Sequential([
        layers.Input(shape=X_train.shape[1]),
    
        layers.Dense(512, activation="relu", kernel_regularizer=regularizers.l2(5e-4)),
        layers.BatchNormalization(),
        layers.Dropout(0.3),
    
        layers.Dense(256, activation='relu', kernel_regularizer=regularizers.l2(5e-4)),
        layers.BatchNormalization(),
        layers.Dropout(0.3),
        
        layers.Dense(128, activation="relu", kernel_regularizer=regularizers.l2(5e-4)),
        layers.BatchNormalization(),
        layers.Dropout(0.2),
    
        layers.Dense(64, activation="relu", kernel_regularizer=regularizers.l2(5e-4)),
        layers.BatchNormalization(),
    
        layers.Dense(1, activation="sigmoid",  bias_initializer=output_bias)
    ])

En este primer modelo usaremos como función de pérdida `Binary Cross-Entropy + class_weight`

In [20]:
model_mlp_1 = create_model()

model_mlp_1.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=[
        tf.keras.metrics.AUC(name='pr_auc', curve='PR'),
        tf.keras.metrics.Precision(name='precision'),
        tf.keras.metrics.Recall(name='recall'),
    ]
)

checkpoint_1 = create_checkpoint(f"{path}/mldl/DL_MLP_1.keras")

history_mlp_1 = model_mlp_1.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=2048,
    validation_data=(X_val, y_val),
    class_weight=class_weight_dict,
    callbacks=[early_stopping, checkpoint_1],
    shuffle=True,
    verbose=0
)

A continuación, se representa la evolución de la métrica PR-AUC a lo largo de las épocas de entrenamiento, tanto para el conjunto de entrenamiento como para el conjunto de validación.

In [17]:
plot_monitoring(history_mlp_1, "Model MLP 1")

El modelo se evaluó sobre el conjunto de prueba y se extrajeron las métricas necesarias para su posterior graficación. Como se observa obtenemos un PR-AUC Score de `0.4625`.

In [32]:
precision_mlp_1, recall_mlp_1, pr_auc_mlp_1, ap_mlp_1 = create_test_report_2(model_mlp_1)

14631/14631 ━━━━━━━━━━━━━━━━━━━━ 14s 978us/step
----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      0.96      0.98    466815
           1       0.06      0.93      0.11      1377

    accuracy                           0.96    468192
   macro avg       0.53      0.94      0.54    468192
weighted avg       1.00      0.96      0.97    468192

PR-AUC Score: 0.4625
Average Precision (AP) Score: 0.4632

A continuación, se representa la curva Precision-Recall, con el objetivo de analizar el comportamiento del modelo para distintos umbrales de clasificación.

In [33]:
plot_PRAUC(precision_mlp_1, recall_mlp_1, pr_auc_mlp_1, ap_mlp_1, "MLP", "Model 1", "darkorange")

En este segundo modelo usaremos como función de pérdida `BinaryFocalCrossentropy`

In [35]:
model_mlp_2 = create_model()

model_mlp_2.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss=tf.keras.losses.BinaryFocalCrossentropy(gamma=2.0, alpha=0.997),
    metrics=[
        tf.keras.metrics.AUC(name='pr_auc', curve='PR'),
        tf.keras.metrics.Precision(name='precision'),
        tf.keras.metrics.Recall(name='recall'),
    ]
)

checkpoint_2 = create_checkpoint(f"{path}/mldl/DL_MLP_2.keras")

history_mlp_2 = model_mlp_2.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=2048,
    validation_data=(X_val, y_val),
    callbacks=[early_stopping, checkpoint_2],
    shuffle=True,
    verbose=0
)

A continuación, se representa la evolución de la métrica PR-AUC a lo largo de las épocas de entrenamiento, tanto para el conjunto de entrenamiento como para el conjunto de validación.

In [36]:
plot_monitoring(history_mlp_2, "Model MLP 2")

El modelo se evaluó sobre el conjunto de prueba y se extrajeron las métricas necesarias para su posterior graficación. Como se observa obtenemos un PR-AUC Score de `0.4682`.

In [43]:
precision_mlp_2, recall_mlp_2, pr_auc_mlp_2, ap_mlp_2 = create_test_report_2(model_mlp_2)

14631/14631 ━━━━━━━━━━━━━━━━━━━━ 15s 997us/step
----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    466815
           1       0.86      0.18      0.30      1377

    accuracy                           1.00    468192
   macro avg       0.93      0.59      0.65    468192
weighted avg       1.00      1.00      1.00    468192

PR-AUC Score: 0.4680
Average Precision (AP) Score: 0.4682

A continuación, se representa la curva Precision-Recall, con el objetivo de analizar el comportamiento del modelo para distintos umbrales de clasificación.

In [38]:
plot_PRAUC(precision_mlp_2, recall_mlp_2, pr_auc_mlp_2, ap_mlp_2, "MLP", "Model 2", "darkgreen")

En esta sección se entrenó un modelo basado en una red neuronal convolucional (CNN).

In [14]:
X_train_cnn = X_train[..., None]
X_val_cnn = X_val[..., None]    
X_test_cnn = X_test[..., None]

In [17]:
model_cnn_1 = tf.keras.Sequential([
    layers.Input(shape=X_train_cnn.shape[1:]), 
    
    layers.Conv1D(filters=64, kernel_size=5, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPooling1D(pool_size=2), 
    layers.Dropout(0.2),
    
    layers.Conv1D(filters=128, kernel_size=3, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPooling1D(pool_size=2),
    layers.Dropout(0.2),
    
    layers.Conv1D(filters=256, kernel_size=3, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.GlobalMaxPooling1D(), 
    layers.Dropout(0.3),
    
    layers.Dense(128, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.3),
    
    layers.Dense(1, activation='sigmoid')
])

model_cnn_1.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss=tf.keras.losses.BinaryFocalCrossentropy(gamma=2.0,apply_class_balancing=True, alpha=0.997 ),
    metrics=[
        tf.keras.metrics.AUC(curve='PR', name='pr_auc'),
        tf.keras.metrics.Precision(name='precision'),
        tf.keras.metrics.Recall(name='recall')
    ]
)

checkpoint_3 = create_checkpoint(f"{path}/mldl/DL_CNN_1.keras")

history_cnn_1 = model_cnn_1.fit(
    X_train_cnn, y_train,
    epochs=50,
    batch_size=2048, 
    validation_data=(X_val_cnn, y_val),
    callbacks=[early_stopping, checkpoint_3],
    verbose=0
)

A continuación, se representa la evolución de la métrica PR-AUC a lo largo de las épocas de entrenamiento, tanto para el conjunto de entrenamiento como para el conjunto de validación.

In [18]:
plot_monitoring(history_cnn_1, "Model CNN 1")

El modelo se evaluó sobre el conjunto de prueba y se extrajeron las métricas necesarias para su posterior graficación. Como se observa obtenemos un PR-AUC Score de `0.5530`.

In [19]:
precision_cnn_1, recall_cnn_1, pr_auc_cnn_1, ap_cnn_1 = create_test_report_2(model_cnn_1)

14631/14631 ━━━━━━━━━━━━━━━━━━━━ 83s 6ms/step
----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      0.91      0.95    466815
           1       0.03      0.96      0.06      1377

    accuracy                           0.91    468192
   macro avg       0.52      0.94      0.51    468192
weighted avg       1.00      0.91      0.95    468192

PR-AUC Score: 0.5530
Average Precision (AP) Score: 0.5532

A continuación, se representa la curva Precision-Recall, con el objetivo de analizar el comportamiento del modelo para distintos umbrales de clasificación.

In [20]:
plot_PRAUC(precision_cnn_1, recall_cnn_1, pr_auc_cnn_1, ap_cnn_1, "CNN", "Model 1", "darkorange")

En esta sección utilizamos la arquitectura CNN-LSTM, inicialmente entrenamos el modelo sin la creación de ventanas temporales, para una posterior comparación con una ventana temporal de 5 transacciones.

In [29]:
model_cnn_lstm_1 = tf.keras.Sequential([
    layers.Input(shape=X_train_cnn.shape[1:]), 
    
    layers.Conv1D(filters=64, kernel_size=5, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPooling1D(pool_size=2),
    layers.Dropout(0.2),
    
    layers.Conv1D(filters=128, kernel_size=3, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPooling1D(pool_size=2), 
    layers.Dropout(0.2),
    
    layers.Conv1D(filters=256, kernel_size=3, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.3),
    
    layers.LSTM(units=128, activation='tanh', recurrent_activation='sigmoid'), 
    layers.BatchNormalization(),
    layers.Dropout(0.3),
    
    layers.Dense(64, activation='relu'), 
    layers.BatchNormalization(),
    layers.Dropout(0.3),
    
    layers.Dense(1, activation='sigmoid')
])

model_cnn_lstm_1.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss=tf.keras.losses.BinaryFocalCrossentropy(gamma=2.0, apply_class_balancing=True, alpha=0.997),
    metrics=[
        tf.keras.metrics.AUC(curve='PR', name='pr_auc'),
        tf.keras.metrics.Precision(name='precision'),
        tf.keras.metrics.Recall(name='recall')
    ]
)

checkpoint_4 = create_checkpoint(f"{path}/mldl/DL_CNN_LSTM_1.keras")

history_cnn_lstm_1 = model_cnn_lstm_1.fit(
    X_train_cnn, y_train,
    epochs=50,
    batch_size=2048, 
    validation_data=(X_val_cnn, y_val),
    callbacks=[early_stopping, checkpoint_4],
    verbose=0
)

A continuación, se representa la evolución de la métrica PR-AUC a lo largo de las épocas de entrenamiento, tanto para el conjunto de entrenamiento como para el conjunto de validación.

In [21]:
plot_monitoring(history_cnn_lstm_1, "Model CNN + LSTM 1")

El modelo se evaluó sobre el conjunto de prueba y se extrajeron las métricas necesarias para su posterior graficación. Como se observa obtenemos un PR-AUC Score de `0.4966`.

In [22]:
precision_cnn_lstm_1, recall_cnn_lstm_1, pr_auc_cnn_lstm_1, ap_cnn_lstm_1 = create_test_report_2(model_cnn_lstm_1)

14631/14631 ━━━━━━━━━━━━━━━━━━━━ 267s 18ms/step
----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      0.92      0.96    466815
           1       0.03      0.95      0.06      1377

    accuracy                           0.92    468192
   macro avg       0.52      0.94      0.51    468192
weighted avg       1.00      0.92      0.95    468192

PR-AUC Score: 0.4966
Average Precision (AP) Score: 0.4968

A continuación, se representa la curva Precision-Recall, con el objetivo de analizar el comportamiento del modelo para distintos umbrales de clasificación.

In [23]:
plot_PRAUC(precision_cnn_lstm_1, recall_cnn_lstm_1, pr_auc_cnn_lstm_1, ap_cnn_lstm_1, "CNN + LSTM", "Model 1", "darkgreen")

In [24]:
import sys
import gc

for var in list(globals().keys()):
    if not var.startswith('_') and var not in ['sys', 'gc', 'path']:
        tipo_var = str(type(globals()[var]))
        if 'function' not in tipo_var and 'module' not in tipo_var and 'type' not in tipo_var:
            del globals()[var]

gc.collect()

df = (
    pl.scan_parquet(f"{path}data/gold/Polars/feature_complete_fraud_data.parquet")
    .select(pl.all().exclude("merchant_latitude", "merchant_longitude"))
    .collect()
)

# X_train = np.load(f"{path}/data/silver/Polars/X_train_w5.npy")
# y_train = np.load(f"{path}/data/silver/Polars/y_train_w5.npy")
# X_val = np.load(f"{path}/data/silver/Polars/X_val_w5.npy")
# y_val = np.load(f"{path}/data/silver/Polars/y_val_w5.npy")
# X_test = np.load(f"{path}/data/silver/Polars/X_test_w5.npy")
# y_test = np.load(f"{path}/data/silver/Polars/y_test_w5.npy")

En esta sección separamos nuestros datos de entrenamiento, validación y test por orden temporal. Y crearemos ventanas temporales de 5 transacciones agrupando por cliente y tarjeta. El uso de 5 transacciones como ventana temporal se debe a limitaciones técnicas.

In [25]:
WINDOW_SIZE = 5

df = df.sort("date")
total_rows = len(df)
train_index = int(total_rows * 0.70)
val_index = int(total_rows * 0.85)

VAL_CUTOFF_DATE = df["date"][train_index]
TEST_CUTOFF_DATE = df["date"][val_index]

train_df = (
    df.filter(pl.col("date") < VAL_CUTOFF_DATE)
    .sort(["client_id", "card_id", "date", "id"])
)
val_df = (
    df.filter((pl.col("date") >= VAL_CUTOFF_DATE) & (pl.col("date") < TEST_CUTOFF_DATE))
    .sort(["client_id", "card_id", "date", "id"])
)
test_df = (
    df.filter(pl.col("date") >= TEST_CUTOFF_DATE)
    .sort(["client_id", "card_id", "date", "id"])
)

excluded_columns = ["id", "client_id", "card_id", "date", "target", "window_target"]
columns_to_scale = train_df.select(pl.all().exclude(excluded_columns)).columns
scaler = StandardScaler()
scaler.fit(train_df.select(columns_to_scale).to_pandas())

def apply_scaling(df_polars, data_scaler, columns):
    transformed_df = pl.DataFrame(
        data_scaler.transform(df_polars.select(columns).to_pandas()), 
        schema=columns
    )
    return df_polars.with_columns([transformed_df[c] for c in columns])

def build_windows_by_id_join(df, window_size, is_train=True):            
    flat_ids_df = (
        df.select(["client_id", "card_id", "date", "id", "target"])
        .with_columns([
            *[pl.col("id").shift(window_size - 1 - i).over(["client_id", "card_id"]).alias(f"id_step_{i}") 
              for i in range(window_size)],
            pl.any_horizontal([
                pl.col("target").shift(i).over(["client_id", "card_id"]) 
                for i in range(window_size)
            ]).alias("window_target")
        ])
        .drop_nulls(subset=["id_step_0", "window_target"])
    )

    id_cols = [f"id_step_{i}" for i in range(window_size)]
    window_targets = flat_ids_df["window_target"].to_numpy().astype(np.int32)
    flat_ids_df = flat_ids_df.select(id_cols)

    feature_cols = df.select(pl.all().exclude(["client_id", "card_id", "date", "id", "target"])).columns
    raw_ids = df["id"].to_numpy()
    raw_features = df.select(feature_cols).to_numpy().astype(np.float32)
    del df
    gc.collect()
    
    id_to_index = {id_val: idx for idx, id_val in enumerate(raw_ids)}
    num_samples = len(flat_ids_df)
    num_features = len(feature_cols)
    X_3d = np.empty((num_samples, window_size, num_features), dtype=np.float32)
    
    for step in range(window_size):
        step_ids = flat_ids_df[f"id_step_{step}"].to_numpy()
        feature_indices = [id_to_index[id_val] for id_val in step_ids]
        X_3d[:, step, :] = raw_features[feature_indices]
        
    del raw_features, raw_ids, id_to_index, flat_ids_df
    gc.collect()
    
    return X_3d, window_targets

In [26]:
train_df = apply_scaling(train_df, scaler, columns_to_scale)
X_train, y_train = build_windows_by_id_join(train_df, WINDOW_SIZE, is_train=True)
del train_df
gc.collect()
np.save(f"{path}/data/silver/Polars/X_train_w5.npy", X_train)
np.save(f"{path}/data/silver/Polars/y_train_w5.npy", y_train)

In [27]:
val_df = apply_scaling(val_df, scaler, columns_to_scale)
X_val, y_val = build_windows_by_id_join(val_df, WINDOW_SIZE, is_train=False)
del val_df
gc.collect()
np.save(f"{path}/data/silver/Polars/X_val_w5.npy", X_val)
np.save(f"{path}/data/silver/Polars/y_val_w5.npy", y_val)

In [28]:
test_df = apply_scaling(test_df, scaler, columns_to_scale)
X_test, y_test = build_windows_by_id_join(test_df, WINDOW_SIZE, is_train=False)
del test_df
gc.collect()
np.save(f"{path}/data/silver/Polars/X_test_w5.npy", X_test)
np.save(f"{path}/data/silver/Polars/y_test_w5.npy", y_test)

A continuación realizamos el entrenamiento con una arquitectura CNN y el conjunto de entrenamiento con una ventana de 5 transacciones, para su convaración con el resto de combinaciones de las arquitecturas utilizadas.

In [16]:
model_cnn_2 = models.Sequential([
    layers.Input(shape=(X_train.shape[1], X_train.shape[2])), 
    
    layers.Conv1D(filters=64, kernel_size=3, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPooling1D(pool_size=1), 
    layers.Dropout(0.2),
    
    layers.Conv1D(filters=128, kernel_size=3, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPooling1D(pool_size=1),
    layers.Dropout(0.2),
    
    layers.Conv1D(filters=256, kernel_size=3, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.GlobalMaxPooling1D(), 
    layers.Dropout(0.3),
    
    layers.Dense(128, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.3),
    
    layers.Dense(1, activation='sigmoid')
])

model_cnn_2.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss=tf.keras.losses.BinaryFocalCrossentropy(gamma=2.0,apply_class_balancing=True, alpha=0.997 ),
    metrics=[
        tf.keras.metrics.AUC(curve='PR', name='pr_auc'),
        tf.keras.metrics.Precision(name='precision'),
        tf.keras.metrics.Recall(name='recall')
    ]
)

checkpoint_5 = create_checkpoint(f"{path}/mldl/DL_CNN_2.keras")

history_cnn_2 = model_cnn_2.fit(
    X_train, y_train,
    epochs=50,
    batch_size=2048, 
    validation_data=(X_val, y_val),
    callbacks=[early_stopping, checkpoint_5],
    verbose=0
)

A continuación, se representa la evolución de la métrica PR-AUC a lo largo de las épocas de entrenamiento, tanto para el conjunto de entrenamiento como para el conjunto de validación.

In [13]:
plot_monitoring(history_cnn_2, "Model CNN 2")

El modelo se evaluó sobre el conjunto de prueba y se extrajeron las métricas necesarias para su posterior graficación. Como se observa obtenemos un PR-AUC Score de `0.3978`.

In [14]:
precision_cnn_2, recall_cnn_2, pr_auc_cnn_2, ap_cnn_2 = create_test_report_2(model_cnn_2)

14199/14199 ━━━━━━━━━━━━━━━━━━━━ 64s 5ms/step
----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      0.95      0.97    451071
           1       0.09      0.75      0.17      3295

    accuracy                           0.95    454366
   macro avg       0.55      0.85      0.57    454366
weighted avg       0.99      0.95      0.97    454366

PR-AUC Score: 0.3978
Average Precision (AP) Score: 0.3979

A continuación, se representa la curva Precision-Recall, con el objetivo de analizar el comportamiento del modelo para distintos umbrales de clasificación.

In [15]:
plot_PRAUC(precision_cnn_2, recall_cnn_2, pr_auc_cnn_2, ap_cnn_2, "CNN", "Model 2", "darkgreen")

Por último, llevamos a cabo el entrenamiento en una arquitectura CNN-LSTM con una ventana temporal de 5 transacciones.

In [3]:
model_cnn_lstm_2 = tf.keras.Sequential([
    layers.Input(shape=(X_train.shape[1], X_train.shape[2])),

    layers.Conv1D(filters=64, kernel_size=3, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPooling1D(pool_size=1),
    layers.Dropout(0.2),

    layers.Conv1D(filters=128, kernel_size=3, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPooling1D(pool_size=1),
    layers.Dropout(0.2),

    layers.Conv1D(filters=256, kernel_size=3, padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.3),

    layers.LSTM(units=128, activation='tanh', recurrent_activation='sigmoid'),
    layers.BatchNormalization(),
    layers.Dropout(0.3),

    layers.Dense(64, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.3),

    layers.Dense(1, activation='sigmoid')
])

model_cnn_lstm_2.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss=tf.keras.losses.BinaryFocalCrossentropy(gamma=2.0, apply_class_balancing=True, alpha=0.997),
    metrics=[
        tf.keras.metrics.AUC(curve='PR', name='pr_auc'),
        tf.keras.metrics.Precision(name='precision'),
        tf.keras.metrics.Recall(name='recall')
    ]
)

checkpoint_6 = create_checkpoint(f"{path}/mldl/DL_CNN_LSTM_2.keras")

history_cnn_lstm_2 = model_cnn_lstm_2.fit(
    X_train, y_train,
    epochs=50,
    batch_size=2048,
    validation_data=(X_val, y_val),
    callbacks=[early_stopping, checkpoint_6],
    verbose=0
)

A continuación, se representa la evolución de la métrica PR-AUC a lo largo de las épocas de entrenamiento, tanto para el conjunto de entrenamiento como para el conjunto de validación.

In [18]:
plot_monitoring(history_cnn_lstm_2, "Model CNN + LSTM 2")

El modelo se evaluó sobre el conjunto de prueba y se extrajeron las métricas necesarias para su posterior graficación. Como se observa obtenemos un PR-AUC Score de `0.2732`.

In [19]:
precision_cnn_lstm_2, recall_cnn_lstm_2, pr_auc_cnn_lstm_2, ap_cnn_lstm_2 = create_test_report_2(model_cnn_lstm_2)

14199/14199 ━━━━━━━━━━━━━━━━━━━━ 112s 8ms/step
----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      0.88      0.94    451071
           1       0.05      0.82      0.09      3295

    accuracy                           0.88    454366
   macro avg       0.52      0.85      0.51    454366
weighted avg       0.99      0.88      0.93    454366

PR-AUC Score: 0.2732
Average Precision (AP) Score: 0.2735

A continuación, se representa la curva Precision-Recall, con el objetivo de analizar el comportamiento del modelo para distintos umbrales de clasificación.

In [20]:
plot_PRAUC(precision_cnn_lstm_2, recall_cnn_lstm_2, pr_auc_cnn_lstm_2, ap_cnn_lstm_2, "CNN + LSTM", "Model 2", "darkgreen")

## <span id="discussion"></span> **4. Discusión**

Los resultados obtenidos muestran que las características demográficas, temporales, espaciales y relacionadas con el comportamiento de compra presentan diferencias entre las transacciones legítimas y fraudulentas. En primer lugar, se observaron diferencias en la distribución del fraude según la edad de los usuarios. La proporción de operaciones fraudulentas aumenta especialmente entre los usuarios de 75 años o más. Asimismo, se observó una elevada proporción de transacciones fraudulentas entre los usuarios de 18 años, edad mínima considerada en el conjunto de datos para la adquisición de una tarjeta bancaria, siendo este comportamiento más marcado en hombres. Estos resultados sugieren que la edad y, en menor medida, el sexo pueden estar asociados con diferentes patrones de exposición al fraude. No obstante, estas diferencias deben interpretarse con cautela, ya que una mayor frecuencia de fraude en un determinado grupo no implica necesariamente una mayor vulnerabilidad individual, pudiendo estar condicionada por la frecuencia y características de uso de las tarjetas en cada población.

En relación con el tipo de comercio, se observaron diferencias en la frecuencia de operaciones fraudulentas según la categoría del establecimiento. Las líneas de cruceros y las tiendas de música presentaron una mayor proporción relativa de operaciones fraudulentas, mientras que los establecimientos relacionados con el mantenimiento de vehículos y los servicios deportivos y recreativos mostraron una menor incidencia. Estas diferencias ponen de manifiesto la relevancia de incorporar información relacionada con el comercio en los modelos de detección, ya que determinadas categorías pueden presentar patrones de riesgo diferenciados. Sin embargo, estos resultados deben entenderse como una asociación observada en el conjunto de datos analizado y no como una medida general del riesgo real de cada sector comercial.

Una de las principales características del conjunto de datos fue la presencia de un elevado número de transacciones sin auditoría. Aproximadamente el 33 % de las operaciones carecía de una etiqueta que permitiera determinar si se trataba de una transacción legítima o fraudulenta. Esta circunstancia constituye una limitación relevante para el análisis supervisado, dado que estas observaciones no pueden utilizarse directamente para evaluar el rendimiento de los modelos. Por este motivo, las transacciones no auditadas fueron excluidas del análisis de las variables relacionadas con la condición de fraude y del entrenamiento de los modelos. Sin embargo, se conservaron para la generación de características relacionadas con el comportamiento histórico de los clientes que no requieren conocer previamente si una operación es fraudulenta o legítima. De esta forma, fue posible aprovechar parte de la información disponible sin introducir directamente la etiqueta desconocida en el proceso de aprendizaje.

Tras la exclusión de las transacciones no auditadas, se observó un marcado desequilibrio de clases, con únicamente un 0,29 % de operaciones fraudulentas frente al 99,71 % de transacciones legítimas. Este desequilibrio constituye una de las principales dificultades del problema, ya que un modelo podría alcanzar una elevada exactitud clasificando la práctica totalidad de las operaciones como legítimas y, al mismo tiempo, presentar una capacidad de detección de fraude insuficiente. Por ello, el desequilibrio fue considerado tanto durante el entrenamiento mediante estrategias de ponderación de las clases como durante la evaluación, priorizando métricas adecuadas para escenarios de clasificación altamente desbalanceados, como Precision-Recall y PR-AUC.

Desde una perspectiva temporal, los resultados muestran una mayor frecuencia de operaciones fraudulentas durante el mes de marzo y una concentración relativa en viernes y domingos. Asimismo, el intervalo comprendido entre las 10:00 y las 12:00 horas presentó una mayor frecuencia de operaciones fraudulentas. También se identificó una periodicidad aproximada de siete días, junto con una concentración de determinadas operaciones hacia el final de mes. La presencia de estos patrones temporales respalda la incorporación de características capaces de representar la periodicidad y el comportamiento histórico de las transacciones. En este sentido, la información temporal no solo permite caracterizar cuándo se producen las operaciones, sino también identificar desviaciones respecto al comportamiento habitual de un determinado cliente.

Otro resultado relevante fue la concentración del fraude en las transacciones realizadas en línea. Estas operaciones no solo concentraron una proporción importante de las transacciones fraudulentas, sino también el mayor volumen económico asociado al fraude. Además, las distribuciones de los importes de las operaciones fraudulentas mostraron valores generalmente superiores a los observados en las operaciones legítimas, incluyendo valores extremos más elevados. Este comportamiento se mantuvo al analizar los diferentes métodos de pago. Estos resultados sugieren que el importe de la transacción puede proporcionar información relevante para la detección, especialmente cuando se analiza en relación con el comportamiento histórico del cliente. Una cantidad elevada no constituye por sí misma una evidencia de fraude, pero una operación cuyo importe se desvía significativamente del patrón habitual de gasto del usuario puede aportar información discriminante al modelo.

En cuanto a la dimensión geográfica, Italia concentró la mayor frecuencia de transacciones fraudulentas realizadas en el extranjero dentro del conjunto de datos, mientras que las transacciones fraudulentas realizadas localmente se concentraron principalmente en Ohio. Dado que los usuarios del conjunto de datos son residentes de Estados Unidos, estas diferencias permiten observar la posible relevancia de la localización geográfica como elemento contextual de una transacción. No obstante, al igual que ocurre con las diferencias entre categorías comerciales, estos resultados dependen de la distribución geográfica específica del conjunto de datos y no deben interpretarse directamente como una medida general del riesgo de fraude de un país o región.

La incorporación de información histórica permitió, además, observar patrones de comportamiento que no serían identificables mediante el análisis aislado de cada transacción. El código desarrollado para analizar el comportamiento de compra de los clientes permitió identificar, en determinados casos, operaciones atípicas asociadas con transacciones fraudulentas. Entre estos comportamientos se observaron ráfagas de operaciones concentradas en periodos de tiempo reducidos, realizadas en horarios poco habituales, con importes superiores a los habituales del cliente o en categorías de comercios poco frecuentadas previamente. En el análisis de las transacciones para las que se disponía de información de localización, se observó además que la primera operación fraudulenta podía producirse en un establecimiento previamente utilizado por el cliente, mientras que las operaciones fraudulentas posteriores se asociaban con establecimientos que no formaban parte de su historial habitual de compras. Este resultado resulta especialmente relevante, ya que muestra que el fraude no necesariamente comienza con una transacción completamente anómala, sino que puede presentar una evolución observable a través de una secuencia de operaciones.

Estas observaciones sirvieron de base para la generación de las características utilizadas posteriormente en los modelos predictivos. Se incorporaron características temporales destinadas a representar la periodicidad y el comportamiento histórico de las transacciones, incluyendo variables basadas en la distribución de von Mises, así como características relacionadas con la cuantía de los desembolsos. También se generaron características espaciales basadas en la distancia entre localizaciones, calculada mediante la fórmula de Haversine, y variables destinadas a representar el riesgo asociado a las diferentes categorías de comercio. De este modo, el proceso de ingeniería de características permitió trasladar al modelo parte de los patrones identificados durante el análisis exploratorio del comportamiento de los clientes. La información de localización se utilizó para caracterizar el comportamiento espacial, evitando utilizar directamente la condición de fraude como fuente de información para estas características.

Finalmente, la comparación de los modelos desarrollados mostró que LightGBM presentó el mejor rendimiento entre los modelos evaluados cuando se optimizó utilizando F1 como criterio de *scoring*. Este modelo alcanzó un valor de PR-AUC de 0,7463 sobre el conjunto de evaluación. Este resultado indica una capacidad relevante para discriminar las transacciones fraudulentas en un escenario caracterizado por un fuerte desequilibrio de clases. La utilización de PR-AUC resulta especialmente apropiada en este contexto, ya que permite evaluar conjuntamente la capacidad del modelo para recuperar operaciones fraudulentas y mantener una precisión adecuada ante la elevada proporción de transacciones legítimas. No obstante, el rendimiento obtenido también pone de manifiesto que existe margen de mejora, especialmente teniendo en cuenta la naturaleza dinámica del fraude y la dificultad de identificar patrones fraudulentos que pueden cambiar con el tiempo.

Las principales variables consideradas por este modelo son la indicación de si la transacción se realiza en línea y la variable `Log2RiskFactor`, generada durante el proceso de ingeniería de características. A continuación, se presentan las diez características con mayor importancia para la predicción, junto con el peso relativo de cada una en el modelo.

In [8]:
model = joblib.load(f"{path}/mldl/ML_LightGBM_2.pkl")
importances_gain = model.booster_.feature_importance(importance_type='gain')
feature_names = model.feature_name_  #

df_importance_pl = pl.DataFrame({
    "Variable": feature_names,
    "Importancia_Gain": importances_gain
}).sort("Importancia_Gain", descending=True)

df_importance_pl.head(10)

shape: (10, 2)
 Variable                Importancia_Gain
 ---                     ---
 str                     f64
 Online_Transaction      3.5465e6
 Log2_risk_factor        1.4213e6
 log_time_diff_m         309175.163691
 ratio_24_yearly_income  263798.971029
 sum_amount_24h          204852.89727
 mcc_rate                195076.222451
 hour_of_day             177926.559942
 amount                  133167.69202
 ic_upper_amt_99_7d      92902.473097
 N_7d                    92300.198003

Desde una perspectiva económica, se analizaron las cuantías monetarias asociadas a las predicciones del modelo, diferenciando entre el dinero recuperado mediante la correcta detección de operaciones fraudulentas (Verdaderos Positivos), las cantidades no detectadas debido a fallos en la identificación del fraude (Falsos Negativos) y las cantidades asociadas a operaciones legítimas que serían bloqueadas incorrectamente (Falsos Positivos). Asimismo, se calculó el porcentaje del importe total correspondiente a operaciones fraudulentas que podría ser recuperado en función del umbral de decisión seleccionado. Los resultados se muestran a continuación.

In [33]:
preds_test = model.predict(X_test)
test_results_df = test_df.with_columns(
    pl.Series("prediction", preds_test).cast(pl.Boolean)
)

calculate_financial_metrics(test_results_df)

shape: (1, 5)
 Recovered_Amount  Leaked_Amount  False_Positive_Cost  Total_Fraud  Recovery_Rate_Pct
 ---               ---            ---                  ---          ---
 f64               f64            f64                  f64          f64
 125317.36         31146.24       108329.87            156463.6     80.093619

La selección del umbral de decisión debe realizarse en función de los objetivos y costes asociados a la actividad de la empresa, buscando un equilibrio adecuado entre *recall* y *precision*. Por ejemplo, para un umbral de `0,89`, se obtiene un *recall* de `0,75` y una *precision* de `0,64`. Esto significa que el modelo identifica correctamente el 75 % de las operaciones fraudulentas y que, de cada 100 operaciones clasificadas como fraudulentas, 64 son efectivamente fraudulentas. En términos económicos, este umbral permite recuperar el 66 % del importe asociado a las operaciones fraudulentas.

In [50]:
_, _, _, _, test_preds_cal = create_test_report(model, calibrated_threshold=0.89)

test_results_cal_df = test_df.with_columns(
    pl.Series("prediction", test_preds_cal).cast(pl.Boolean)
)

calculate_financial_metrics(test_results_cal_df)

----------- TEST REPORT -----------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    466815
           1       0.75      0.64      0.69      1377

    accuracy                           1.00    468192
   macro avg       0.87      0.82      0.84    468192
weighted avg       1.00      1.00      1.00    468192

PR-AUC Score: 0.7462
Average Precision (AP) Score: 0.7463

shape: (1, 5)
 Recovered_Amount  Leaked_Amount  False_Positive_Cost  Total_Fraud  Recovery_Rate_Pct
 ---               ---            ---                  ---          ---
 f64               f64            f64                  f64          f64
 104099.87         52363.73       26662.65             156463.6     66.532964

La elección de este umbral supone un compromiso entre la cantidad de fraude detectada y el volumen de operaciones legítimas que podrían ser bloqueadas incorrectamente. En este caso, aunque se recupera un porcentaje inferior del importe total del fraude respecto a umbrales más bajos, también se reduce el volumen económico correspondiente a operaciones legítimas clasificadas incorrectamente como fraudulentas. Por tanto, el umbral óptimo no depende únicamente del rendimiento predictivo del modelo, sino también de los costes económicos asociados a los Falsos Positivos y Falsos Negativos.

Como futuras líneas de investigación, sería interesante incorporar nuevas características relacionadas con el comportamiento espacial de los clientes, como la utilización de coordenadas de comercios que no hayan sido previamente frecuentados. Asimismo, podría estudiarse la modificación de las estrategias utilizadas para generar las características mediante shift, con el objetivo de representar diferentes horizontes temporales del comportamiento histórico del cliente.

Finalmente, podrían evaluarse modelos específicamente diseñados para escenarios de detección de fraude sensibles al coste. Entre ellos se encuentran los enfoques CDST (Cost-sensitive Decision Tree), que permiten incorporar explícitamente una matriz de costes en el proceso de clasificación. También sería de interés explorar modelos basados en Graph Neural Networks (GNN), que permiten representar las relaciones entre clientes, tarjetas, comercios y transacciones mediante estructuras de grafos. Estos modelos podrían facilitar el análisis de patrones relacionales y de frecuencia de interacción entre los diferentes elementos del sistema financiero, proporcionando información complementaria a las características utilizadas en este trabajo.

## <span id="ref"></span> **5. Referencias**

<!-- BIBLIOGRAPHY START -->
<div class="csl-bib-body">
  <div class="csl-entry"><i id="zotero|24849794/T98H6WQU"></i>Caixabank Tech. (n.d.). <i>Transactions Fraud Datasets</i> [Data set]. Retrieved August 28, 2026, from <a href="https://www.kaggle.com/datasets/computingvictor/transactions-fraud-datasets">https://www.kaggle.com/datasets/computingvictor/transactions-fraud-datasets</a></div>
  <div class="csl-entry"><i id="zotero|24849794/BTXFK83Q"></i>Correa Bahnsen, A., Aouada, D., Stojanovic, A., &#38; Ottersten, B. (2016). Feature engineering strategies for credit card fraud detection. <i>Expert Systems with Applications</i>, <i>51</i>, 134–142. <a href="https://doi.org/10.1016/j.eswa.2015.12.030">https://doi.org/10.1016/j.eswa.2015.12.030</a></div>
  <div class="csl-entry"><i id="zotero|24849794/8RUI7M59"></i>Jendruszak, B. (2024, November 14). Costo del fraude: impacto en ingresos y reputación | SEON. <i>SEON ES</i>. <a href="https://seon.io/es/recursos/el-costo-total-del-fraude/">https://seon.io/es/recursos/el-costo-total-del-fraude/</a></div>
  <div class="csl-entry"><i id="zotero|24849794/7BUIWEJW"></i>Zhu, X., Ao, X., Qin, Z., Chang, Y., Liu, Y., He, Q., &#38; Li, J. (2021). Intelligent financial fraud detection practices in post-pandemic era. <i>The Innovation</i>, <i>2</i>(4), 100176. <a href="https://doi.org/10.1016/j.xinn.2021.100176">https://doi.org/10.1016/j.xinn.2021.100176</a></div>
</div>
<!-- BIBLIOGRAPHY END -->

## <span id="anexo"></span> **6. Anexo**

In [22]:
display(HTML(
    f'<a href="Anexo.html" target="_blank">Análisis exploratorio de variables automatizado realizado con Sweetviz</a>'))

<br>

---